'use client';
import {useRef,useState} from 'react';
import {unzipSync,strFromU8} from 'fflate';
import {settingsFromBackup,settingsKeys,settingsLabels,type SettingsKey} from '@/lib/orbit/backup-settings';
import {digest} from '@/lib/orbit/backup';
import {agentRequest} from '../agent/connections';
import type {WorkspaceData} from '@/lib/orbit/model';
type SettingsFile={payload:Record<string,unknown>;checksum:string};
type SettingsPreview={basis:string;revision:number;changes:{key:string;before:unknown;after:unknown}[]};
export function SettingsRestore({disabled,onRefresh}:{disabled:boolean;onRefresh:()=>Promise<void>}){
 const [file,setFile]=useState<SettingsFile|null>(null),[selection,setSelection]=useState<SettingsKey[]>([]),[preview,setPreview]=useState<SettingsPreview|null>(null),[working,setWorking]=useState(false),[message,setMessage]=useState('');const op=useRef(crypto.randomUUID()),lock=useRef(false);
 const reset=()=>{op.current=crypto.randomUUID();setPreview(null)};
 async function load(f:File){try{setMessage('');setFile(null);setSelection([]);reset();if(f.size>300*1024*1024)throw Error('큰 ZIP은 압축을 풀고 settings.json을 선택하세요.');let parsed:SettingsFile;if(f.name.endsWith('.zip')){const entries=unzipSync(new Uint8Array(await f.arrayBuffer()),{filter:e=>['settings.json','workspace.json'].includes(e.name)&&e.originalSize<=25000000});const bytes=entries['settings.json']??entries['workspace.json'];if(!bytes)throw Error('설정 또는 워크스페이스 백업이 없습니다.');parsed=JSON.parse(strFromU8(bytes));}else{if(f.size>25000000)throw Error('설정 파일은 25MB 이내여야 합니다.');parsed=JSON.parse(await f.text());}if(await digest(parsed.payload)!==parsed.checksum)throw Error('백업 검증값이 다릅니다.');if(parsed.payload.format==='orbit-backup/v2'){const payload=settingsFromBackup(parsed.payload.data as WorkspaceData,parsed.payload.capturedAt as string);parsed={payload,checksum:await digest(payload)};setMessage('구버전 백업의 개인 설정과 제안 이력을 읽었습니다. 별도 사운드·캘린더 설정은 새 ZIP의 settings.json에서 복원할 수 있습니다.');}setFile(parsed);}catch(e){setMessage((e as Error).message)}}
 async function run(action:'preview'|'restore'){if(lock.current)return;lock.current=true;setWorking(true);setMessage('');try{const r=await agentRequest('/api/backup/settings','POST',{action,...file,selection,basis:preview?.basis,operationId:op.current});if(action==='preview')setPreview(r);else{setMessage(r.replayed?'이 복원 요청은 이미 처리되었습니다.':'선택한 설정을 저장하고 다시 읽어 확인했습니다. 돌봄·자동 실행은 필요할 때 다시 켜세요. 외부 예약 설정은 AI 에이전트의 예약 설정에서 재승인할 수 있습니다.');setPreview(null);await onRefresh();}}catch(e){setMessage((e as Error).message)}finally{lock.current=false;setWorking(false)}}
 return <article className="phase2-record"><h2>전체 설정 복원</h2><p>선택한 개인 설정을 덮어쓰며 같은 번호의 기억·루틴·제안은 유지합니다. 연결된 업무·원문을 먼저 복원하세요. 이전 실행 승인은 되살리지 않습니다.</p><input aria-label="설정 백업 선택" type="file" accept=".zip,.json" disabled={disabled||working} onChange={e=>e.target.files?.[0]&&void load(e.target.files[0])}/>{file&&<><div className="backup-choices">{settingsKeys.map(key=><label className="backup-choice" key={key}><input type="checkbox" disabled={working||file.payload[key]===undefined} checked={selection.includes(key)} onChange={e=>{setSelection(s=>e.target.checked?[...s,key]:s.filter(k=>k!==key));reset()}}/>{settingsLabels[key]}{file.payload[key]===undefined?' · 백업에 없음':''}</label>)}</div><button className="secondary-button" disabled={disabled||working||!selection.length} onClick={()=>void run('preview')}>설정 변경 미리보기</button></>}{preview&&<section><h3>복원할 설정 확인</h3>{preview.changes.map(c=><details key={c.key}><summary>{settingsLabels[c.key as SettingsKey]}</summary><div className="field-grid"><div><strong>현재 값</strong><pre style={{whiteSpace:'pre-wrap',maxHeight:240,overflow:'auto'}}>{JSON.stringify(c.before,null,2)}</pre></div><div><strong>백업 값 · 실행은 재승인</strong><pre style={{whiteSpace:'pre-wrap',maxHeight:240,overflow:'auto'}}>{JSON.stringify(c.after,null,2)}</pre></div></div></details>)}<p>사운드는 멈춘 상태, 자동 실행은 꺼진 상태로 복원합니다. 기존 외부 예약은 변경하지 않습니다.</p><button className="primary-button" disabled={disabled||working} onClick={()=>void run('restore')}>확인한 설정 복원</button></section>}{message&&<p role="status">{message}</p>}</article>;
}
