'use client';
import {useEffect,useRef,useState} from 'react';
import type {WorkspaceData} from '@/lib/orbit/model';
import {morningScript} from '@/lib/orbit/phase4';
export function VoiceInput({onText,disabled=false}:{onText:(s:string)=>void;disabled?:boolean}){
 const [supported,setSupported]=useState(false),[recording,setRecording]=useState(false),[notice,setNotice]=useState('');const recognition=useRef<any>(null),timer=useRef<ReturnType<typeof setTimeout>|null>(null);const callback=useRef(onText);callback.current=onText;
 useEffect(()=>{setSupported(!!((window as any).SpeechRecognition||(window as any).webkitSpeechRecognition));return()=>{if(timer.current)clearTimeout(timer.current);if(recognition.current){recognition.current.onresult=null;recognition.current.onerror=null;recognition.current.onend=null;recognition.current.abort();}};},[]);
 useEffect(()=>{if(disabled&&recognition.current){recognition.current.onresult=null;recognition.current.abort();}},[disabled]);
 const stop=()=>recognition.current?.stop();
 function start(){try{const Engine=(window as any).SpeechRecognition||(window as any).webkitSpeechRecognition;const r=new Engine();recognition.current=r;r.lang='ko-KR';r.interimResults=false;r.continuous=false;r.onresult=(e:any)=>{const text=Array.from(e.results as any[]).map((x:any)=>x[0].transcript).join(' ').slice(0,8000);callback.current(text);setNotice('인식한 내용을 확인하고 보내기를 누르세요.');};r.onerror=(e:any)=>setNotice(e.error==='not-allowed'?'마이크 권한을 허용하거나 키보드로 입력하세요.':'음성을 인식하지 못했습니다. 다시 시도하거나 키보드로 입력하세요.');r.onend=()=>{setRecording(false);if(timer.current)clearTimeout(timer.current);recognition.current=null};r.start();setRecording(true);setNotice('듣고 있습니다. 최대 60초. 브라우저의 음성 인식 서비스를 사용합니다.');timer.current=setTimeout(()=>r.stop(),60000);}catch{setNotice('이 브라우저에서는 음성을 시작할 수 없습니다. 키보드로 입력하세요.')}}
 return <div className="orbit-voice-input"><button type="button" className="secondary-button" disabled={disabled||!supported} onClick={()=>recording?stop():start()} aria-pressed={recording}>{recording?'음성 입력 마치기':'음성으로 입력'}</button><small role="status">{notice||(!supported?'음성 미지원 환경에서는 키보드의 음성 입력을 사용할 수 있습니다.':'인식한 문장은 검토 후 전송합니다. 음성이 브라우저 제공자의 서버에서 처리될 수 있습니다.')}</small></div>;
}
export function VoicePanel({data,today,onAsk}:{data:WorkspaceData;today:string;onAsk:(s:string)=>void}){
 const [text,setText]=useState(''),[speaking,setSpeaking]=useState(false),[notice,setNotice]=useState(''),[supported,setSupported]=useState(false);const timer=useRef<ReturnType<typeof setTimeout>|null>(null);const script=morningScript(data,today);
 useEffect(()=>{setSupported('speechSynthesis'in window);return()=>{if(timer.current)clearTimeout(timer.current);window.speechSynthesis?.cancel();};},[]);
 function speak(){window.speechSynthesis.cancel();if(timer.current)clearTimeout(timer.current);const u=new SpeechSynthesisUtterance(script);u.lang='ko-KR';u.rate=1.1;u.onend=()=>{setSpeaking(false);if(timer.current)clearTimeout(timer.current)};u.onerror=()=>{setSpeaking(false);setNotice('읽기를 완료하지 못했습니다. 아래 원문을 확인하세요.')};window.speechSynthesis.speak(u);setSpeaking(true);timer.current=setTimeout(()=>{window.speechSynthesis.cancel();setSpeaking(false);setNotice('60초 읽기를 마쳤습니다. 남은 내용은 원문에서 확인하세요.');},60000);}
 return <section className="phase2-panel"><article className="phase2-record"><h2>아침 60초 브리핑</h2><p>{script}</p><button className="primary-button" disabled={!supported} onClick={()=>speaking?(window.speechSynthesis.cancel(),timer.current&&clearTimeout(timer.current),setSpeaking(false)):speak()}>{speaking?'읽기 중지':'브리핑 듣기'}</button><p role="status">{notice}</p></article><article className="phase2-record"><h2>짧게 말하고 검토하기</h2><VoiceInput onText={s=>setText(t=>(t+' '+s).trim().slice(0,8000))}/><label className="form-label">업무·결정·마감<textarea className="form-field" maxLength={8000} value={text} onChange={e=>setText(e.target.value)}/></label><button className="primary-button" disabled={!text.trim()} onClick={()=>onAsk(text)}>검토한 내용을 에이전트에 가져가기</button></article></section>;
}
