'use client';
import {useState} from 'react';
import type {WorkspaceData} from '@/lib/orbit/model';
import type {WorkspaceAction} from '@/lib/orbit/validation';
import {contactContext,monthlyReport} from '@/lib/orbit/phase4';
import type {Contact} from '@/lib/orbit/phase4-schema';
import {addDays} from '@/lib/orbit/dates';
type Props={data:WorkspaceData;today:string;busy:boolean;perform:(a:WorkspaceAction,m?:string)=>Promise<boolean>;onOpen:(kind:'note'|'task',id:string,revision?:number)=>void;onAsk:(s:string)=>void};
export function ExperimentsPanel({data,today,busy,perform,onOpen,onAsk}:Props){
 const blank=()=>({id:crypto.randomUUID(),title:'',projectId:data.projects[0]?.id??'',noteId:data.notes[0]?.id??'',noteRevision:data.notes[0]?.revision??1,hypothesis:'',action:'',metric:'',unit:'',baseline:0,target:1,direction:'up' as const,from:today,through:addDays(today,7),minutes:30});
 type Draft=Omit<ReturnType<typeof blank>,'direction'>&{direction:'up'|'down'};
 const [draft,setDraft]=useState<Draft|null>(null),[result,setResult]=useState<{id:string;value:number;evidence:string;conclusion:string}|null>(null);
 const field=(key:keyof Draft,label:string,type='text')=><label className="form-label" key={key}>{label}<input className="form-field" required maxLength={['hypothesis','action'].includes(key)?2000:160} type={type} value={draft![key]} onChange={e=>setDraft({...draft!,[key]:type==='number'?Number(e.target.value):e.target.value})}/></label>;
 return <section className="phase2-panel"><div className="phase2-toolbar"><p>읽은 자료를 작은 실험으로 검증하고, 결과를 원문과 연결합니다.</p><button className="primary-button" disabled={busy||!data.projects.length||!data.notes.length} onClick={()=>setDraft(blank())}>새 실험</button></div>{!data.notes.length&&<p>근거로 삼을 지식이나 위키를 먼저 저장하세요.</p>}
 {draft&&<form className="phase2-record" onSubmit={async e=>{e.preventDefault();if(await perform({type:'experiment.start',experiment:draft},'실험과 실행 업무를 함께 저장했습니다.'))setDraft(null)}}><h2>실험 설계</h2>{field('title','실험 이름')}<label className="form-label">적용할 사업<select className="form-field" value={draft.projectId} onChange={e=>setDraft({...draft,projectId:e.target.value})}>{data.projects.map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select></label><label className="form-label">출발한 지식<select className="form-field" value={draft.noteId} onChange={e=>setDraft({...draft,noteId:e.target.value,noteRevision:data.notes.find(n=>n.id===e.target.value)?.revision??1})}>{data.notes.map(n=><option key={n.id} value={n.id}>{n.title}</option>)}</select></label><button type="button" className="text-button" onClick={()=>onAsk(`원문 ID ${draft.noteId} 버전 ${draft.noteRevision}을 읽고 사업 ${draft.projectId}에 적용할 작은 실험을 설계해 줘. 가설, 최소 행동, 기간, 기준값·목표값·단위·개선 방향을 구분하고 모르는 수치는 미확인으로 남겨 줘. 실행하거나 저장하기 전에 검토할 수 있게 제안해 줘.`)}>근거를 읽고 실험 초안 요청</button>{field('hypothesis','검증할 가설')}{field('action','작게 실행할 행동')}<div className="phase3-fields">{field('metric','측정 지표')}{field('unit','단위')}{field('baseline','시작 값','number')}{field('target','성공 기준 값','number')}</div><label className="form-label">개선 방향<select className="form-field" value={draft.direction} onChange={e=>setDraft({...draft,direction:e.target.value as 'up'|'down'})}><option value="up">목표 이상</option><option value="down">목표 이하</option></select></label><div className="phase3-fields">{field('from','시작','date')}{field('through','종료','date')}{field('minutes','첫 행동 예상 시간(분)','number')}</div><button className="primary-button" disabled={busy}>실험과 첫 행동 등록</button><button type="button" className="text-button" onClick={()=>setDraft(null)}>닫기</button></form>}
 {(data.experiments??[]).map(e=><article className="phase2-record" key={e.id}><h2>{e.title}</h2><p>{data.projects.find(p=>p.id===e.projectId)?.name} · {e.from}–{e.through} · {e.status==='active'?'실행 중':e.status==='completed'?'결과 기록':'중단'}</p><p>{e.hypothesis}</p><p>{e.action}</p><p>{e.metric} · {e.baseline} → {e.target} {e.unit}</p><button className="text-button" onClick={()=>onOpen('note',e.noteId,e.noteRevision)}>출발한 원문 v{e.noteRevision}</button><button className="text-button" onClick={()=>onOpen('task',e.taskId)}>실행 업무</button>{e.result?<><p>{e.result.met?'기록한 성공 기준 충족':'기록한 성공 기준 미충족'} · {e.result.value} {e.unit}</p><p>{e.result.evidence}</p><p>{e.result.conclusion}</p></>:e.status==='active'&&<><button className="secondary-button" disabled={busy} onClick={()=>setResult({id:e.id,value:e.baseline,evidence:'',conclusion:''})}>결과 기록</button><button className="text-button" disabled={busy} onClick={()=>void perform({type:'experiment.stop',id:e.id},'실험을 중단했습니다. 연결 업무의 상태는 직접 확인하세요.')}>실험 중단</button></>}</article>)}
 {result&&<form className="phase2-record" onSubmit={async e=>{e.preventDefault();if(await perform({type:'experiment.finish',...result},'측정 근거와 실험 결과를 저장했습니다.'))setResult(null)}}><h2>관측한 결과</h2><label className="form-label">측정값<input className="form-field" type="number" step="any" required value={result.value} onChange={e=>setResult({...result,value:Number(e.target.value)})}/></label><label className="form-label">검증 가능한 근거<textarea className="form-field" required maxLength={2000} value={result.evidence} onChange={e=>setResult({...result,evidence:e.target.value})}/></label><label className="form-label">배운 점·확대 또는 중단 판단<textarea className="form-field" required maxLength={2000} value={result.conclusion} onChange={e=>setResult({...result,conclusion:e.target.value})}/></label><button className="primary-button" disabled={busy}>결과 저장</button><button type="button" className="text-button" onClick={()=>setResult(null)}>닫기</button></form>}
 </section>;
}
export function ContactsPanel({data,today,busy,perform,onOpen,onAsk}:Props){
 const [query,setQuery]=useState(''),[draft,setDraft]=useState<Contact|null>(null);
 function links(key:'projectIds'|'noteIds'|'decisionIds'|'delegationIds'|'eventIds',title:string,records:{id:string;title?:string;name?:string}[]){return <details><summary>{title} · {draft![key].length}개 연결</summary>{records.map(r=><label className="backup-choice" key={r.id}><input type="checkbox" checked={draft![key].includes(r.id)} onChange={e=>setDraft({...draft!,[key]:e.target.checked?[...draft![key],r.id]:draft![key].filter(id=>id!==r.id)})}/>{r.name??r.title}</label>)}</details>}
 return <section className="phase2-panel"><div className="phase2-toolbar"><input className="form-field" aria-label="사람·거래처 검색" placeholder="이름·거래처 검색" value={query} onChange={e=>setQuery(e.target.value)}/><button className="primary-button" disabled={busy} onClick={()=>setDraft({id:crypto.randomUUID(),name:'',organization:'',role:'',aliases:[],projectIds:[],noteIds:[],decisionIds:[],delegationIds:[],eventIds:[],memo:'',updatedAt:''})}>새 카드</button></div>
 {draft&&<form className="phase2-record" onSubmit={async e=>{e.preventDefault();const {updatedAt,...contact}=draft;if(await perform({type:'contact.upsert',contact},'업무 맥락 카드를 저장했습니다.'))setDraft(null)}}><h2>사람·거래처 연결</h2>{(['name','organization','role','memo'] as const).map((k,i)=><label className="form-label" key={k}>{['이름','거래처·조직','역할','만남 전에 확인할 내용'][i]}<input className="form-field" required={k==='name'} maxLength={k==='memo'?2000:k==='organization'?150:100} value={draft[k]} onChange={e=>setDraft({...draft,[k]:e.target.value})}/></label>)}<p className="form-hint">동명이인을 합치지 않도록 관계 자료를 직접 선택합니다. 위임 담당자 이름이 정확히 일치하는 약속은 함께 표시합니다.</p>{links('projectIds','관련 사업',data.projects)}{links('noteIds','자료',data.notes)}{links('decisionIds','합의·결정',data.decisions??[])}{links('delegationIds','약속',data.delegations??[])}{links('eventIds','만남',data.events.filter(e=>e.kind==='meeting'&&!e.id.startsWith('google:')))}<button className="primary-button" disabled={busy}>저장</button><button type="button" className="text-button" onClick={()=>setDraft(null)}>닫기</button></form>}
 {(data.contacts??[]).filter(c=>(c.name+' '+c.organization).toLowerCase().includes(query.toLowerCase())).map(c=>{const ctx=contactContext(data,c);return <article className="phase2-record" key={c.id}><h2>{c.name} <small>{c.organization} · {c.role}</small></h2><p>{c.memo}</p><p>{ctx.projects.map(p=>p.name).join(' · ')||'연결한 사업 없음'}</p><h3>미결 약속</h3>{ctx.promises.filter(d=>!['verified','cancelled'].includes(d.status)).map(d=><p key={d.id}>{d.deliverable} · {d.assignee} · {d.due}{d.checkDate<=today?' · 확인 필요':''}</p>)}<h3>합의와 자료</h3>{ctx.decisions.map(d=><p key={d.id}>{d.choice} · 재검토 {d.reviewDate}</p>)}{ctx.notes.map(n=><button className="link-card" key={n.id} onClick={()=>onOpen('note',n.id)}>{n.title}</button>)}{ctx.meetings.map(e=><p key={e.id}>{e.date} · {e.title}</p>)}<button className="text-button" disabled={busy} onClick={()=>setDraft(c)}>연결·내용 수정</button><button className="text-button" onClick={()=>onAsk(`${c.name}(${c.organization}) 만남을 준비해 줘. 다음 연결 맥락의 원문을 확인해 질문·미결 약속·오늘 결정할 것을 정리해 줘. 이름이 같다는 이유로 다른 사람 자료를 합치지 마. ${JSON.stringify(ctx).slice(0,6500)}`)}>만남 브리핑 요청</button><button className="text-button" disabled={busy} onClick={()=>{if(window.confirm('이 사람 카드를 삭제할까요? 연결된 원문과 업무는 유지됩니다.'))void perform({type:'contact.delete',id:c.id})}}>카드 삭제</button></article>})}</section>;
}
export function MonthlyPanel({data,today,busy,perform,onOpen,onAsk}:Props){
 const previous=addDays(today.slice(0,7)+'-01',-1).slice(0,7),[month,setMonth]=useState(previous),[review,setReview]=useState<{id:string;value:number;note:string}|null>(null);const report=data.monthlyReports?.find(r=>r.id===month),preview=monthlyReport(data,month,new Date()),r=report??preview;
 return <section className="phase2-panel"><div className="phase2-toolbar"><label className="form-label">분석 월<input type="month" className="form-field" max={previous} value={month} onChange={e=>{if(e.target.value){setMonth(e.target.value);setReview(null)}}}/></label><button className="primary-button" disabled={busy||!!report||month>previous} onClick={()=>void perform({type:'monthly.generate',month},'월간 보고서를 고정된 기록으로 저장했습니다.')}>{report?'저장된 보고서':'이 달 보고서 저장'}</button></div><p>지난달 보고서는 서버가 자동 준비합니다. 채택한 개선은 다음 달 측정 결과로 다시 확인하세요.</p><article className="phase2-record"><h2>{month} 일하는 방식</h2><p>{r.summary}</p><p className="form-hint">{r.coverage}</p><div className="phase2-metrics"><article>기록된 실제 시간<strong>{r.metrics.minutes}분</strong></article><article>기록 사이 사업 전환<strong>{r.metrics.switches}회</strong></article><article>나에게 모인 신규 결정<strong>{r.metrics.decisions}건</strong></article></div><button className="text-button" onClick={()=>onAsk(`이 월간 보고서의 근거 기록을 확인해 업무 구조 개선안을 깊게 검토해 줘. 기록 누락을 실패로 해석하지 말고 실제 원인과 가설을 구분해 줘. ${JSON.stringify(r).slice(0,6800)}`)}>근거를 바탕으로 심층 검토</button></article>
 {(['stop','delegate','standardize'] as const).map((kind,i)=><article className="phase2-record" key={kind}><h2>{['다음 달 중단할 일','다음 달 위임할 일','다음 달 표준화할 일'][i]}</h2>{r.recommendations.filter(a=>a.kind===kind).map(a=><div key={a.id}><strong>{a.title}</strong><ul>{a.evidence.map((e,i)=><li key={i}>{e}</li>)}</ul>{a.taskId&&data.tasks.some(t=>t.id===a.taskId)&&<button className="text-button" onClick={()=>onOpen('task',a.taskId!)}>근거 업무</button>}<p>기준 월 발생 {a.baseline}건 · {a.status==='suggested'?'검토 전':a.status==='adopted'?'채택':'보류'}</p>{report&&<><button className="secondary-button" disabled={busy} onClick={()=>void perform({type:'monthly.decide',month,id:a.id,status:'adopted'})}>개선 채택</button><button className="text-button" disabled={busy} onClick={()=>void perform({type:'monthly.decide',month,id:a.id,status:'dismissed'})}>보류</button>{a.status==='adopted'&&<button className="text-button" disabled={busy} onClick={()=>setReview({id:a.id,value:a.baseline,note:''})}>다음 달 효과 기록</button>}</>}{a.review&&<p>재확인 {a.review.date} · {a.baseline} → {a.review.value}건 · {a.review.note}</p>}</div>)}{!r.recommendations.some(a=>a.kind===kind)&&<p>현재 기록에서 제안할 충분한 근거가 없습니다.</p>}</article>)}
 {review&&<form className="phase2-record" onSubmit={async e=>{e.preventDefault();if(await perform({type:'monthly.review',month,...review},'다음 달 효과를 기록했습니다.'))setReview(null)}}><label className="form-label">다음 달 같은 문제의 발생 건수<input className="form-field" type="number" min="0" required value={review.value} onChange={e=>setReview({...review,value:Number(e.target.value)})}/></label><label className="form-label">집계 기간·근거·달라진 조건<textarea className="form-field" required maxLength={1000} value={review.note} onChange={e=>setReview({...review,note:e.target.value})}/></label><button className="primary-button" disabled={busy}>효과 저장</button></form>}</section>;
}
