import {z} from 'zod';
import {preferencesSchema,taskSchema,dateSchema} from './validation.ts';
import {briefContentSchema} from './brief/schema.ts';
import {soundState} from './sound/state.ts';
import {digest} from './backup.ts';
import {readWorkspace,RevisionConflict,type Database} from '../../db/repository.ts';
import {validateLinks,DomainError} from './reducer.ts';
import type {WorkspaceData,Proposal,Task} from './model.ts';
const id=z.string().min(1).max(100),minute=z.number().int().min(0).max(1440),date=dateSchema,stamp=z.string().datetime();
const memory=z.object({id,statement:z.string().min(1).max(600),kind:z.enum(['preference','constraint','strategy','reflection']),origin:z.enum(['user','records','saju']),sources:z.array(z.object({kind:z.enum(['note','task','review']),id,revision:z.number().int().positive().optional(),signature:z.string().max(100).optional()}).strict()).max(6),confirmedOn:date,updatedOn:date}).strict().refine(m=>m.origin!=='saju'||m.kind==='reflection').refine(m=>m.origin!=='records'||m.sources.length>0);
const care=z.object({id,title:z.string().min(1).max(160),domain:z.enum(['health','mind','learning']),minutes:z.number().int().min(2).max(120),days:z.array(z.number().int().min(0).max(6)).min(1).max(7).refine(a=>new Set(a).size===a.length),start:minute,goalId:id.optional(),active:z.boolean(),log:z.array(date).max(5000)}).strict();
const chief=z.object({settings:z.object({tone:z.enum(['gentle','balanced','firm']),quietStart:minute,quietEnd:minute,pausedUntil:stamp.optional()}).strict().optional(),checkins:z.array(z.object({date,energy:z.enum(['low','normal','high']),strain:z.enum(['light','normal','heavy']),note:z.string().max(500),updatedAt:stamp}).strict()).max(90).optional(),responses:z.array(z.object({key:z.string().max(220),kind:z.enum(['snooze','blocked','recovered']),until:stamp,reason:z.string().max(500),at:stamp}).strict()).max(100).optional()}).strict();
const item=z.object({id:z.string().min(1).max(220),taskId:id,start:minute,end:minute,reason:z.string().max(5000),state:z.enum(['pending','approved','deferred']),draftTask:taskSchema.optional(),deferReason:z.string().max(2000).optional(),revisitDate:date.optional(),role:z.enum(['laser','must','fill']).optional(),quadrant:z.enum(['A','B','C','D']).optional(),cognition:z.enum(['high','mid','low','external']).optional(),factor:z.number().positive().optional(),estimate:z.number().positive().optional()}).strict().refine(i=>i.end>i.start);
const brief=briefContentSchema.extend({date,cutoff:z.string().max(100),generatedAt:stamp,sourceRevision:z.number().int().nonnegative(),sourceTurnId:id,coverage:z.object({projects:z.number(),tasks:z.number(),completed:z.number(),incomplete:z.number(),notes:z.number(),noteBodies:z.number(),reviews:z.number(),events:z.number(),conversations:z.number(),warnings:z.array(z.string()),google:z.string(),plaud:z.string()}),evidence:z.array(z.object({id:z.string().max(180),kind:z.enum(['metric','project','task','note','review','event','conversation','decision','delegation','plaud','memory','goal']),recordId:z.string().max(500),title:z.string().max(2000),date:z.string().optional(),revision:z.number().optional(),excerpt:z.string().max(10000).optional()})).max(200)});
const proposal=z.object({id,date,items:z.array(item).max(100),draftTasks:z.array(taskSchema).max(100).optional(),unscheduled:z.array(id).max(3000),budget:z.number().nonnegative(),energy:z.enum(['low','normal','high']),laser:z.object({taskId:id.optional(),status:z.enum(['placed','failed','none']),minutes:z.number(),note:z.string().max(5000)}).optional(),delegate:z.array(id).max(3000).optional(),brief:brief.optional()});
const schedule=z.object({hours:z.union([z.literal(6),z.literal(12),z.literal(24)]),delivery:z.enum(['local','telegram']),research:z.string().max(300),includeCare:z.boolean()});
export const settingsSchema=z.object({format:z.literal('orbit-settings/v1'),capturedAt:stamp,preferences:preferencesSchema,dominoProjectId:id.optional(),memories:z.array(memory).max(60),careRoutines:z.array(care).max(12),chief,proposals:z.array(proposal).max(5000),sound:soundState.optional(),calendar:z.array(z.string().min(1).max(500)).min(1).max(10).optional(),runtime:z.object({enabled:z.boolean(),eveningHour:z.number().int().min(0).max(23)}).optional(),chiefSchedule:schedule.optional()});
export const settingsKeys=['preferences','memories','careRoutines','chief','proposals','sound','calendar','runtime','chiefSchedule'] as const;
export type SettingsKey=typeof settingsKeys[number];
export const settingsLabels:Record<SettingsKey,string>={preferences:'시간대·근무·집중·리듬·도미노 설정',memories:'개인 기억과 근거',careRoutines:'돌봄·학습 루틴과 기록',chief:'비서실장 말투·조용한 시간·체크인',proposals:'실행 제안 이력',sound:'사운드 설정·즐겨찾기·루틴·기록',calendar:'조회 캘린더 선택',runtime:'자동 실행 시간 · 꺼진 상태로 복원',chiefSchedule:'외부 예약 설정 · 재승인 후보'};
export const settingsSelection=z.array(z.enum(settingsKeys)).min(1).max(settingsKeys.length).refine(s=>new Set(s).size===s.length);
export function settingsFromBackup(data:WorkspaceData,capturedAt:string,rows:Record<string,any[]>={}){
 const get=(table:string,field:string)=>{const value=rows[table]?.[0]?.[field];return value?JSON.parse(value):undefined};
 const remote=get('orbit_chief_jobs','config_json'),candidate=remote?.restored??remote?.confirmed;
 return settingsSchema.parse({format:'orbit-settings/v1',capturedAt,preferences:data.preferences,dominoProjectId:data.dominoProjectId,memories:data.memories??[],careRoutines:data.careRoutines??[],chief:data.chief??{},proposals:data.proposals,sound:get('orbit_sound_state','state_json'),calendar:get('orbit_calendar_settings','selected_json'),runtime:get('orbit_daily_runtime','config_json'),chiefSchedule:candidate});
}
const tables=[['orbit_sound_state','state_json'],['orbit_calendar_settings','selected_json'],['orbit_daily_runtime','config_json'],['orbit_chief_jobs','config_json']] as const;
async function stateOf(db:Database,owner:string){const snapshot=await readWorkspace(db,owner);const rows=await db.batch(tables.map(([table])=>db.prepare(`SELECT * FROM ${table} WHERE owner_id=?`).bind(owner)));const state=rows.map(r=>r.results?.[0] as any??null);return {snapshot,state,basis:await digest({revision:snapshot.revision,state:state.map((r,i)=>[r?.[tables[i][1]]??'',r?.revision??0])})};}
const cleanDraft=(t:Task):Task=>({...t,startedAt:undefined,focus:false,focusDate:undefined,laserDate:undefined,planHoldUntil:undefined,planHoldReason:undefined,planHoldProposalId:undefined});
export function planSettings(current:WorkspaceData,raw:unknown,selection:SettingsKey[]){
 const parsed=settingsSchema.safeParse(raw);if(!parsed.success)throw new DomainError('설정 백업을 확인해 주세요: '+parsed.error.issues[0]?.path.join('.'));
 const source=parsed.data,next=structuredClone(current),changes:{key:SettingsKey;before:unknown;after:unknown}[]=[];
 const merge=<T extends {id:string}>(a:T[],b:T[])=>{if(new Set(b.map(x=>x.id)).size!==b.length)throw new DomainError('설정 백업에 중복 기록이 있습니다.');return [...a,...b.filter(x=>!a.some(y=>y.id===x.id))]};
 for(const key of selection){if(source[key]===undefined)throw new DomainError(settingsLabels[key]+' 설정이 백업에 없습니다.');
  if(key==='preferences'){next.preferences=source.preferences;next.dominoProjectId=source.dominoProjectId;}
  if(key==='memories')next.memories=merge(current.memories??[],source.memories);
  if(key==='careRoutines')next.careRoutines=merge(current.careRoutines??[],source.careRoutines.map(r=>({...r,active:false})));
  if(key==='chief')next.chief={settings:source.chief.settings,checkins:[...new Map([...(source.chief.checkins??[]),...(current.chief?.checkins??[])].map(x=>[x.date,x])).values()].slice(-90),responses:[...new Map([...(source.chief.responses??[]),...(current.chief?.responses??[])].map(x=>[x.key,x])).values()].slice(-100)};
  if(key==='proposals'){
   if(new Set(source.proposals.map(p=>p.id)).size!==source.proposals.length)throw new DomainError('제안 번호가 중복되었습니다.');
   for(const p of source.proposals){if(new Set(p.items.map(i=>i.id)).size!==p.items.length||new Set(p.items.map(i=>i.taskId)).size!==p.items.length||p.items.some(i=>i.draftTask&&i.taskId!==i.draftTask.id)||current.proposals.some(x=>x.id===p.id&&x.date!==p.date))throw new DomainError('제안의 업무와 번호를 확인하세요.');}
   if(new Set(source.proposals.map(p=>p.date)).size!==source.proposals.length)throw new DomainError('제안 날짜가 중복되었습니다.');
   const imported=source.proposals.filter(p=>!current.proposals.some(x=>x.date===p.date));
   for(const p of imported){const drafts=[...p.draftTasks??[],...p.items.flatMap(i=>i.draftTask?[i.draftTask]:[])];const pool=[...new Map([...drafts,...next.tasks].map(t=>[t.id,t])).values()];validateLinks({...next,tasks:pool});if([...p.items.map(i=>i.taskId),...p.unscheduled,...p.delegate??[],...p.laser?.taskId?[p.laser.taskId]:[]].some(id=>!pool.some(t=>t.id===id)))throw new DomainError('제안에 연결된 할 일을 먼저 복원하세요.');}
   next.proposals=[...current.proposals,...imported.map(p=>({...p,draftTasks:p.draftTasks?.map(cleanDraft),items:p.items.map(i=>({...i,draftTask:i.draftTask?cleanDraft(i.draftTask):undefined,state:i.state==='approved'?'pending' as const:i.state}))}))] as Proposal[];
  }
  changes.push({key,before:key==='preferences'?{...current.preferences,dominoProjectId:current.dominoProjectId}:key in current?(current as any)[key]:null,after:key==='preferences'?{...next.preferences,dominoProjectId:next.dominoProjectId}:key in next?(next as any)[key]:source[key]});
 }
 validateLinks(next);if(new TextEncoder().encode(JSON.stringify(next)).length>950000)throw new DomainError('설정 복원 후 저장 한도를 넘습니다.');
 return {next,source,changes};
}
function separateSettings(source:z.infer<typeof settingsSchema>,state:any[],selection:SettingsKey[]){
 const separate=new Map<number,string>();
 if(selection.includes('sound')){const old=state[0]?soundState.parse(JSON.parse(state[0].state_json)):null;if(old?.active)throw new DomainError('재생 중인 사운드를 마친 뒤 복원하세요.');const s=structuredClone(source.sound!);const sessions=[...s.sessions,...s.active?[{...s.active,status:'abandoned' as const,finished_at:Date.parse(source.capturedAt)}]:[]];s.sessions=[...new Map([...sessions,...old?.sessions??[]].map(x=>[x.id,x])).values()];s.active=null;s.routines=[...new Map([...s.routines,...old?.routines??[]].map(x=>[x.id,x])).values()];soundState.parse(s);separate.set(0,JSON.stringify(s));}
 if(selection.includes('calendar'))separate.set(1,JSON.stringify([...new Set(source.calendar!)]));
 if(selection.includes('runtime'))separate.set(2,JSON.stringify({enabled:false,eveningHour:source.runtime!.eveningHour}));
 if(selection.includes('chiefSchedule'))separate.set(3,JSON.stringify({...state[3]?JSON.parse(state[3].config_json):{},restored:source.chiefSchedule}));
return separate;
}
export async function previewSettings(db:Database,owner:string,raw:unknown,selection:SettingsKey[]){const state=await stateOf(db,owner),plan=planSettings(state.snapshot.data,raw,selection),separate=separateSettings(plan.source,state.state,selection);for(const c of plan.changes){const index={sound:0,calendar:1,runtime:2,chiefSchedule:3}[c.key as 'sound'];if(index!==undefined){c.before=state.state[index]?JSON.parse(state.state[index][tables[index][1]]):null;c.after=JSON.parse(separate.get(index)!);}}return {basis:state.basis,revision:state.snapshot.revision,changes:plan.changes};}
export async function restoreSettings(db:Database,owner:string,raw:unknown,selection:SettingsKey[],basis:string,operationId:string,checksum:string){
 if(await digest(raw)!==checksum)throw new DomainError('설정 백업 검증값이 다릅니다.');const hash=await digest({kind:'settings',checksum,selection});
 const prior=await db.prepare('SELECT action_hash FROM orbit_mutations WHERE owner_id=? AND operation_id=?').bind(owner,operationId).first<{action_hash:string}>();if(prior){if(prior.action_hash!==hash)throw new RevisionConflict('같은 복원 번호의 내용이 다릅니다.');return {replayed:true};}
 const state=await stateOf(db,owner);if(state.basis!==basis)throw new RevisionConflict('미리보기 이후 설정이 변경됐습니다. 다시 검토해 주세요.');const plan=planSettings(state.snapshot.data,raw,selection),at=new Date().toISOString();
 for(const m of (selection.includes('memories')?plan.next.memories??[]:[]).filter(m=>!state.snapshot.data.memories?.some(x=>x.id===m.id)))for(const s of m.sources){if(s.kind==='note'&&s.revision){const n=plan.next.notes.find(n=>n.id===s.id);if(!n)throw new DomainError('기억의 원문 기록을 먼저 복원하세요.');if(n.bodyStored||s.revision!==(n.revision??1)){if(!await db.prepare('SELECT 1 FROM orbit_note_revisions WHERE owner_id=? AND note_id=? AND revision=?').bind(owner,s.id,s.revision).first())throw new DomainError('기억의 원문 버전이 없습니다. 기록 이력을 먼저 복원하세요.');}}}
 const newMemories=(plan.next.memories??[]).filter(m=>!state.snapshot.data.memories?.some(x=>x.id===m.id));if(newMemories.length&&await db.prepare("SELECT id FROM orbit_data_trash WHERE owner_id=? AND category='memories' AND record_id IN (SELECT value FROM json_each(?)) LIMIT 1").bind(owner,JSON.stringify(newMemories.map(m=>m.id))).first())throw new DomainError('휴지통의 기억은 데이터 관리에서 먼저 복원하세요.');
 const separate=separateSettings(plan.source,state.state,selection);
 const rawState=JSON.stringify({...plan.next,events:plan.next.events.filter(e=>!e.id.startsWith('google:'))});
 const guard=tables.map(([table,column])=>`COALESCE((SELECT ${column} FROM ${table} WHERE owner_id=?),'')=?`).join(' AND ')+' AND COALESCE((SELECT revision FROM orbit_sound_state WHERE owner_id=?),0)=?';
 const guardValues=tables.flatMap(([_,column],i)=>[owner,state.state[i]?.[column]??'']).concat([owner,state.state[0]?.revision??0]);
 const idle=`NOT EXISTS(SELECT 1 FROM orbit_daily_runtime WHERE owner_id=? AND lease_until>?) AND NOT EXISTS(SELECT 1 FROM orbit_chief_jobs WHERE owner_id=? AND lease_until>?) AND NOT EXISTS(SELECT 1 FROM orbit_agent_turns WHERE owner_id=? AND status='running') AND NOT EXISTS(SELECT 1 FROM orbit_agent_actions WHERE owner_id=? AND state='applying') AND NOT EXISTS(SELECT 1 FROM orbit_agent_orders WHERE owner_id=? AND json_extract(state_json,'$.status') NOT IN ('completed','failed','cancelled','unknown')) AND NOT EXISTS(SELECT 1 FROM orbit_aside_jobs WHERE owner_id=? AND status IN ('queued','awaiting_approval','running','stop_requested','needs_attention')) AND NOT EXISTS(SELECT 1 FROM orbit_calendar_exports WHERE owner_id=? AND json_extract(state_json,'$.status')='publishing' AND COALESCE(json_extract(state_json,'$.leaseUntil'),0)>?)`;
 const idleValues=[owner,Date.now(),owner,Date.now(),owner,owner,owner,owner,owner,Date.now()];const revision=state.snapshot.revision+1;
 const update=db.prepare(`INSERT INTO orbit_workspaces(owner_id,revision,state_json,mutation_id,updated_at) SELECT ?,?,?,?,? WHERE ${guard} AND ${idle} ON CONFLICT(owner_id) DO UPDATE SET revision=excluded.revision,state_json=excluded.state_json,mutation_id=excluded.mutation_id,updated_at=excluded.updated_at WHERE orbit_workspaces.revision=? AND ${guard} AND ${idle}`).bind(owner,revision,rawState,operationId,at,...guardValues,...idleValues,state.snapshot.revision,...guardValues,...idleValues);
 const gate='EXISTS(SELECT 1 FROM orbit_workspaces WHERE owner_id=? AND revision=? AND mutation_id=?)',v=[owner,revision,operationId];const statements=[update];
 for(const [index,value] of separate){if(index===0)statements.push(db.prepare(`INSERT INTO orbit_sound_state(owner_id,revision,state_json,updated_at) SELECT ?,?,?,? WHERE ${gate} ON CONFLICT(owner_id) DO UPDATE SET revision=excluded.revision,state_json=excluded.state_json,updated_at=excluded.updated_at`).bind(owner,(state.state[0]?.revision??0)+1,value,at,...v));if(index===1)statements.push(db.prepare(`INSERT INTO orbit_calendar_settings(owner_id,selected_json,updated_at) SELECT ?,?,? WHERE ${gate} ON CONFLICT(owner_id) DO UPDATE SET selected_json=excluded.selected_json,updated_at=excluded.updated_at`).bind(owner,value,at,...v));if(index>=2)statements.push(db.prepare(`INSERT INTO ${tables[index][0]}(owner_id,config_json,lease_until) SELECT ?,?,0 WHERE ${gate} ON CONFLICT(owner_id) DO UPDATE SET config_json=excluded.config_json`).bind(owner,value,...v));}
 if(selection.includes('calendar')||selection.includes('preferences'))statements.push(db.prepare(`DELETE FROM orbit_calendar_cache WHERE owner_id=? AND ${gate}`).bind(owner,...v));
 statements.push(db.prepare(`INSERT INTO orbit_mutations(owner_id,operation_id,action_hash,revision,created_at) SELECT ?,?,?,?,? WHERE ${gate}`).bind(owner,operationId,hash,revision,at,...v));const result=await db.batch(statements);if(result[0]?.meta?.changes!==1)throw new RevisionConflict('설정이 변경되었거나 실행 중입니다. 다시 미리보기를 확인하세요.');
 const stored=await db.prepare('SELECT state_json FROM orbit_workspaces WHERE owner_id=?').bind(owner).first<{state_json:string}>();if(stored?.state_json!==rawState)throw new RevisionConflict('복원 후 다른 변경이 있었습니다. 현재 설정을 다시 확인하세요.');for(const [i,value] of separate){const row=await db.prepare(`SELECT ${tables[i][1]} AS value FROM ${tables[i][0]} WHERE owner_id=?`).bind(owner).first<{value:string}>();if(row?.value!==value)throw new RevisionConflict('설정 복원 후 변경이 감지되었습니다. 다시 확인하세요.');}
 return {restored:selection,verified:true};
}
