'use client';
import {useCallback,useEffect,useState} from 'react';
import {Dialog,DialogContent,DialogHeader,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import type {Project} from '@/lib/orbit/model';
import {agentRequest} from './connections';
import './activity-library.css';
const categories:Record<string,string>={general:'일반',research:'조사',development:'개발',meeting:'회의',finance:'재무',marketing:'마케팅',operations:'운영'};
interface RecordItem {id:string;source:string;title:string;project_id:string|null;category:string;summary:string;message_offset:number;updated_at:string;metadata_json:string}
interface Message {id:string;role:string;content:string;tool_name:string;tool_calls:string;timestamp:string}
interface Listing {items:RecordItem[];hasMore:boolean;sources:{source:string;count:number}[];status:{lastSync:string|null;lastError:string;pending:number;cycles:number;sessions:number;messages:number;coverage:string}}
export function ActivityLibrary({projects,onClose}:{projects:Project[];onClose:()=>void}){
 const [data,setData]=useState<Listing|null>(null),[query,setQuery]=useState(''),[source,setSource]=useState(''),[project,setProject]=useState(''),[offset,setOffset]=useState(0),[busy,setBusy]=useState(false),[error,setError]=useState(''),[detail,setDetail]=useState<{record:RecordItem;messages:Message[];hasMore:boolean}|null>(null),[messageOffset,setMessageOffset]=useState(0);
 const refresh=useCallback(async()=>{const r=await agentRequest('/api/agent/activity?'+new URLSearchParams({q:query,source,project,offset:String(offset)}));setData(r);},[query,source,project,offset]);
 useEffect(()=>{let live=true;const timer=setTimeout(()=>{void refresh().catch(e=>{if(live)setError(e.message)})},200);return()=>{live=false;clearTimeout(timer)}},[refresh]);
 async function sync(){setBusy(true);setError('');try{await agentRequest('/api/agent/activity','POST',{action:'sync'});await refresh()}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
 async function open(id:string,start=0){setBusy(true);setError('');try{setDetail(await agentRequest('/api/agent/activity?'+new URLSearchParams({id,offset:String(start)})));setMessageOffset(start)}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
 async function classify(id:string,projectId:string|null,category:string){setBusy(true);setError('');try{await agentRequest('/api/agent/activity','POST',{action:'classify',id,projectId,category});await refresh();if(detail?.record.id===id)setDetail({...detail,record:{...detail.record,project_id:projectId,category}})}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
 return <Dialog open onOpenChange={v=>{if(!v)onClose()}}><DialogContent className="activity-library"><DialogHeader><DialogTitle>HERMES 통합 기록</DialogTitle><DialogDescription>Discord, ORBIT, CLI와 기존 Slack 등 연결된 Hermes의 대화와 도구 실행을 프로젝트별로 모읍니다.</DialogDescription></DialogHeader>
 <div className="activity-status"><div><strong>{data?.status.sessions??0}개 대화 · {data?.status.messages??0}개 메시지</strong><p>{data?.status.lastSync?'최근 수집 '+new Date(data.status.lastSync).toLocaleString('ko-KR'):'아직 수집 기록이 없습니다.'}{!!data?.status.pending&&' · 다음 기록 수집 대기 '+data.status.pending+'건'}</p></div><button className="primary-button" onClick={()=>void sync()} disabled={busy}>{busy?'확인 중…':'지금 수집'}</button></div>
 <p className="activity-notice">서버 하루 운영이 켜져 있으면 앱을 닫아도 순차 수집합니다. 프로젝트 연결이 불명확한 기록은 미분류로 남깁니다.</p>
 {(error||data?.status.lastError)&&<p role="alert" className="agent-error">{error||data?.status.lastError}</p>}
 <div className="activity-filters"><input className="form-field" aria-label="통합 기록 검색" placeholder="대화와 실행 결과 검색" value={query} onChange={e=>{setQuery(e.target.value);setOffset(0)}}/><select className="form-field" aria-label="기록 출처" value={source} onChange={e=>{setSource(e.target.value);setOffset(0)}}><option value="">모든 창구</option>{data?.sources.map(s=><option value={s.source} key={s.source}>{s.source} ({s.count})</option>)}</select><select className="form-field" aria-label="기록 프로젝트" value={project} onChange={e=>{setProject(e.target.value);setOffset(0)}}><option value="">모든 프로젝트</option><option value="unassigned">미분류</option>{projects.map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select></div>
 <div className="activity-content"><div className="activity-list">{data?.items.map(r=><article key={r.id}><button className="activity-open" onClick={()=>void open(r.id)}><small>{r.source} · {categories[r.category]??r.category} · {r.message_offset}개 메시지</small><strong>{r.title}</strong><span>{projects.find(p=>p.id===r.project_id)?.name??'프로젝트 미분류'}</span><p>{r.summary.slice(0,180)}</p></button></article>)}{data&&!data.items.length&&<p>표시할 기록이 없습니다. 지금 수집을 누르거나 검색 조건을 변경해 주세요.</p>}<div className="activity-pages"><button className="secondary-button" disabled={!offset||busy} onClick={()=>setOffset(Math.max(0,offset-20))}>이전</button><button className="secondary-button" disabled={!data?.hasMore||busy} onClick={()=>setOffset(offset+20)}>다음</button></div></div>
 {detail&&<section className="activity-detail"><h3>{detail.record.title}</h3><div className="activity-filters"><label>프로젝트<select className="form-field" disabled={busy} value={detail.record.project_id??''} onChange={e=>void classify(detail.record.id,e.target.value||null,detail.record.category)}><option value="">미분류</option>{projects.map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select></label><label>분류<select className="form-field" disabled={busy} value={detail.record.category} onChange={e=>void classify(detail.record.id,detail.record.project_id,e.target.value)}>{Object.entries(categories).map(([v,l])=><option key={v} value={v}>{l}</option>)}</select></label></div><p className="activity-notice">AI 답변은 원문 기록이며, 사실 검증이나 업무 완료 판정과 구분합니다. 수동으로 정한 분류는 다음 수집에도 유지됩니다.</p>{detail.messages.map((m,i)=><div className={'activity-message '+m.role} key={m.id+':'+i}><small>{{user:'사용자',assistant:'HERMES',tool:'도구',system:'시스템',function:'도구'}[m.role]??m.role} {m.tool_name&&'· '+m.tool_name}</small><pre>{m.content}</pre>{m.tool_calls&&<details><summary>도구 호출 기록</summary><pre>{m.tool_calls}</pre></details>}</div>)}<div className="activity-pages"><button className="secondary-button" disabled={!messageOffset||busy} onClick={()=>void open(detail.record.id,Math.max(0,messageOffset-100))}>이전 원문</button><button className="secondary-button" disabled={!detail.hasMore||busy} onClick={()=>void open(detail.record.id,messageOffset+100)}>다음 원문</button></div></section>}</div>
 <p className="activity-notice">{data?.status.coverage??'인증된 Hermes 연결의 기록만 조회합니다.'}</p>
 </DialogContent></Dialog>;
}
