'use client';
import {useEffect,useRef,useState} from 'react';
import {AgentRequestError,type OverlapDetails} from '@/lib/orbit/agent/approval-feedback';
import {Orbit,ArrowUp,ArrowUpRight,Check,Clock3,Link2,LoaderCircle,Mic,Moon,RefreshCw,Sparkles,Target,X,ChevronDown} from 'lucide-react';
import {Dialog,DialogContent,DialogHeader,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {Connections,agentRequest} from './connections';
import {addDays,todayInZone,koreanDate} from '@/lib/orbit/dates';
import {formatTime,type View,type WorkspaceSnapshot} from '@/lib/orbit/model';
import type {AgentAction} from '@/lib/orbit/agent/types';
import {useAttachments} from '../attachments/provider';
import {AttachmentInput,FileCards,FileDrop} from '../attachments/files';
import type {StoredAttachment} from '@/lib/orbit/attachments/types';
import {useAgentConversations} from './use-agent-conversations';
import {ConversationLibrary,ConversationHeading} from './conversation-library';
const suggestions=[{icon:Target,title:'오늘의 우선순위',text:'오늘 일정과 프로젝트를 보고, 결과물에 가까워질 우선순위를 제안해 줘.'},{icon:Mic,title:'회의에서 다음 행동으로',text:'최근 Plaud 회의 기록을 찾아 핵심 결정, 개인 위키에 남길 내용과 후속 할 일을 제안해 줘. 프로젝트 연결이 불명확하면 먼저 물어봐 줘.'},{icon:Sparkles,title:'멈춘 프로젝트 점검',text:'진행 중인 프로젝트의 완료 조건과 막힌 일을 확인하고, 다음에 할 일을 제안해 줘.'},{icon:Moon,title:'회고하고 내일 설계',text:'오늘의 성과와 막힌 점을 함께 돌아보고, 내일 하루를 설계해 줘. 먼저 내가 답할 질문부터 해 줘.'}];
const names:Record<string,string>={title:'제목',name:'이름',goal:'결과물',due:'기한',priority:'우선순위',symbol:'표시',color:'색상',projectId:'프로젝트',status:'진행 상태',duration:'예상 소요(분)',impact:'중요도',focus:'오늘 집중',definition:'완료 조건',blocker:'막힌 점',checkDate:'확인일',planHoldUntil:'보류 기한',dependsOn:'선행 업무',completedOn:'완료일',kind:'종류',summary:'요약',body:'본문',tags:'태그',updated:'기록 날짜',date:'날짜',start:'시작',end:'종료',timeZone:'시간대',description:'설명',win:'성과',block:'장애물',energy:'에너지',itemId:'계획 항목',reason:'이유',revisitDate:'다시 검토할 날짜',workStart:'업무 시작',workEnd:'업무 종료',breakStart:'휴식 시작',breakEnd:'휴식 종료',workDays:'업무 요일',focusLimit:'핵심 결과물 개수',breakMinutes:'휴식 간격(분)',bufferFraction:'여유 시간 비율',focusDate:'집중 날짜',noteId:'연결 문서',revision:'문서 버전',line:'원문 행',quote:'근거',result:'결과',planHoldReason:'보류 이유',planHoldProposalId:'보류한 계획',dailyBudget:'집중 예산',taskId:'할 일'};
const values:Record<string,string>={todo:'할 일',doing:'진행 중',waiting:'대기',done:'완료',meeting:'회의',wiki:'위키',knowledge:'지식',normal:'보통',low:'낮음',high:'높음'};
function ActionPreview({item,snapshot}:{item:AgentAction;snapshot:WorkspaceSnapshot}){
 const entries=(record:Record<string,unknown>):[string,unknown][]=>Object.entries(record).flatMap(([key,value]):[string,unknown][]=>['type','id','expectedNoteRevision'].includes(key)?[]:value&&typeof value==='object'&&!Array.isArray(value)?entries(value as Record<string,unknown>):[[key,value]]);
 const rows=entries(item.action as unknown as Record<string,unknown>);const targetId='id' in item.action?item.action.id:undefined;const target=snapshot.data.tasks.find(t=>t.id===targetId)?.title;if(target)rows.unshift(['taskId',target]);
 return <details className="agent-change"><summary>반영할 내용 확인 <ChevronDown size={14}/></summary><dl>{rows.map(([key,value],i)=>{let text=typeof value==='boolean'?(value?'예':'아니요'):Array.isArray(value)?value.map(v=>snapshot.data.tasks.find(t=>t.id===v)?.title??v).join(', '):String(value??'없음');if(['start','end','workStart','workEnd','breakStart','breakEnd'].includes(key)&&typeof value==='number')text=formatTime(value);if(key==='projectId')text=snapshot.data.projects.find(p=>p.id===value)?.name??'새 프로젝트 · 선행 제안 승인 필요';if(key==='itemId')text=snapshot.data.tasks.find(t=>t.id===snapshot.data.proposals.flatMap(p=>p.items).find(i=>i.id===value)?.taskId)?.title??text;if(key==='taskId')text=snapshot.data.tasks.find(t=>t.id===value)?.title??text;return <div key={key+i} className={key==='body'?'agent-change-body':''}><dt>{names[key]??key}</dt><dd>{values[text]??text}</dd></div>})}</dl></details>;
}
export function AgentWorkspace({demo,displayName,snapshot,onWorkspaceChange,navigate}:{demo:boolean;displayName:string;snapshot:WorkspaceSnapshot;onWorkspaceChange:()=>void;navigate:(view:View)=>void}){
 const chat=useAgentConversations(demo),{state,loaded,draft,setDraft,sending,error,setError,older,load}=chat;
 const attachmentScope='chat:'+(chat.selected??'new'),uploads=useAttachments(attachmentScope);
 const [feedback,setFeedback]=useState(''),[settings,setSettings]=useState(false),[acting,setActing]=useState<string|null>(null),[deferred,setDeferred]=useState<AgentAction|null>(null),[reason,setReason]=useState(''),[revisit,setRevisit]=useState(addDays(todayInZone(snapshot.data.preferences.timeZone),1)),[queue,setQueue]=useState(false);
 const [actionNotices,setActionNotices]=useState<Record<string,{message:string;success?:boolean;overlap?:OverlapDetails}>>({});
 const decisionLock=useRef(false);
 const input=useRef<HTMLTextAreaElement>(null),end=useRef<HTMLDivElement>(null),running=!!state.activeRun;
 useEffect(()=>{const url=new URL(location.href),changed=url.searchParams.has('connected')||url.searchParams.has('connection_error');if(url.searchParams.has('connected')){setFeedback('계정 연결을 저장했습니다. 필요한 기록을 대화에서 요청해 보세요.');if(url.searchParams.get('connected')==='google_calendar')void agentRequest('/api/integrations/sync','POST',{}).then(()=>onWorkspaceChange()).catch(e=>setError(e.message));url.searchParams.delete('connected')}else if(url.searchParams.has('connection_error')){setError('계정 연결을 마치지 못했습니다. 연결 설정에서 다시 시도해 주세요.');setSettings(true);url.searchParams.delete('connection_error')}if(changed)history.replaceState(null,'',url.pathname+url.search+'#agent')},[]);
 const refresh=async()=>{await chat.refresh();onWorkspaceChange()};
 async function send(text=draft,id=crypto.randomUUID(),retryFiles?:StoredAttachment[]){
  if(!ready){setSettings(true);return}if(uploads.busy&&!retryFiles)return;const files=retryFiles??uploads.ready;const message=text.trim()||(files.length?'첨부한 자료를 함께 확인해 줘.':'');if(!message)return;setFeedback('');setQueue(false);
  let target=chat.selected;if(!target){const created=await chat.create();if(!created)return;target=created.id;if(!uploads.transfer(attachmentScope,'chat:'+target))return}
  const ok=await chat.send(message,id,files,target);if(ok){uploads.clearAt('chat:'+target,files.map(f=>f.id));await uploads.completeShare('chat:'+target,files.map(f=>f.id));}onWorkspaceChange();
 }
 const opened=()=>{setQueue(false);setFeedback('')};
 async function decision(item:AgentAction,decision:'approve'|'defer'|'reconsider'|'reject',overlapConfirmation?:string){
  if(decisionLock.current||acting)return;decisionLock.current=true;setActing(item.id);setError('');
  setActionNotices(previous=>({...previous,[item.id]:{message:'처리 중입니다…'}}));
  try{
   await agentRequest('/api/agent','PATCH',{id:item.id,decision,...(overlapConfirmation?{overlapConfirmation}:{}),...(decision==='defer'?{reason,revisitDate:revisit}:{})});
   setDeferred(null);
   const message=decision==='approve'?'승인한 내용을 반영했습니다.':decision==='defer'?'검토할 날짜와 보류 이유를 저장했습니다.':decision==='reject'?'제안을 닫았습니다.':'다시 검토할 수 있습니다.';
   setActionNotices(previous=>({...previous,[item.id]:{message,success:true}}));setFeedback(message);
   try{await refresh()}catch{setActionNotices(previous=>({...previous,[item.id]:{message:message+' 목록을 새로 불러오지 못했습니다. 대화 새로 불러오기를 누르면 결과를 확인할 수 있습니다.',success:true}}))}
  }catch(e){
   const message=e instanceof Error?e.message:'변경을 완료하지 못했습니다.';
   setActionNotices(previous=>({...previous,[item.id]:{message,overlap:e instanceof AgentRequestError&&e.code==='CALENDAR_OVERLAP'?e.details:undefined}}));
   await load().catch(()=>{});
  }finally{decisionLock.current=false;setActing(null)}
 }
 const actionNotice=(item:AgentAction)=>{
  const notice=actionNotices[item.id];if(!notice)return null;
  return <div role={notice.success||acting===item.id?'status':'alert'} className={notice.success?'agent-feedback':'agent-error'}>
   <p>{notice.message}</p>
   {notice.overlap&&item.state!=='approved'&&<>
    <ul className="agent-overlap-list">{notice.overlap.conflicts.map((event,index)=><li key={index}><strong>{event.title}</strong><span>{event.date} · {formatTime(event.start)}–{formatTime(event.end)}</span></li>)}</ul>
    {notice.overlap.total>notice.overlap.conflicts.length&&<p>외 {notice.overlap.total-notice.overlap.conflicts.length}개 일정이 더 겹칩니다.</p>}
    <div className="agent-overlap-options"><button className="primary-button" disabled={!!acting} onClick={()=>void decision(item,'approve',notice.overlap!.overlapConfirmation)}>겹침을 확인하고 등록</button><button className="secondary-button" disabled={!!acting} onClick={()=>{setDraft('“'+item.title+'” 제안을 기존 일정과 겹치지 않는 시간으로 다시 제안해 줘.');setQueue(false);input.current?.focus()}}>다른 시간 요청하기</button></div>
   </>}
  </div>;
 };

 const ready=state.connections.find(c=>c.provider==='hermes')?.connected,pending=state.pendingActions??[];
 const renderAction=(item:AgentAction)=><article key={item.id} className={'agent-action '+item.state}><div className="agent-action-top"><span>{item.action.type==='google.event.create'?'GOOGLE 일정':item.action.type.startsWith('note.')?'기록 제안':item.action.type.startsWith('proposal.')||item.action.type.startsWith('review.')?'하루 설계':'업무 제안'}</span><small>{({pending:'승인 대기',applying:'적용 중',approved:'반영 완료',deferred:'보류',rejected:'닫힘'})[item.state]}</small></div>{queue&&item.conversationId&&<button className="text-button" onClick={()=>{chat.select(item.conversationId!);opened()}}>원래 대화 열기 <ArrowUpRight size={14}/></button>}<h3>{item.title}</h3><p>{item.reason}</p><ActionPreview item={item} snapshot={snapshot}/>{actionNotice(item)}{item.note&&<p className="agent-defer-note">{item.revisitDate} 다시 검토 · {item.note}</p>}{item.state==='approved'&&item.result?.briefDate&&<button className="text-button" onClick={()=>navigate('proposal')}>원페이지 제안 확인 <ArrowUpRight size={14}/></button>}{item.state==='approved'&&item.result?.url&&/^https:\/\/(calendar\.google\.com|www\.google\.com)\//.test(item.result.url)&&<a className="text-button" href={item.result.url} target="_blank" rel="noreferrer">Google에서 일정 보기 <ArrowUpRight size={14}/></a>}{['pending','applying'].includes(item.state)&&<div className="agent-action-buttons"><button className="primary-button" disabled={!!acting} onClick={()=>void decision(item,'approve')}>{acting===item.id?<LoaderCircle size={15} className="animate-spin"/>:<Check size={15}/>} {item.state==='applying'?'결과 확인 / 재시도':'승인하고 반영'}</button><button className="secondary-button" disabled={!!acting||item.state==='applying'} onClick={()=>{setDeferred(item);setReason('');setRevisit(addDays(todayInZone(snapshot.data.preferences.timeZone),1))}}><Clock3 size={15}/> 보류</button><button className="icon-button" aria-label={item.title+' 제안 닫기'} disabled={!!acting||item.state==='applying'} onClick={()=>void decision(item,'reject')}><X size={16}/></button></div>}{item.state==='deferred'&&<button className="text-button" disabled={!!acting} onClick={()=>void decision(item,'reconsider')}>다시 검토하기 <ArrowUpRight size={14}/></button>}</article>;
 return <FileDrop className="agent-layout" onFiles={uploads.add} disabled={demo||chat.creating}><ConversationLibrary chat={chat} projects={snapshot.data.projects} demo={demo} onOpen={opened}/><section className="agent-workspace" aria-label="Orbit AI 에이전트"><header className="agent-toolbar"><div className="agent-identity"><span><Orbit size={20}/></span><div><strong>Orbit</strong><small>Hermes · 나의 실행 파트너</small></div></div><div className="agent-tools"><button className={'secondary-button '+(queue?'selected':'')} onClick={()=>setQueue(v=>!v)} aria-pressed={queue}><Check size={15}/><span>검토함</span>{pending.length>0&&<b>{pending.length}</b>}</button><button className="secondary-button" onClick={()=>setSettings(true)} disabled={demo}><Link2 size={15}/><span>연결</span><i className={ready?'ready':''}/></button></div></header><ConversationHeading chat={chat} projects={snapshot.data.projects} onOpen={opened}/>
 {error&&<div role="alert" className="agent-error">{error}<button onClick={()=>void refresh().catch(e=>setError(e.message))}>다시 불러오기</button></div>}{feedback&&<div role="status" className="agent-feedback">{feedback}</div>}
 {!loaded?<div className="agent-loading"><LoaderCircle size={22} className="animate-spin"/>대화를 불러오는 중</div>:queue?<div className="agent-queue"><h2>내가 결정하는 다음 단계</h2><p>반영할 내용을 확인하고 승인하거나, 이유와 검토일을 남겨 보류하세요.</p>{pending.length?pending.map(renderAction):<div className="agent-empty-queue"><Check size={24}/><p>검토를 기다리는 제안이 없습니다.</p><button className="text-button" onClick={()=>setQueue(false)}>대화로 돌아가기</button></div>}</div>:<>
  {!state.turns.length&&<div className="agent-welcome"><div className="agent-orbit"><Orbit size={42}/></div><span className="agent-eyebrow">{koreanDate(todayInZone(snapshot.data.preferences.timeZone))} · YOUR PERSONAL ORBIT</span><h1>{displayName.split(' ')[0]}님,<br/>무엇부터 함께 정리할까요?</h1><p>생각은 대화로, 계획은 실행으로.<br/>내 기록과 일정을 연결해 다음 행동을 찾습니다.</p><div className="agent-suggestions">{suggestions.map(s=><button key={s.title} onClick={()=>{setDraft(s.text);input.current?.focus()}}><s.icon size={18}/><span>{s.title}</span><ArrowUpRight size={15}/></button>)}</div>{demo?<p className="agent-setup-note">체험 화면입니다. 실제 AI 대화는 내 워크스페이스에서 연결 후 시작할 수 있습니다.</p>:!ready&&<div className="agent-setup"><span>헤르메스를 연결하면 여기서 대화를 시작할 수 있어요.</span><button onClick={()=>setSettings(true)}>헤르메스 연결하기 <ArrowUpRight size={15}/></button></div>}</div>}
  {!!state.turns.length&&<div className="agent-thread" role="log" aria-label="저장된 대화"><div className="agent-thread-head"><span>내 기록을 바탕으로, 다음 행동까지</span><button aria-label="대화 새로 불러오기" className="icon-button" onClick={()=>void refresh().catch(e=>setError(e.message))}><RefreshCw size={15}/></button></div>{state.hasMore&&<button className="text-button agent-older" disabled={older} onClick={()=>void chat.loadOlder()}>이전 대화 불러오기</button>}{state.turns.map(turn=><div className="agent-turn" key={turn.id}><div className="agent-user-message"><span>나</span><p>{turn.input}</p>{!!turn.attachments?.length&&<FileCards files={turn.attachments}/>}</div><div className="agent-assistant-message"><span className="agent-message-mark"><Orbit size={18}/></span><div className="agent-message-body"><strong>Orbit</strong>{turn.status==='running'?<><p className="agent-thinking"><LoaderCircle size={16} className="animate-spin"/>{turn.progress??'헤르메스가 기록을 확인하고 다음 단계를 정리하고 있어요.'}</p><button className="text-button" disabled={acting===turn.id} onClick={async()=>{setActing(turn.id);try{await agentRequest('/api/agent/run','POST',{id:turn.id,action:'cancel'});setFeedback('중지를 요청했습니다. 헤르메스의 종료 상태를 확인합니다.');await load()}catch(e){setError(e instanceof Error?e.message:'중지 상태를 확인하지 못했습니다.')}finally{setActing(null)}}}>요청 중지</button></>:turn.status==='failed'?<><p className="agent-error">{turn.error}</p><button className="text-button" disabled={sending||running} onClick={()=>void send(turn.input,turn.id,turn.attachments)}>이 메시지 다시 시도</button></>:<><p className="agent-answer">{turn.text}</p>{turn.sources.length>0&&<div className="agent-sources" aria-label="참고한 기록">{turn.sources.map((s,i)=><span key={i}>{s.title} · {s.label}</span>)}</div>}{state.actions.filter(a=>a.turnId===turn.id).map(renderAction)}</>}</div></div></div>)}</div>}
 </>}
 <div ref={end}/><form className="agent-composer" onSubmit={event=>{event.preventDefault();void send()}}><AttachmentInput scope={attachmentScope} disabled={demo||chat.creating||sending} compact/><label className="sr-only" htmlFor="orbit-message">Orbit에게 메시지 보내기</label><textarea ref={input} id="orbit-message" disabled={chat.creating} rows={2} maxLength={8000} value={draft} onPaste={e=>{const files=[...e.clipboardData.files];if(files.length){e.preventDefault();uploads.add(files)}}} onChange={e=>setDraft(e.target.value)} onKeyDown={e=>{if(e.key==='Enter'&&(e.metaKey||e.ctrlKey)){e.preventDefault();void send()}}} placeholder="하고 싶은 일, 막힌 일, 오늘의 생각을 이야기하세요."/><div className="agent-composer-bottom"><span>{demo?'체험 화면':sending||running?'응답을 준비하고 있습니다':ready?'변경사항은 승인한 뒤 반영됩니다':'연결 설정에서 헤르메스를 준비해 주세요'}</span><button type="submit" aria-label="메시지 보내기" disabled={demo||!loaded||chat.creating||sending||running||uploads.busy||(!draft.trim()&&!uploads.ready.length)}>{sending||running?<LoaderCircle size={19} className="animate-spin"/>:<ArrowUp size={20}/>}</button></div></form>
 <footer className="agent-footer">{!demo&&<><a href="/install">앱 설치</a><span>·</span></>}<button onClick={()=>navigate('today')}>오늘 한눈에 보기</button><span>·</span><button onClick={()=>navigate('wiki')}>개인 위키</button>{state.connections.find(c=>c.provider==='google_calendar')?.connected&&<><span>·</span><button disabled={!!acting} onClick={async()=>{setActing('sync');setError('');try{const data=await agentRequest('/api/integrations/sync','POST',{});await refresh();setFeedback(`Google 일정 ${data.count}개를 확인했습니다.`)}catch(e){setError(e instanceof Error?e.message:'일정 동기화에 실패했습니다.')}finally{setActing(null)}}}>Google 일정 동기화</button></>}</footer>
 {settings&&<Connections connections={state.connections} onClose={()=>setSettings(false)} onChange={refresh}/>}
 {deferred&&<Dialog open onOpenChange={open=>{if(!open)setDeferred(null)}}><DialogContent><DialogHeader><DialogTitle>지금은 보류하기</DialogTitle><DialogDescription>{deferred.title}</DialogDescription></DialogHeader><form className="dialog-form agent-defer-form" onSubmit={e=>{e.preventDefault();void decision(deferred,'defer')}}><label>보류하는 이유<textarea className="form-field" value={reason} onChange={e=>setReason(e.target.value)} required maxLength={2000} placeholder="선행 자료가 도착한 뒤 진행하기"/></label><label>다시 검토할 날짜<input className="form-field" type="date" min={addDays(todayInZone(snapshot.data.preferences.timeZone),1)} value={revisit} onChange={e=>setRevisit(e.target.value)} required/></label>{actionNotice(deferred)}<button className="primary-button" disabled={!!acting||!reason.trim()}>이유를 남기고 보류</button></form></DialogContent></Dialog>}
 </section></FileDrop>;
}
