'use client';
import {useState} from 'react';
import {Folder,LoaderCircle,MessageSquare,Plus,Pencil,MessagesSquare} from 'lucide-react';
import {Dialog,DialogContent,DialogHeader,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {Sheet,SheetContent,SheetHeader,SheetTitle,SheetDescription} from '@/components/ui/sheet';
import {Select,SelectContent,SelectItem,SelectTrigger,SelectValue} from '@/components/ui/select';
import type {WorkspaceSnapshot} from '@/lib/orbit/model';
import type {useAgentConversations} from './use-agent-conversations';
type Chat=ReturnType<typeof useAgentConversations>;
export function ConversationLibrary({chat,projects,demo,onOpen}:{chat:Chat;projects:WorkspaceSnapshot['data']['projects'];demo:boolean;onOpen:()=>void}){
 const [mobile,setMobile]=useState(false);
 const choose=(id:string)=>{chat.select(id);setMobile(false);onOpen()};
 const create=async()=>{const c=await chat.create();if(c){setMobile(false);onOpen()}};
 const library=<div className="conversation-library"><div className="conversation-library-title"><MessagesSquare size={17}/><strong>대화 보관함</strong></div><button className="primary-button conversation-new" disabled={demo||chat.creating} onClick={()=>void create()}>{chat.creating?<LoaderCircle className="animate-spin" size={16}/>:<Plus size={16}/>} 새 대화</button><label className="conversation-filter-label">프로젝트로 모아보기</label><Select value={chat.filter} onValueChange={value=>{onOpen();void chat.changeFilter(value)}}><SelectTrigger aria-label="대화의 프로젝트 필터" className="conversation-filter"><SelectValue/></SelectTrigger><SelectContent><SelectItem value="all">모든 대화</SelectItem><SelectItem value="general">일반 대화</SelectItem>{projects.map(p=><SelectItem key={p.id} value={'project:'+p.id}>{p.name}</SelectItem>)}</SelectContent></Select><nav className="conversation-list" aria-label="저장된 대화 목록" aria-busy={chat.listLoading}>{chat.list.items.map(c=><button key={c.id} className={'conversation-item '+(chat.selected===c.id?'selected':'')} aria-current={chat.selected===c.id?'page':undefined} onClick={()=>choose(c.id)}><MessageSquare size={15}/><span><strong>{c.title}</strong><small>{projects.find(p=>p.id===c.projectId)?.name??'일반 대화'} · {new Date(c.updatedAt).toLocaleDateString('ko-KR',{month:'short',day:'numeric'})}</small></span>{chat.state.activeRuns?.some(r=>r.conversationId===c.id)&&<LoaderCircle size={13} className="animate-spin" aria-label="응답 중"/>}</button>)}{!chat.list.items.length&&!chat.listLoading&&<p className="conversation-empty">{demo?'내 워크스페이스에서 대화를 시작하세요.':'아직 보관된 대화가 없어요. 새 대화로 첫 이야기를 시작하세요.'}</p>}{chat.listLoading&&<p className="conversation-list-status" role="status"><LoaderCircle size={14} className="animate-spin"/> 목록을 불러오는 중</p>}{chat.list.hasMore&&<button className="text-button conversation-more" disabled={chat.listLoading} onClick={()=>void chat.loadList(true).catch(()=>{})}>대화 더 보기</button>}</nav><p className="conversation-library-note"><Folder size={14}/> 대화는 자동으로 저장됩니다.<br/>제목 옆에서 프로젝트를 지정하세요.</p></div>;
 return <><aside className="conversation-desktop">{library}</aside><div className="conversation-mobile-bar"><button className="secondary-button" onClick={()=>setMobile(true)}><MessagesSquare size={16}/> 대화 목록</button><button className="secondary-button" disabled={demo||chat.creating} onClick={()=>void create()}><Plus size={16}/> 새 대화</button></div><Sheet open={mobile} onOpenChange={setMobile}><SheetContent side="left" className="conversation-sheet"><SheetHeader><SheetTitle>내 대화</SheetTitle><SheetDescription>주제와 프로젝트별로 이어가세요.</SheetDescription></SheetHeader>{library}</SheetContent></Sheet></>;
}
export function ConversationHeading({chat,projects,onOpen}:{chat:Chat;projects:WorkspaceSnapshot['data']['projects'];onOpen:()=>void}){
 const [edit,setEdit]=useState(false),[title,setTitle]=useState(''),[projectId,setProjectId]=useState('general'),[saving,setSaving]=useState(false),[saveError,setSaveError]=useState('');const c=chat.state.conversation;
 const project=projects.find(p=>p.id===(c?c.projectId:(chat.filter.startsWith('project:')?chat.filter.slice(8):null)));
 return <><div className="conversation-heading"><div><span><Folder size={13}/>{project?.name??'일반 대화'}</span><h1>{c?.title??(chat.loaded?'새 대화':'대화를 불러오는 중')}</h1></div>{c&&<button className="icon-button" aria-label="대화 제목과 프로젝트 정리" disabled={chat.state.activeRuns?.some(r=>r.conversationId===c.id)} onClick={()=>{setTitle(c.title);setProjectId(c.projectId?'project:'+c.projectId:'general');setSaveError('');setEdit(true)}}><Pencil size={16}/></button>}</div>{(chat.state.activeRuns??[]).filter(r=>r.conversationId!==chat.selected).length>0&&<div className="conversation-running" role="status"><LoaderCircle size={15} className="animate-spin"/><span>다른 대화 {(chat.state.activeRuns??[]).filter(r=>r.conversationId!==chat.selected).length}개가 진행 중입니다. 여기서도 바로 요청할 수 있어요.</span><button onClick={()=>{const run=chat.state.activeRuns?.find(r=>r.conversationId!==chat.selected);if(run){chat.select(run.conversationId);onOpen()}}}>진행 중 대화 보기</button></div>}{edit&&c&&<Dialog open onOpenChange={open=>{if(!saving)setEdit(open)}}><DialogContent><DialogHeader><DialogTitle>대화 정리</DialogTitle><DialogDescription>주제를 알아보기 쉽게 이름을 붙이고 프로젝트에 보관하세요.</DialogDescription></DialogHeader><form className="dialog-form" onSubmit={async e=>{e.preventDefault();setSaving(true);setSaveError('');try{await chat.save({title:title.trim(),projectId:projectId==='general'?null:projectId.slice(8)});setEdit(false)}catch(e){setSaveError(e instanceof Error?e.message:'저장하지 못했습니다.')}finally{setSaving(false)}}}><label>대화 제목<input className="form-field" value={title} onChange={e=>setTitle(e.target.value)} required maxLength={100} autoFocus/></label><label>보관할 프로젝트</label><Select value={projectId} onValueChange={setProjectId}><SelectTrigger aria-label="대화를 보관할 프로젝트" className="conversation-filter"><SelectValue/></SelectTrigger><SelectContent><SelectItem value="general">일반 대화 · 프로젝트 없음</SelectItem>{projects.map(p=><SelectItem key={p.id} value={'project:'+p.id}>{p.name}</SelectItem>)}</SelectContent></Select>{saveError&&<p role="alert" className="agent-error">{saveError}</p>}<button className="primary-button" disabled={saving||!title.trim()}>{saving?'저장 중…':'저장하기'}</button></form></DialogContent></Dialog>}</>;
}
