'use client';
import {useCallback,useEffect,useRef,useState} from 'react';
import {ArrowUpRight,Check,GitBranch,LoaderCircle,Plus,RefreshCw,Send,Square,X} from 'lucide-react';
import {Dialog,DialogContent,DialogHeader,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import type {WorkspaceData} from '@/lib/orbit/model';
import {orderActive,orderStatusLabel,type DispatchAction,type WorkOrder} from '@/lib/orbit/agent/orders-schema';
import {agentRequest} from './connections';

export function useWorkOrders(demo:boolean){
 const [orders,setOrders]=useState<WorkOrder[]>([]),[error,setError]=useState(''),[busy,setBusy]=useState<string|null>(null);
 const current=useRef(orders),polling=useRef(false),controlLock=useRef(false);current.current=orders;
 const refresh=useCallback(async()=>{if(demo)return;const result=await agentRequest('/api/agent/orders');setOrders(result.orders);},[demo]);
 useEffect(()=>{if(demo)return;let gone=false;const load=()=>void refresh().catch(e=>{if(!gone)setError(e.message)});load();const resume=()=>{if(document.visibilityState==='visible')load()};document.addEventListener('visibilitychange',resume);return()=>{gone=true;document.removeEventListener('visibilitychange',resume)}},[demo,refresh]);
 const active=orders.filter(o=>orderActive(o.status)).map(o=>o.id).sort().join('|');
 useEffect(()=>{if(!active||demo)return;let gone=false;const poll=async()=>{if(polling.current||document.visibilityState!=='visible')return;polling.current=true;try{const todo=current.current.filter(o=>orderActive(o.status));let i=0;const worker=async()=>{while(i<todo.length&&!gone){const o=todo[i++];await agentRequest('/api/agent/orders','POST',{action:'poll',id:o.id});}};await Promise.all([worker(),worker(),worker()]);if(!gone)await refresh();}catch(e){if(!gone)setError(e instanceof Error?e.message:'실행 상태를 불러오지 못했습니다.')}finally{polling.current=false}};void poll();const timer=setInterval(()=>void poll(),6000);return()=>{gone=true;clearInterval(timer)}},[active,demo,refresh]);
 const command=async(input:Record<string,unknown>)=>{if(demo||controlLock.current)return null;controlLock.current=true;setBusy(String(input.id));setError('');try{const result=await agentRequest('/api/agent/orders','POST',input);setOrders(old=>[result.order,...old.filter(o=>o.id!==result.order.id)]);return result.order as WorkOrder;}catch(e){setError(e instanceof Error?e.message:'지시를 완료하지 못했습니다.');return null;}finally{controlLock.current=false;setBusy(null);void refresh().catch(()=>{});}};
 return {orders,error,setError,busy,refresh,command};
}
type Room=ReturnType<typeof useWorkOrders>;
interface Capabilities {supported:boolean;delegation:boolean;tools:string[];steer:boolean;approval:boolean;discoveryError:string}
export function OrderRoom({room,data,demo,conversationId,initialText,onClose,onAsk,onComplete}:{room:Room;data:WorkspaceData;demo:boolean;conversationId:string|null;initialText:string;onClose:()=>void;onAsk:(id:string)=>void;onComplete:(id:string)=>Promise<boolean>}){
 const [creating,setCreating]=useState(!!initialText),[instruction,setInstruction]=useState(initialText),[projectId,setProjectId]=useState(''),[taskIds,setTaskIds]=useState<string[]>([]),[caps,setCaps]=useState<Capabilities|null>(null),[capsError,setCapsError]=useState(''),[inspect,setInspect]=useState<string|null>(null),[steer,setSteer]=useState('');
 const receipt=useRef<{id:string;fingerprint:string}|null>(null);
 const capability=useCallback(async()=>{if(demo)return;setCapsError('');try{setCaps(await agentRequest('/api/agent/orders?capabilities=1'))}catch(e){setCapsError(e instanceof Error?e.message:'Hermes 연결을 확인해 주세요.')}},[demo]);
 useEffect(()=>{void capability()},[capability]);
 const activeCount=room.orders.filter(o=>orderActive(o.status)).length;
 async function submit(){
  const order:DispatchAction={type:'agent.dispatch',title:instruction.trim().split('\n')[0].slice(0,100),instruction:instruction.trim(),projectId:projectId||null,taskIds};
  const fingerprint=JSON.stringify({order,conversationId});
  if(!receipt.current||receipt.current.fingerprint!==fingerprint)receipt.current={id:crypto.randomUUID(),fingerprint};
  const result=await room.command({action:'dispatch',id:receipt.current.id,order,...(conversationId?{conversationId}:{})});
  if(result){receipt.current=null;setInstruction('');setTaskIds([]);setCreating(false);setInspect(result.id);}
 }
 return <Dialog open onOpenChange={open=>{if(!open)onClose()}}><DialogContent className="order-room"><DialogHeader><DialogTitle><GitBranch size={21}/> Orbit 실행실</DialogTitle><DialogDescription>지시를 실제 실행으로. 여러 업무를 동시에 맡기고, 진행과 결과를 확인하세요.</DialogDescription></DialogHeader>
 <div className="order-room-toolbar"><div><strong>Hermes 실행팀</strong><span>{activeCount}개 실행 중 · {room.orders.length}개 지시</span></div><button className="secondary-button" onClick={()=>{void room.refresh().catch(e=>room.setError(e.message));void capability()}} disabled={!!room.busy}><RefreshCw size={15}/>상태 확인</button><button className="primary-button" disabled={demo} onClick={()=>setCreating(v=>!v)}><Plus size={15}/>새 업무 지시</button></div>
 <details className="order-capabilities"><summary>{caps?caps.supported?caps.delegation?'실행·병렬 위임 사용 가능':'업무 실행 사용 가능 · 위임 도구 확인 필요':'Hermes 실행 기능 업데이트 필요':capsError||'연결된 실행 권한 확인 중'}</summary><p>연결된 Hermes가 가진 도구와 권한으로 실행합니다. 특정 에이전트는 실제 등록과 연결을 확인한 뒤 지시합니다.</p>{capsError&&<p role="alert">{capsError}</p>}{caps&&<><p>{caps.tools.length?'확인한 도구: '+caps.tools.join(', '):'사용 가능한 도구 목록을 확인하지 못했습니다.'}</p>{caps.discoveryError&&<p>{caps.discoveryError}</p>}<p>추가 지시 {caps.steer?'가능':'미지원'} · 실행 승인 응답 {caps.approval?'가능':'미지원'}</p></>}</details>
 {room.error&&<div role="alert" className="agent-error">{room.error}</div>}
 {creating&&<form className="order-create" onSubmit={e=>{e.preventDefault();void submit()}}><label>어떤 결과를 만들어야 하나요?<textarea className="form-field" required maxLength={8000} rows={5} value={instruction} disabled={!!room.busy} onChange={e=>setInstruction(e.target.value)} placeholder="개발팀에 Google Calendar 개선을 맡겨 줘. 기존 코드를 확인하고 구현·테스트한 뒤 변경사항과 결과를 보고해 줘."/></label><label>연결할 프로젝트<select className="form-field" value={projectId} disabled={!!room.busy} onChange={e=>{setProjectId(e.target.value);setTaskIds([])}}><option value="">일반 업무</option>{data.projects.map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select></label>{projectId&&<fieldset><legend>함께 전달할 할 일 · 최대 12개</legend><div className="order-task-pick">{data.tasks.filter(t=>t.projectId===projectId&&t.status!=='done').map(t=><label key={t.id}><input type="checkbox" checked={taskIds.includes(t.id)} disabled={!!room.busy||taskIds.length>=12&&!taskIds.includes(t.id)} onChange={e=>setTaskIds(ids=>e.target.checked?[...ids,t.id]:ids.filter(id=>id!==t.id))}/>{t.title}</label>)}</div></fieldset>}<p>보내면 별도 검토 카드 없이 실행을 시작합니다. 실행할 내용과 필요한 전달·게시 범위를 지시문에 적어 주세요.</p><div className="order-actions"><button type="submit" className="primary-button" disabled={demo||!!room.busy||!instruction.trim()||caps?.supported===false}>{room.busy?<LoaderCircle size={16} className="animate-spin"/>:<Send size={16}/>}지시하고 실행</button><button type="button" className="secondary-button" onClick={()=>setCreating(false)}>닫기</button></div></form>}
 <div className="order-list">{!room.orders.length&&!creating?<div className="agent-empty-queue"><GitBranch size={28}/><h3>Orbit이 직접 움직일 차례입니다</h3><p>개발, 조사, 자료 정리처럼 결과가 필요한 업무를 지시하세요.</p><button className="primary-button" onClick={()=>setCreating(true)} disabled={demo}>첫 업무 지시하기</button></div>:room.orders.map(o=><article key={o.id} className="order-card"><header><div><span className={'order-status '+o.status}>{orderStatusLabel[o.status]}</span><h3>{o.title}</h3><small>{data.projects.find(p=>p.id===o.projectId)?.name??'일반 업무'} · {new Date(o.createdAt).toLocaleString('ko-KR')}</small></div>{orderActive(o.status)&&<button className="secondary-button" disabled={!!room.busy} onClick={()=>void room.command({action:'stop',id:o.id})}><Square size={14}/>중지</button>}</header>{o.status==='unknown'&&o.runId&&<button className="secondary-button" disabled={!!room.busy} onClick={()=>void room.command({action:'poll',id:o.id})}>실행 상태 다시 확인</button>}{o.error&&<p className="agent-error" role="alert">{o.error}</p>}
 {!!o.taskIds.length&&<div className="order-linked-tasks">{o.taskIds.map(id=>{const t=data.tasks.find(t=>t.id===id);return <div key={id}><span>{t?.title??'삭제된 할 일'}</span>{t&&o.status==='completed'&&t.status!=='done'?<button className="text-button" onClick={()=>void onComplete(id)} disabled={!!room.busy}><Check size={14}/>결과 확인 후 완료</button>:t?.status==='done'?<small>완료</small>:<small>실행 결과 대기</small>}</div>})}</div>}
 {o.approval&&<div className="order-approval"><strong>Hermes가 다음 작업의 승인을 요청했습니다</strong><pre>{o.approval.description}</pre>{o.controls.approval?<div className="order-actions"><button className="primary-button" disabled={!!room.busy} onClick={()=>void room.command({action:'approval',id:o.id,requestId:o.approval!.id,choice:'once'})}><Check size={15}/>이번 작업만 승인</button><button className="secondary-button" disabled={!!room.busy} onClick={()=>void room.command({action:'approval',id:o.id,requestId:o.approval!.id,choice:'deny'})}><X size={15}/>거절</button></div>:<p>Hermes에서 실행 승인을 확인해 주세요.</p>}</div>}
 <button className="text-button" onClick={()=>{setInspect(inspect===o.id?null:o.id);setSteer('')}}>{inspect===o.id?'상세 닫기':'지시·진행·결과 보기'}<ArrowUpRight size={14}/></button>
 {inspect===o.id&&<div className="order-detail"><h4>전달한 지시</h4><p>{o.instruction}</p>{o.output&&<><h4>실행 결과</h4><p className="order-output">{o.output}</p><button className="secondary-button" onClick={()=>onAsk(o.id)}>Orbit과 결과 검토하기 <ArrowUpRight size={15}/></button></>}{o.status==='running'&&o.controls.steer&&<form onSubmit={async e=>{e.preventDefault();if(await room.command({action:'steer',id:o.id,input:steer}))setSteer('')}}><label>실행 중 추가 지시<textarea className="form-field" required rows={2} maxLength={4000} value={steer} onChange={e=>setSteer(e.target.value)}/></label><button className="secondary-button" disabled={!!room.busy||!steer.trim()}>추가 지시 전달</button></form>}<h4>실행 기록</h4><ol>{o.activity.map((a,i)=><li key={i}><time>{new Date(a.at).toLocaleTimeString('ko-KR')}</time>{a.text}</li>)}</ol>{o.runId&&<small>Hermes 실행 번호 · {o.runId}</small>}</div>}</article>)}</div>
 <p className="order-room-note">Hermes가 켜져 있으면 접수된 실행은 앱을 닫아도 계속됩니다. 진행과 결과는 Orbit을 열었을 때 갱신됩니다. 중지는 이미 수행한 작업을 되돌리지 않습니다.</p>
 </DialogContent></Dialog>;
}
