'use client';
import {useEffect,useState} from 'react';
import {agentRequest} from './connections';
import type {WorkOrder} from '@/lib/orbit/agent/orders-schema';
import type {Task} from '@/lib/orbit/model';
export function OrderReview({order,tasks,onComplete}:{order:WorkOrder;tasks:Task[];onComplete:(id:string)=>Promise<boolean>}){
 const [receipt,setReceipt]=useState<any>(),[criteria,setCriteria]=useState(tasks.map(t=>t.definition).filter(Boolean).join('\n')),[evidence,setEvidence]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState('');
 useEffect(()=>{void agentRequest('/api/agent/order-review?id='+encodeURIComponent(order.id)).then(r=>{setReceipt(r);if(r.review){setCriteria(r.review.criteria);setEvidence(r.review.evidence)}}).catch(e=>setError(e.message))},[order.id,order.output]);
 const save=async(verdict:string)=>{setBusy(true);try{setReceipt(await agentRequest('/api/agent/order-review','POST',{orderId:order.id,verdict,criteria,evidence,outputHash:receipt.outputHash}));setError('')}catch(e){setError(e instanceof Error?e.message:'검토 저장 실패')}finally{setBusy(false)}};
 return <div className="order-verification"><h4>결과 검토 기록</h4><p>실제 산출물과 완료 기준을 대조한 뒤 검토 결과를 남기세요.</p><label>완료 기준<textarea className="form-field" value={criteria} rows={2} maxLength={2000} onChange={e=>setCriteria(e.target.value)}/></label><label>확인한 산출물 · 검증 근거<textarea className="form-field" value={evidence} rows={3} maxLength={4000} placeholder="산출물 링크, 직접 확인한 결과, 테스트 결과" onChange={e=>setEvidence(e.target.value)}/></label><div className="order-actions"><button className="primary-button" disabled={busy||!receipt||!criteria.trim()||!evidence.trim()} onClick={()=>void save('accepted')}>기준 충족 확인</button><button className="secondary-button" disabled={busy||!receipt||!criteria.trim()||!evidence.trim()} onClick={()=>void save('needs_work')}>보완 필요로 기록</button></div>{error&&<p role="alert">{error}</p>}{receipt?.review&&<p role="status">{receipt.review.stale?'결과가 변경되어 재검토 필요':receipt.review.verdict==='accepted'?'사용자 검토 완료':'보완 필요'} · {new Date(receipt.review.reviewedAt).toLocaleString('ko-KR')}</p>}{receipt?.review?.verdict==='accepted'&&!receipt.review.stale&&tasks.filter(t=>t.status!=='done').map(t=><button key={t.id} className="text-button" disabled={busy} onClick={async()=>{setBusy(true);try{await onComplete(t.id)}finally{setBusy(false)}}}>{t.title} · 검토한 할 일 완료</button>)}</div>;
}
