'use client';
import {useEffect,useState} from 'react';
import {agentRequest} from './connections';
import type {SourceStatus} from '@/lib/orbit/source-status';
import type {View} from '@/lib/orbit/model';
interface Status {schedulerConfigured:boolean;config:{enabled:boolean;eveningHour:number;lastError?:string;lastSchedulerTick?:string};lastTick:string|null;sources:SourceStatus[];runs:{date:string;status:string;message?:string}[]}
export function RuntimePanel({demo,navigate}:{demo:boolean;navigate:(view:View)=>void}){
 const [status,setStatus]=useState<Status|null>(null),[error,setError]=useState(''),[busy,setBusy]=useState(false);
 useEffect(()=>{if(demo)return;const load=async()=>{try{setStatus(await agentRequest('/api/runtime'));setError('')}catch(e){setError(e instanceof Error?e.message:'상태 확인 실패')}};void load();const timer=setInterval(()=>{if(document.visibilityState==='visible')void load()},60000);return()=>clearInterval(timer)},[demo]);
 if(demo)return null;
 // eslint-disable-next-line react-hooks/purity -- the stale label compares the server tick with the wall clock at render time; snapshotting the time would change when the label flips
 const stale=!status?.config.lastSchedulerTick||Date.now()-Date.parse(status.config.lastSchedulerTick)>180000;
 const action=async(method:string,body?:unknown)=>{setBusy(true);try{setStatus(await agentRequest('/api/runtime',method,body));setError('')}catch(e){setError(e instanceof Error?e.message:'운영 확인 실패')}finally{setBusy(false)}};
 const labels:Record<string,string>={google_calendar:'Google 일정',google_tasks:'Google Tasks',google_mail:'Gmail',plaud:'Plaud 원문',hermes:'Hermes 실행'};
 return <details className="runtime-panel"><summary><strong>하루 운영</strong><span>{!status?'상태 확인 중':!status.schedulerConfigured?'예약 실행기 연결 대기':!status.config.enabled?'일시 정지':stale?'서버 연결 확인 필요':'서버 실행 중'}</span></summary><p>{status?.schedulerConfigured?'앱을 닫아도 접수된 분석을 이어가고, 매일 저녁 내일 제안을 준비합니다.':'예약 실행기 연결 후 앱을 닫아도 분석과 내일 제안 준비를 이어갈 수 있습니다. 지금은 아래 버튼으로 직접 처리할 수 있습니다.'} 일정 반영과 결과 완료는 직접 확인합니다.</p>{error&&<p role="alert" className="agent-error">{error}</p>}{status&&<><p>마지막 예약 실행 · {status.config.lastSchedulerTick?new Date(status.config.lastSchedulerTick).toLocaleString('ko-KR'):'아직 기록 없음'}</p>{status.config.lastError&&<p role="alert">{status.config.lastError}</p>}<div className="runtime-actions"><label><input type="checkbox" checked={status.config.enabled} disabled={busy} onChange={e=>void action('PUT',{...{enabled:e.target.checked,eveningHour:status.config.eveningHour}})}/> 앱 밖 실행</label><label>내일 제안 준비 시각<select value={status.config.eveningHour} disabled={busy} onChange={e=>void action('PUT',{enabled:status.config.enabled,eveningHour:Number(e.target.value)})}>{Array.from({length:24},(_,h)=><option key={h} value={h}>{h}시</option>)}</select></label><button className="secondary-button" disabled={busy} onClick={()=>void action('POST',{})}>{busy?'확인 중…':'지금 상태 확인'}</button></div><div className="source-status-list">{Object.entries(labels).map(([provider,label])=>{const s=status.sources.find(s=>s.provider===provider);return <div key={provider}><strong>{label}</strong><span>{!s?'조회 기록 없음':s.state==='ok'?'조회 성공':s.state==='partial'?'일부 범위 확인':'확인 필요'}</span><small>{s?.detail??'연결 여부와 실제 조회 성공은 별도로 확인합니다.'}{s?.succeededAt&&' · 마지막 성공 '+new Date(s.succeededAt).toLocaleString('ko-KR')}{s?.from&&' · '+s.from+' ~ '+s.to}{s?.targets&&' · '+s.targets.length+'개 캘린더'}</small></div>})}</div>{status.runs[0]&&<p>내일 제안 {status.runs[0].date} · {({running:'분석 중',completed:'검토 가능',failed:'실패 · 다시 요청 필요',local:'기본 계획 준비됨',queued:'준비 대기'} as Record<string,string>)[status.runs[0].status]} {status.runs[0].message}</p>}<div className="runtime-actions"><button className="text-button" onClick={()=>navigate('review')}>1분 회고 열기</button><button className="text-button" onClick={()=>navigate('proposal')}>내일 제안 확인</button></div><small>Hermes 분석은 연결된 Mac과 Hermes가 켜져 있어야 합니다. Plaud는 실제 조회한 자료만 포함하며, 조회 기록이 없으면 최신 자료로 표시하지 않습니다.</small></>}</details>;
}
