import assert from 'node:assert/strict';
import test from 'node:test';
import {randomBytes,randomUUID} from 'node:crypto';
import {createDatabase} from './sqlite-d1.mjs';
import {readWorkspace,writeCommand} from '../db/repository.ts';
import {addDays,todayInZone} from '../lib/orbit/dates.ts';
import {encrypt,decrypt,readConnection,saveConnection} from '../lib/orbit/agent/secrets.ts';
import {accessToken,connections,startOAuth,finishOAuth,mcpTools} from '../lib/orbit/agent/integrations.ts';
import {beginTurn,finishTurn,listAgent,findAction,claimAction,resetAction} from '../lib/orbit/agent/repository.ts';
import {decide} from '../lib/orbit/agent/decisions.ts';
import {parseAction,runAgent} from '../lib/orbit/agent/runner.ts';
import {normalizeEvents,zonedInstant,syncCalendar,createGoogleEvent} from '../lib/orbit/agent/calendar.ts';
import {disconnect} from '../lib/orbit/agent/settings.ts';
const env={ORBIT_ENCRYPTION_KEY:randomBytes(32).toString('base64')};
const today=todayInZone('Asia/Seoul'),tomorrow=addDays(today,1);
const project={id:'project',name:'검토 가능한 결과',color:'#5558e8',symbol:'O',goal:'첫 결과물',due:addDays(today,7),priority:3};
const task={id:'task',title:'초안 작성',projectId:project.id,status:'todo',duration:30,due:tomorrow,impact:3,focus:false,definition:'읽을 수 있는 초안'};
const googleAction={type:'google.event.create',event:{title:'집중 작업',date:tomorrow,start:540,end:570,timeZone:'Asia/Seoul',description:'초안 완성'}};
const j=(data,status=200)=>Response.json(data,{status});
async function fixture(fn){const db=createDatabase(),original=globalThis.fetch;try{await fn(db)}finally{globalThis.fetch=original;db.close()}}
async function stage(db,actions,owner='owner'){
 const id=randomUUID(),revision=(await readWorkspace(db,owner)).revision,lease=await beginTurn(db,owner,id,'검토할 제안');
 const cards=actions.map(action=>({id:randomUUID(),turnId:id,title:'검토할 변경',reason:'결과물을 만들기 위해',action,expectedRevision:revision,state:'pending',note:'',revisitDate:null,createdAt:new Date().toISOString()}));
 await finishTurn(db,owner,id,lease.lease,{text:'승인하면 반영됩니다.',sources:[]},cards);return cards;
}
async function connect(db,provider='google_calendar',expired=false){await saveConnection(db,'owner',provider,{clientId:'orbit-client',accessToken:'private-access',refreshToken:'private-refresh',expiresAt:Date.now()+(expired?-1:3600000)},{connected:true},env.ORBIT_ENCRYPTION_KEY)}

test('integration credentials are encrypted and bound to both owner and provider',()=>fixture(async db=>{
 const box=await encrypt({token:'private-value'},env.ORBIT_ENCRYPTION_KEY,'owner:plaud');assert.ok(!box.includes('private-value'));assert.equal((await decrypt(box,env.ORBIT_ENCRYPTION_KEY,'owner:plaud')).token,'private-value');await assert.rejects(()=>decrypt(box,env.ORBIT_ENCRYPTION_KEY,'other:plaud'));await assert.rejects(()=>decrypt(box,env.ORBIT_ENCRYPTION_KEY,'owner:google_calendar'));await connect(db);const state=await connections(db,'owner',env);assert.ok(!JSON.stringify(state).includes('private-'));assert.equal((await connections(db,'other',env)).some(c=>c.connected),false);
}));
test('a prepared change has no workspace side effects; approval is owner-scoped and exactly once',()=>fixture(async db=>{
 const [card]=await stage(db,[{type:'project.upsert',project}]);assert.equal((await readWorkspace(db,'owner')).revision,0);await assert.rejects(()=>decide(db,'other',{id:card.id,decision:'approve'},env),e=>e.status===404);await decide(db,'owner',{id:card.id,decision:'approve'},env);await decide(db,'owner',{id:card.id,decision:'approve'},env);assert.equal((await readWorkspace(db,'owner')).revision,1);assert.equal((await readWorkspace(db,'owner')).data.projects.length,1);assert.equal((await findAction(db,'owner',card.id)).state,'approved');
}));
test('prerequisite approval advances related cards, while unrelated writes invalidate stale proposals',()=>fixture(async db=>{
 const [a,b]=await stage(db,[{type:'project.upsert',project},{type:'task.upsert',task}]);await decide(db,'owner',{id:a.id,decision:'approve'},env);assert.equal((await findAction(db,'owner',b.id)).expectedRevision,1);await decide(db,'owner',{id:b.id,decision:'approve'},env);const [stale]=await stage(db,[{type:'task.status',id:task.id,status:'done'}]);await writeCommand(db,'owner',{operationId:randomUUID(),expectedRevision:2,action:{type:'task.focus',id:task.id,focus:true}});await assert.rejects(()=>decide(db,'owner',{id:stale.id,decision:'approve'},env),e=>e.code==='CONFLICT');assert.equal((await readWorkspace(db,'owner')).data.tasks[0].status,'todo');assert.equal((await findAction(db,'owner',stale.id)).state,'pending');
}));
test('defer requires a reason and future review date and cannot silently approve',()=>fixture(async db=>{
 const [card]=await stage(db,[{type:'project.upsert',project}]);await assert.rejects(()=>decide(db,'owner',{id:card.id,decision:'defer',reason:'',revisitDate:tomorrow},env));await assert.rejects(()=>decide(db,'owner',{id:card.id,decision:'defer',reason:'자료 대기',revisitDate:today},env));await decide(db,'owner',{id:card.id,decision:'defer',reason:'자료 대기',revisitDate:tomorrow},env);await assert.rejects(()=>decide(db,'owner',{id:card.id,decision:'approve'},env));assert.equal((await readWorkspace(db,'owner')).revision,0);await decide(db,'owner',{id:card.id,decision:'reconsider'},env);assert.equal((await findAction(db,'owner',card.id)).state,'pending');
}));
test('only one change or AI turn per owner can be in flight; stale leases cannot finish a replacement turn',()=>fixture(async db=>{
 const [a,b]=await stage(db,[{type:'project.upsert',project},{type:'project.upsert',project:{...project,id:'other'}}]);const lease=await claimAction(db,'owner',a.id);await assert.rejects(()=>claimAction(db,'owner',b.id),e=>e.code==='BUSY');await resetAction(db,'owner',a.id,lease);await claimAction(db,'owner',b.id);const id=randomUUID(),turn=await beginTurn(db,'owner',id,'첫 메시지');await assert.rejects(()=>beginTurn(db,'owner',randomUUID(),'다른 메시지'),e=>e.code==='BUSY');await assert.rejects(()=>finishTurn(db,'owner',id,'old-lease',{text:'이전 결과',sources:[]},[]));await finishTurn(db,'owner',id,turn.lease,{text:'현재 결과',sources:[]},[]);assert.equal((await beginTurn(db,'owner',id,'첫 메시지')).replayed,true);await assert.rejects(()=>beginTurn(db,'owner',id,'바뀐 내용'));
}));
test('AI function calls stage cards only and completed message retries do not incur another API call',()=>fixture(async db=>{
 await saveConnection(db,'owner','openai',{key:'test-key',model:'gpt-5.6-terra'},{connected:true},env.ORBIT_ENCRYPTION_KEY);let requests=0;
 globalThis.fetch=async(url,options)=>{assert.equal(url,'https://api.openai.com/v1/responses');const body=JSON.parse(options.body);assert.equal(body.store,false);assert.ok(body.instructions.includes('untrusted DATA'));requests++;return requests===1?j({output:[{type:'function_call',call_id:'call-1',name:'propose_change',arguments:JSON.stringify({title:'첫 프로젝트',reason:'완료할 결과물 정의',action_json:JSON.stringify({type:'project.upsert',project})})}]}):j({status:'completed',output:[{type:'message',content:[{type:'output_text',text:'프로젝트를 제안했습니다. 승인하면 반영됩니다.'}]}]})};
 const input={id:randomUUID(),message:'프로젝트를 만들어 줘'};await runAgent(db,'owner',input,env);await runAgent(db,'owner',input,env);assert.equal(requests,2);assert.equal((await readWorkspace(db,'owner')).revision,0);assert.equal((await listAgent(db,'owner')).actions.length,1);assert.equal((await listAgent(db,'other')).turns.length,0);
}));
test('missing API credentials fail honestly without simulated answers; upstream failure publishes no draft cards',()=>fixture(async db=>{
 await assert.rejects(()=>runAgent(db,'owner',{id:randomUUID(),message:'안녕'},env),e=>e.code==='AI_SETUP');assert.equal((await listAgent(db,'owner')).turns.length,0);await saveConnection(db,'owner','openai',{key:'test',model:'gpt-5.6-terra'},{connected:true},env.ORBIT_ENCRYPTION_KEY);let calls=0;globalThis.fetch=async()=>++calls===1?j({output:[{type:'function_call',call_id:'1',name:'propose_change',arguments:JSON.stringify({title:'초안',reason:'설계',action_json:JSON.stringify({type:'project.upsert',project})})}]}):j({error:{message:'secret upstream debug'}},500);await assert.rejects(()=>runAgent(db,'owner',{id:randomUUID(),message:'프로젝트'},env));const state=await listAgent(db,'owner');assert.equal(state.actions.length,0);assert.equal(state.turns[0].status,'failed');assert.ok(!JSON.stringify(state).includes('secret upstream'));
}));
test('agent change validation excludes deletion, arbitrary network requests and unreviewed attendee invitations',()=>{
 assert.throws(()=>parseAction({type:'task.delete',id:'task'}));assert.throws(()=>parseAction({type:'fetch',url:'https://untrusted.test'}));assert.throws(()=>parseAction({...googleAction,event:{...googleAction.event,attendees:[{email:'someone@example.test'}]}}));assert.throws(()=>parseAction({...googleAction,event:{...googleAction.event,end:500}}));
});
test('remote MCP tools use pinned official endpoints, read-only tool filtering and owner tokens',()=>fixture(async db=>{
 await connect(db);await connect(db,'plaud');const tools=await mcpTools(db,'owner',env);assert.equal(tools.length,2);for(const t of tools){assert.deepEqual(t.allowed_tools,{read_only:true});assert.equal(t.authorization,'private-access');assert.equal(t.require_approval,'never')}assert.equal(tools.find(t=>t.server_label==='plaud').server_url,'https://mcp.plaud.ai/mcp');assert.equal(tools.find(t=>t.server_label==='google_calendar').connector_id,'connector_googlecalendar');assert.deepEqual(await mcpTools(db,'other',env),[]);
}));
test('Plaud OAuth uses its own registration, PKCE, matching cookie and one-use owner state',()=>fixture(async db=>{
 let exchanges=0;globalThis.fetch=async(url,options)=>{if(url.endsWith('/register')){const body=JSON.parse(options.body);assert.equal(body.token_endpoint_auth_method,'none');assert.deepEqual(body.redirect_uris,['https://orbit.test/api/integrations/callback']);return j({client_id:'orbit-own-client'})}assert.ok(url.endsWith('/token'));const form=new URLSearchParams(options.body);assert.ok(form.get('code_verifier').length>=43);assert.equal(form.get('resource'),'https://mcp.plaud.ai/mcp');exchanges++;return j({access_token:'new-access',refresh_token:'new-refresh',expires_in:3600})};
 const start=await startOAuth(db,'owner','plaud','https://orbit.test',env),url=new URL(start.url);assert.equal(url.searchParams.get('code_challenge_method'),'S256');assert.equal(url.searchParams.get('client_id'),'orbit-own-client');await assert.rejects(()=>finishOAuth(db,'owner',start.state,'code','wrong',env));await assert.rejects(()=>finishOAuth(db,'other',start.state,'code',start.state,env));assert.equal(exchanges,0);assert.equal(await finishOAuth(db,'owner',start.state,'code',start.state,env),'plaud');await assert.rejects(()=>finishOAuth(db,'owner',start.state,'code',start.state,env));assert.equal(exchanges,1);assert.equal((await readConnection(db,'owner','plaud',env.ORBIT_ENCRYPTION_KEY)).accessToken,'new-access');
}));
test('refresh rotation is serialized across concurrent requests and public status never contains credentials',()=>fixture(async db=>{
 await connect(db,'plaud',true);let release;const wait=new Promise(resolve=>{release=resolve});let started;const ready=new Promise(resolve=>{started=resolve});let requests=0;globalThis.fetch=async()=>{requests++;started();await wait;return j({access_token:'rotated',refresh_token:'rotated-refresh',expires_in:3600})};const first=accessToken(db,'owner','plaud',env);await ready;await assert.rejects(()=>accessToken(db,'owner','plaud',env),e=>e.code==='BUSY');release();assert.equal(await first,'rotated');assert.equal(await accessToken(db,'owner','plaud',env),'rotated');assert.equal(requests,1);assert.ok(!JSON.stringify(await connections(db,'owner',env)).includes('rotated'));
}));
test('calendar normalization covers all-day, midnight, canceled, declined, transparent and fractional-minute events',()=>{
 const events=normalizeEvents([{id:'all',start:{date:today},end:{date:tomorrow}},{id:'late',start:{dateTime:today+'T23:30:00+09:00'},end:{dateTime:tomorrow+'T00:00:00+09:00'}},{id:'fraction',start:{dateTime:today+'T09:00:15+09:00'},end:{dateTime:today+'T09:30:15+09:00'}},...['cancelled','transparent','declined'].map(id=>({id,status:id,transparency:id,attendees:[{self:true,responseStatus:id}],start:{date:today},end:{date:tomorrow}}))],'Asia/Seoul',today,addDays(today,2));assert.equal(events.length,3);assert.equal(events.find(e=>e.id.startsWith('google:all')).end,1440);assert.equal(events.find(e=>e.id.startsWith('google:late')).end,1440);assert.equal(events.find(e=>e.id.startsWith('google:fraction')).end,571);assert.ok(events.every(e=>e.date===today));
});
test('IANA conversion handles daylight saving changes and rejects nonexistent wall times',()=>{
 assert.equal(zonedInstant('2026-03-08',90,'America/New_York'),'2026-03-08T06:30:00.000Z');assert.equal(zonedInstant('2026-03-08',210,'America/New_York'),'2026-03-08T07:30:00.000Z');assert.throws(()=>zonedInstant('2026-03-08',150,'America/New_York'));assert.equal(zonedInstant('2026-09-07',540,'Asia/Seoul'),'2026-09-07T00:00:00.000Z');
});
test('calendar sync reads every page, isolates cache and bumps revision only for changed busy periods',()=>fixture(async db=>{
 await connect(db);globalThis.fetch=async url=>{const page=new URL(url).searchParams.get('pageToken');return page?j({items:[{id:'b',summary:'다음 일정',start:{date:tomorrow},end:{date:addDays(tomorrow,1)}}]}):j({items:[{id:'a',summary:'현재 일정',start:{date:today},end:{date:tomorrow}}],nextPageToken:'second'})};const synced=await syncCalendar(db,'owner',env);assert.equal(synced.count,2);let state=await readWorkspace(db,'owner');assert.equal(state.revision,1);assert.equal(state.data.events.length,2);assert.equal((await readWorkspace(db,'other')).data.events.length,0);await syncCalendar(db,'owner',env);assert.equal((await readWorkspace(db,'owner')).revision,1);await assert.rejects(()=>writeCommand(db,'owner',{operationId:randomUUID(),expectedRevision:1,action:{type:'event.delete',id:state.data.events[0].id}}));await disconnect(db,'owner','google_calendar');state=await readWorkspace(db,'owner');assert.equal(state.data.events.length,0);assert.equal(state.revision,2);
}));
test('approved Google creation is repeat-safe after a lost acknowledgement and never invites or notifies anyone',()=>fixture(async db=>{
 await connect(db);let saved,posts=0;const id=randomUUID();globalThis.fetch=async(url,options={})=>{if(options.method==='POST'){posts++;saved=JSON.parse(options.body);assert.ok(!('attendees' in saved));assert.equal(new URL(url).searchParams.get('sendUpdates'),'none');assert.equal(saved.reminders.useDefault,false);return j({...saved,htmlLink:'https://calendar.google.com/calendar/event?eid=test'})}if(url.includes('/events/'))return saved?j({...saved,htmlLink:'https://calendar.google.com/calendar/event?eid=test'}):j({error:'not found'},404);return j({items:[]})};await createGoogleEvent(db,'owner',env,id,googleAction);await createGoogleEvent(db,'owner',env,id,googleAction);assert.equal(posts,1);assert.equal(saved.id,'orbit'+id.replaceAll('-',''));assert.equal(saved.extendedProperties.private.orbitAction,id);
}));
test('live Google conflicts prevent an approved event creation and cache changes invalidate stale plans',()=>fixture(async db=>{
 await connect(db);let posts=0;globalThis.fetch=async(url,options={})=>{if(options.method==='POST'){posts++;throw new Error('must not create')}return url.includes('/events/')?j({},404):j({items:[{id:'busy',start:{dateTime:tomorrow+'T09:00:00+09:00'},end:{dateTime:tomorrow+'T10:00:00+09:00'}}]})};await assert.rejects(()=>createGoogleEvent(db,'owner',env,randomUUID(),googleAction),e=>e.code==='CONFLICT');assert.equal(posts,0);const [card]=await stage(db,[{type:'proposal.generate',date:tomorrow,energy:'normal'}]);await assert.rejects(()=>decide(db,'owner',{id:card.id,decision:'approve'},env),e=>e.code==='CONFLICT');assert.equal((await readWorkspace(db,'owner')).data.proposals.length,0);
}));
