import {randomBytes} from 'node:crypto';
import {saveConnection} from '../lib/orbit/agent/secrets.ts';
import test from 'node:test';
import assert from 'node:assert/strict';
import {createDatabase} from './sqlite-d1.mjs';
import {readWorkspace,readNote,writeCommand} from '../db/repository.ts';
import {importRecording} from '../lib/orbit/meetings/store.ts';
import {processMeetingReviews,meetingReviewDetail,setMeetingDue} from '../lib/orbit/meetings/review-runtime.ts';
import {collectNotifications,listNotifications} from '../lib/orbit/notifications/store.ts';
import {decide} from '../lib/orbit/agent/decisions.ts';
const owner='auto-owner',env={OPENAI_API_KEY:'test-only'},project={id:'p',name:'피자',goal:'매장 준비',due:'2099-01-01',priority:3,color:'#7766aa',symbol:'P'};
const text='피자 계약 조건을 정리한다.';
async function seed(db){await writeCommand(db,owner,{operationId:crypto.randomUUID(),expectedRevision:0,action:{type:'project.upsert',project}});await importRecording(db,owner,{id:'new-meeting',title:'피자 논의',started:'2026-09-22',duration:5,transcript:text,summary:'',pending:true});return await readNote(db,owner,'plaud:new-meeting')}
function output(note,invalid=false){return {kind:'final',text:'회의 정보\n피자 논의\n안건별 요약\n계약 조건 정리가 필요합니다.\n다음 할 일\n계약 조건 정리\nAI 제안 및 확인할 내용\n마감일은 미정입니다.',proposals:[{title:'피자 계약 조건 정리',reason:'계약 협의 준비 · 예상 30분 제안',source:{line:note.body.split('\n').findIndex(l=>l===text)+1,quote:text},action:invalid?{type:'task.create',payload:{title:'계약 정리'}}:{type:'task.upsert',task:{title:'피자 계약 조건 정리',projectId:'p',duration:30,impact:3,definition:'검토할 계약 조건을 정리한 문서'}}}]}}
async function mocked(run,reply){const real=globalThis.fetch;globalThis.fetch=async(url,init)=>{assert.equal(url,'https://api.openai.com/v1/responses');const value=await reply(JSON.parse(init.body));return Response.json({status:'completed',output:[{type:'message',role:'assistant',content:[{type:'output_text',text:JSON.stringify(value)}]}]})};try{return await run()}finally{globalThis.fetch=real}}
test('import alone completes automatically, repairs malformed proposals, notifies, and blocks unknown due before approval',async()=>{const db=createDatabase();try{const note=await seed(db);let calls=0;await mocked(async()=>{for(let i=0;i<4;i++)await processMeetingReviews(db,owner,env)},request=>{assert.match(request.instructions,/회의 정보/);assert.doesNotMatch(request.instructions,/Additional reviewable actions/);return output(note,++calls===1)});
 const review=await meetingReviewDetail(db,owner,note.id);assert.equal(review.status,'completed',review.error);assert.equal(calls,2);assert.equal(review.actions.length,1);assert.match(review.summary,/안건별 요약/);assert.equal((await readWorkspace(db,owner)).data.tasks.length,0);
 const card=review.actions[0];assert.equal(card.guard.meeting.needsDue,true);await assert.rejects(()=>decide(db,owner,{id:card.id,decision:'approve'},env),e=>e.code==='MEETING_DUE');await setMeetingDue(db,owner,note.id,card.id,'2099-01-02');await decide(db,owner,{id:card.id,decision:'approve'},env);assert.equal((await readWorkspace(db,owner)).data.tasks[0].due,'2099-01-02');
 await collectNotifications(db,owner);const inbox=await listNotifications(db,owner);assert.ok(inbox.items.some(n=>n.kind==='approval'&&n.href.includes('note=')));const count=inbox.items.length;await collectNotifications(db,owner);assert.equal((await listNotifications(db,owner)).items.length,count);assert.equal((await listNotifications(db,'other')).items.length,0);
 }finally{db.close()}});
test('existing missed records and old extractor failures recover without opening the note',async()=>{const db=createDatabase();try{const note=await seed(db);await db.prepare('DELETE FROM orbit_meeting_reviews').run();await mocked(()=>processMeetingReviews(db,owner,env),()=>output(note));assert.equal((await meetingReviewDetail(db,owner,note.id)).status,'completed');const current=await db.prepare('SELECT turn_id FROM orbit_meeting_reviews').first();await db.prepare("UPDATE orbit_meeting_reviews SET status='failed',engine_version=1,error='지원하는 변경 형식이 아닙니다.'").run();await mocked(()=>processMeetingReviews(db,owner,env),()=>({...output(note),proposals:[]}));const next=await db.prepare('SELECT turn_id,status,engine_version FROM orbit_meeting_reviews').first();assert.notEqual(next.turn_id,current.turn_id);assert.equal(next.status,'completed');assert.equal(next.engine_version,2)}finally{db.close()}});
test('image-only Plaud summaries wait for real text and automatically continue after source revision',async()=>{const db=createDatabase();try{await importRecording(db,owner,{id:'image',title:'이미지 요약',started:'2026-09-22',duration:5,transcript:'',summary:'![](plaud://image?type=summaryCard&id=abc)',pending:true});const real=globalThis.fetch;globalThis.fetch=()=>{throw new Error('must not call model for absent text')};try{await processMeetingReviews(db,owner,env)}finally{globalThis.fetch=real}assert.equal((await meetingReviewDetail(db,owner,'plaud:image')).status,'waiting_source');await importRecording(db,owner,{id:'image',title:'이미지 요약',started:'2026-09-22',duration:5,transcript:'실제 회의 내용을 확인했다.',summary:'![](plaud://image?type=summaryCard&id=abc)',pending:false});await mocked(()=>processMeetingReviews(db,owner,env),()=>({kind:'final',text:'회의 정보\n실제 회의 내용 수집됨',proposals:[]}));assert.equal((await meetingReviewDetail(db,owner,'plaud:image')).status,'completed')}finally{db.close()}});
test('summary is retained when model repeatedly returns invalid proposals and failure is notified',async()=>{const db=createDatabase();try{const note=await seed(db);let calls=0;await mocked(async()=>{for(let i=0;i<5;i++)await processMeetingReviews(db,owner,env)},()=>{calls++;return output(note,true)});const review=await meetingReviewDetail(db,owner,note.id);assert.equal(review.status,'failed');assert.match(review.summary,/회의 정보/);assert.equal(review.actions.length,0);assert.equal(calls,3);assert.ok((await listNotifications(db,owner)).items.some(n=>n.kind==='failed'));assert.equal((await readWorkspace(db,owner)).data.tasks.length,0)}finally{db.close()}});
test('editing a new project due date preserves approval of its dependent task',async()=>{const db=createDatabase();try{const note=await seed(db),base=output(note),projectCard={...base.proposals[0],title:'신규 프로젝트',action:{type:'project.upsert',project:{id:'new-p',name:'신규 피자',goal:'가맹 준비'}}};base.proposals[0].action.task.projectId='new-p';base.proposals.unshift(projectCard);await mocked(()=>processMeetingReviews(db,owner,env),()=>base);let review=await meetingReviewDetail(db,owner,note.id);assert.equal(review.status,'completed',review.error);assert.equal(review.actions.length,2);await setMeetingDue(db,owner,note.id,review.actions[0].id,'2099-03-01');await decide(db,owner,{id:review.actions[0].id,decision:'approve'},env);await setMeetingDue(db,owner,note.id,review.actions[1].id,'2099-02-01');await decide(db,owner,{id:review.actions[1].id,decision:'approve'},env);const data=(await readWorkspace(db,owner)).data;assert.equal(data.tasks.length,1);assert.equal(data.projects.find(p=>p.id===data.tasks[0].projectId).due,'2099-03-01')}finally{db.close()}});

test('Hermes gateway receives only supported fields and finishes automatic meeting review',async()=>{const db=createDatabase(),real=globalThis.fetch;try{const note=await seed(db),nativeEnv={ORBIT_ENCRYPTION_KEY:randomBytes(32).toString('base64')};await saveConnection(db,owner,'hermes',{endpoint:'https://hermes.example.com',token:'private-fixture-token',connectionId:'native'},{connected:true,endpoint:'https://hermes.example.com',model:'Hermes'},nativeEnv.ORBIT_ENCRYPTION_KEY);let submitted=0;globalThis.fetch=async(url,options)=>{assert.ok(url.startsWith('https://hermes.example.com/v1/runs'));if(options.method==='POST'){const request=JSON.parse(options.body);assert.deepEqual(Object.keys(request).sort(),['conversation_history','input','instructions','session_id']);assert.match(request.instructions,/회의 정보/);submitted++;return Response.json({run_id:'meeting-native',status:'started'},{status:202});}return Response.json({object:'hermes.run',run_id:'meeting-native',status:'completed',output:JSON.stringify(output(note))});};await processMeetingReviews(db,owner,nativeEnv);assert.equal((await meetingReviewDetail(db,owner,note.id)).status,'completed');assert.equal(submitted,1)}finally{globalThis.fetch=real;db.close()}});
