import assert from 'node:assert/strict';
import test from 'node:test';
import {randomUUID} from 'node:crypto';
import {createDatabase} from './sqlite-d1.mjs';
import {writeCommand,readWorkspace,readNote,listNoteHistory,exportWorkspace,searchNotes,RevisionConflict,NoteNotFound} from '../db/repository.ts';
import {emptyWorkspace} from '../lib/orbit/model.ts';
import {meetingCandidates} from '../lib/orbit/meeting.ts';
import {commandSchema} from '../lib/orbit/validation.ts';
import {DomainError} from '../lib/orbit/reducer.ts';
const now=new Date('2026-09-06T13:00:00Z');
const project={id:'p',name:'프로젝트',color:'#5558e8',symbol:'O',goal:'결과물',due:'2026-09-10',priority:3};
const note={id:'n',title:'회의 기록',kind:'meeting',projectId:'p',summary:'회의 요약',body:'결정: 범위를 먼저 확정\n- [ ] 초안 작성\n할 일: 의견 요청\n- [x] 이미 끝낸 일\n날짜를 정할 수도 있다',tags:['회의록'],updated:'2026-09-06'};
const command=(revision,action)=>({operationId:randomUUID(),expectedRevision:revision,action});
async function seed(db){const state=await writeCommand(db,'a',command(0,{type:'project.upsert',project}),now);return writeCommand(db,'a',command(state.revision,{type:'note.upsert',note}),now)}
const restore=(revision,version,current)=>command(revision,{type:'note.restore',id:'n',revision:version,expectedNoteRevision:current});

test('note bodies are stored separately, owner-scoped and preserved in exports',async()=>{
 const db=createDatabase();try{const state=await seed(db);assert.equal(state.data.schemaVersion,3);assert.equal(state.data.notes[0].body,'');assert.equal(state.data.notes[0].bodyStored,true);assert.equal((await readNote(db,'a','n')).body,note.body);await assert.rejects(()=>readNote(db,'b','n'),NoteNotFound);await assert.rejects(()=>listNoteHistory(db,'b','n'),NoteNotFound);const output=await new Response(exportWorkspace(db,'a',state)).json();assert.equal(output.data.notes[0].body,note.body);assert.equal(output.data.projects[0].id,'p')}finally{db.close()}
});
test('legacy migration preserves original IDs, references and body in the same transaction as an edit',async()=>{
 const db=createDatabase();try{const legacy={...emptyWorkspace(),projects:[project],notes:[note],tasks:[{id:'t',title:'旧 할 일',projectId:'p',status:'todo',duration:30,due:'2026-09-07',impact:3,focus:false,definition:'확인',noteId:'n'}]};await db.prepare('INSERT INTO orbit_workspaces VALUES (?, ?, ?, ?, ?)').bind('a',7,JSON.stringify(legacy),'old',now.toISOString()).run();assert.equal((await readNote(db,'a','n')).body,note.body);const state=await writeCommand(db,'a',command(7,{type:'note.upsert',note:{...note,body:'새 내용'}}),now);assert.equal(state.data.notes[0].revision,2);assert.equal(state.data.tasks[0].noteId,'n');assert.equal((await readNote(db,'a','n',1)).body,note.body);assert.equal((await readNote(db,'a','n')).body,'새 내용')}finally{db.close()}
});
test('revision history is paged and restore adds a version without erasing history',async()=>{
 const db=createDatabase();try{let state=await seed(db);for(let i=2;i<=13;i++)state=await writeCommand(db,'a',command(state.revision,{type:'note.upsert',note:{...note,body:`내용 ${i}`}}),now);const first=await listNoteHistory(db,'a','n');assert.equal(first.items.length,10);assert.equal(first.nextBefore,4);const second=await listNoteHistory(db,'a','n',first.nextBefore);assert.deepEqual(second.items.map(i=>i.revision),[3,2,1]);state=await writeCommand(db,'a',restore(state.revision,1,13),now);assert.equal(state.data.notes[0].revision,14);assert.equal((await readNote(db,'a','n')).body,note.body);assert.equal((await readNote(db,'a','n',13)).body,'내용 13')}finally{db.close()}
});
test('stale note edits/restores and competing writes cannot overwrite or create stray versions',async()=>{
 const db=createDatabase();try{let state=await seed(db);const requests=[command(state.revision,{type:'note.upsert',note:{...note,body:'A'},expectedNoteRevision:1}),command(state.revision,{type:'note.upsert',note:{...note,body:'B'},expectedNoteRevision:1})];const outcomes=await Promise.allSettled(requests.map(r=>writeCommand(db,'a',r,now)));assert.equal(outcomes.filter(r=>r.status==='fulfilled').length,1);state=await readWorkspace(db,'a');assert.equal((await listNoteHistory(db,'a','n')).items.length,2);await assert.rejects(()=>writeCommand(db,'a',restore(state.revision,1,1),now),RevisionConflict);await assert.rejects(()=>writeCommand(db,'a',command(state.revision,{type:'note.upsert',note,expectedNoteRevision:1}),now),RevisionConflict)}finally{db.close()}
});
test('combined document bodies can exceed the former aggregate limit and export pinned versions',async()=>{
 const db=createDatabase();try{let state=await writeCommand(db,'a',command(0,{type:'project.upsert',project}),now);for(let i=0;i<11;i++)state=await writeCommand(db,'a',command(state.revision,{type:'note.upsert',note:{...note,id:`note-${i}`,body:'가'.repeat(90000)}}),now);assert.ok(JSON.stringify(state).length<10000);const original=state;await writeCommand(db,'a',command(state.revision,{type:'note.upsert',note:{...note,id:'note-0',body:'updated'}}),now);const result=await new Response(exportWorkspace(db,'a',original)).json();assert.equal(result.data.notes.length,11);assert.equal(result.data.notes[0].body.length,90000);assert.equal(result.data.notes.at(-1).body.length,90000)}finally{db.close()}
});
test('only explicit meeting markers become candidates; acceptance preserves evidence and is repeat-safe',async()=>{
 const db=createDatabase();try{let state=await seed(db);assert.deepEqual(meetingCandidates(note).map(c=>c.line),[2,3]);const action={type:'meeting.acceptActions',noteId:'n',expectedNoteRevision:1,items:[{id:'t',line:2,title:'초안 작성',definition:'검토 가능한 초안',due:'2026-09-08',duration:60}]};const request=command(state.revision,action);state=await writeCommand(db,'a',request,now);state=await writeCommand(db,'a',request,now);state=await writeCommand(db,'a',command(state.revision,action),now);assert.equal(state.data.tasks.length,1);assert.equal(state.data.tasks[0].noteCitation.quote,'- [ ] 초안 작성');assert.equal(state.data.tasks[0].noteId,'n');assert.equal(state.data.tasks[0].due,'2026-09-08');assert.equal(state.data.events.length,0);assert.equal(state.data.tasks[0].focus,false);state=await writeCommand(db,'a',command(state.revision,{type:'note.upsert',note:{...note,body:note.body+'\n추가 논의'}}),now);state=await writeCommand(db,'a',command(state.revision,{...action,expectedNoteRevision:2,items:[{...action.items[0],id:'new-request-id'}]}),now);assert.equal(state.data.tasks.length,1)}finally{db.close()}
});
test('invalid or stale meeting candidates cannot partially create tasks, and citations cannot be forged by editing',async()=>{
 const db=createDatabase();try{let state=await seed(db);const item={id:'t',line:2,title:'초안',definition:'확인',due:'2026-09-08',duration:30};const action={type:'meeting.acceptActions',noteId:'n',expectedNoteRevision:1,items:[item,{...item,id:'bad',line:5}]};await assert.rejects(()=>writeCommand(db,'a',command(state.revision,action),now),DomainError);assert.equal((await readWorkspace(db,'a')).data.tasks.length,0);state=await writeCommand(db,'a',command(state.revision,{...action,items:[item]}),now);const task=state.data.tasks[0];state=await writeCommand(db,'a',command(state.revision,{type:'task.upsert',task:{...task,noteCitation:{revision:99,line:99,quote:'forged'}}}),now);assert.equal(state.data.tasks[0].noteCitation.quote,'- [ ] 초안 작성');state=await writeCommand(db,'a',command(state.revision,{type:'note.upsert',note:{...note,body:'할 일: 다른 업무'}}),now);await assert.rejects(()=>writeCommand(db,'a',command(state.revision,{...action,items:[item]}),now),RevisionConflict)}finally{db.close()}
});
test('failed revision storage rolls back the aggregate and idempotency receipt',async()=>{
 const db=createDatabase();try{let state=await seed(db);const before=state.revision;await db.prepare("CREATE TRIGGER reject_note_insert BEFORE INSERT ON orbit_note_revisions BEGIN SELECT RAISE(ABORT, 'injected storage failure'); END").run();const request=command(before,{type:'note.upsert',note:{...note,body:'cannot save'}});await assert.rejects(()=>writeCommand(db,'a',request,now));state=await readWorkspace(db,'a');assert.equal(state.revision,before);assert.equal((await readNote(db,'a','n')).body,note.body);const receipt=await db.prepare('SELECT operation_id FROM orbit_mutations WHERE owner_id = ? AND operation_id = ?').bind('a',request.operationId).first();assert.equal(receipt,null)}finally{db.close()}
});
test('deletion checks references and removes the selected document history only',async()=>{
 const db=createDatabase();try{let state=await seed(db);state=await writeCommand(db,'a',command(state.revision,{type:'note.upsert',note:{...note,id:'other'}}),now);state=await writeCommand(db,'a',command(state.revision,{type:'note.delete',id:'n'}),now);await assert.rejects(()=>readNote(db,'a','n'),NoteNotFound);assert.equal((await db.prepare('SELECT COUNT(*) AS count FROM orbit_note_revisions WHERE owner_id = ? AND note_id = ?').bind('a','n').first()).count,0);assert.equal((await readNote(db,'a','other')).body,note.body)}finally{db.close()}
});
test('action schema rejects unbounded selections and untrusted source text',()=>{
 const item={id:'t',line:2,title:'할 일',definition:'확인',due:'2026-09-08',duration:30};assert.equal(commandSchema.safeParse(command(1,{type:'meeting.acceptActions',noteId:'n',expectedNoteRevision:1,items:[{...item,quote:'injected'}]})).success,false);assert.equal(commandSchema.safeParse(command(1,{type:'meeting.acceptActions',noteId:'n',expectedNoteRevision:1,items:Array(21).fill(item)})).success,false);
});

test('paged search finds current full bodies, excludes old revisions, and isolates owners',async()=>{
 const db=createDatabase();try{let state=await seed(db);for(let i=0;i<25;i++)state=await writeCommand(db,'a',command(state.revision,{type:'note.upsert',note:{...note,id:`search-${String(i).padStart(2,'0')}`,body:'원문에서만 찾을 수 있는 키워드'}}),now);const first=await searchNotes(db,'a',{query:'키워드',kind:'wiki',offset:0,expectedRevision:state.revision});assert.equal(first.items.length,24);assert.equal(first.hasMore,true);assert.ok(first.items.every(n=>n.body===''));const last=await searchNotes(db,'a',{query:'키워드',kind:'wiki',offset:24});assert.equal(last.items.length,1);assert.equal(last.hasMore,false);assert.ok(!first.items.some(n=>n.id===last.items[0].id));assert.equal((await searchNotes(db,'b',{query:'키워드',kind:'wiki',offset:0})).items.length,0);state=await writeCommand(db,'a',command(state.revision,{type:'note.upsert',note:{...note,id:'search-00',body:'changed'}}),now);assert.equal((await searchNotes(db,'a',{query:'키워드',kind:'wiki',offset:0})).hasMore,false);await assert.rejects(()=>searchNotes(db,'a',{query:'',kind:'wiki',offset:0,expectedRevision:state.revision-1}),RevisionConflict)}finally{db.close()}
});
