import test from 'node:test';
import assert from 'node:assert/strict';
import {randomBytes,randomUUID} from 'node:crypto';
import {createDatabase} from './sqlite-d1.mjs';
import {readWorkspace,writeCommand} from '../db/repository.ts';
import {emptyWorkspace} from '../lib/orbit/model.ts';
import {todayInZone,addDays} from '../lib/orbit/dates.ts';
import {saveConnection} from '../lib/orbit/agent/secrets.ts';
import {normalizeEvents,syncCalendar} from '../lib/orbit/agent/calendar.ts';
import {exportFocus,calendarExports} from '../lib/orbit/agent/calendar-export.ts';
import {recordSource,sourceStatuses} from '../lib/orbit/source-status.ts';
import {tickRuntime,runtimeStatus,runtimeSettings,eveningDue} from '../lib/orbit/daily-runtime.ts';
import {readOrderReview,saveOrderReview,outputHash} from '../lib/orbit/agent/order-review.ts';
import {draftKey,readDraft,saveDraft,clearDraft} from '../lib/orbit/device-drafts.ts';
const env={ORBIT_ENCRYPTION_KEY:randomBytes(32).toString('base64')};
const date=addDays(todayInZone('Asia/Seoul'),1);
async function fixture(fn){const db=createDatabase(),original=globalThis.fetch;try{await fn(db)}finally{db.close();globalThis.fetch=original;}}
async function connect(db){await saveConnection(db,'owner','google_calendar',{clientId:'client',accessToken:'test',expiresAt:Date.now()+3600000},{connected:true},env.ORBIT_ENCRYPTION_KEY);}
async function seed(db){const data=emptyWorkspace();data.proposals=[{id:'p',date,energy:'normal',items:[{id:'focus',state:'approved'}]}];data.events=[{id:'approved:focus',title:'Focus',date,start:600,end:630,kind:'focus'}];await db.prepare('INSERT INTO orbit_workspaces(owner_id,revision,state_json,mutation_id,updated_at) VALUES(?,?,?,?,?)').bind('owner',1,JSON.stringify(data),'seed',new Date().toISOString()).run();}
test('source failures preserve last success and remain owner scoped',()=>fixture(async db=>{const first=await recordSource(db,'a','plaud',{state:'ok',detail:'one source'});await recordSource(db,'a','plaud',{state:'error',detail:'failed'});const [r]=await sourceStatuses(db,'a');assert.equal(r.succeededAt,first.succeededAt);assert.equal(r.state,'error');assert.deepEqual(await sourceStatuses(db,'b'),[]);}));
test('same native event ID in two calendars keeps separate busy records',()=>{const e={id:'same',start:{date},end:{date:addDays(date,1)}};const rows=normalizeEvents([{...e,orbitCalendarId:'primary'},{...e,orbitCalendarId:'aux@group'}],'Asia/Seoul',date,addDays(date,1));assert.equal(new Set(rows.map(r=>r.id)).size,2);assert.equal(rows.find(r=>r.google.calendarId==='primary').id,'google:same:'+date);});
test('a selection changing during collection never receives a false success receipt',()=>fixture(async db=>{await connect(db);globalThis.fetch=async()=>{await db.prepare('INSERT OR REPLACE INTO orbit_calendar_settings(owner_id,selected_json,updated_at) VALUES(?,?,?)').bind('owner','["aux"]','new-version').run();return Response.json({items:[]});};await assert.rejects(()=>syncCalendar(db,'owner',env));const [s]=await sourceStatuses(db,'owner');assert.equal(s.state,'error');assert.equal(await db.prepare('SELECT owner_id FROM orbit_calendar_cache WHERE owner_id=?').bind('owner').first(),null);}));
test('lost Google ACK reuses one remote event, and duplicate cache rows disappear only for matching focus time',()=>fixture(async db=>{await seed(db);await connect(db);let remote,posts=0;globalThis.fetch=async(url,init={})=>{if(init.method==='POST'){posts++;remote=JSON.parse(init.body);throw new Error('lost ack');}if(url.includes('/events/'))return remote?Response.json({...remote,htmlLink:'https://calendar.google.com/calendar/event?eid=x'}):Response.json({}, {status:404});return Response.json({items:remote?[remote]:[]});};await assert.rejects(()=>exportFocus(db,'owner',env,'approved:focus'));assert.equal((await calendarExports(db,'owner'))[0].status,'uncertain');const result=await exportFocus(db,'owner',env,'approved:focus');assert.equal(result.status,'verified');assert.equal(posts,1);assert.equal((await readWorkspace(db,'owner')).data.events.length,1);assert.equal((await calendarExports(db,'other')).length,0);}));
test('publishing receipt blocks concurrent workspace writes and revalidates current approval',()=>fixture(async db=>{await seed(db);await connect(db);let blocked=false;globalThis.fetch=async(url,init={})=>{if(url.includes('/events/')){await assert.rejects(()=>writeCommand(db,'owner',{operationId:randomUUID(),expectedRevision:1,action:{type:'proposal.revoke',date,itemId:'focus'}}));blocked=true;const data=(await readWorkspace(db,'owner')).data;data.events=[];data.proposals[0].items[0].state='pending';await db.prepare('UPDATE orbit_workspaces SET state_json=? WHERE owner_id=?').bind(JSON.stringify(data),'owner').run();return Response.json({}, {status:404});}assert.notEqual(init.method,'POST');return Response.json({items:[]});};await assert.rejects(()=>exportFocus(db,'owner',env,'approved:focus'),e=>e.code==='CONFLICT');assert.equal(blocked,true);}));
test('daily runtime prepares one plan per date, is pausable and separates owners',()=>fixture(async db=>{for(let i=0;i<7;i++)await tickRuntime(db,'a',env);const first=await runtimeStatus(db,'a');assert.equal(first.runs.length,1);assert.equal(first.runs[0].status,'local');await runtimeSettings(db,'a',{enabled:false,eveningHour:20});assert.equal((await tickRuntime(db,'a',env)).disabled,true);assert.equal((await runtimeStatus(db,'b')).runs.length,0);}));
test('evening time follows workspace timezone',()=>{assert.equal(eveningDue(new Date('2026-09-16T12:00:00Z'),'Asia/Seoul',21),true);assert.equal(eveningDue(new Date('2026-09-16T11:59:00Z'),'Asia/Seoul',21),false);});
test('review receipts bind exact output and never complete work on their own',()=>fixture(async db=>{const id=randomUUID(),state={status:'completed',output:'artifact one'};await db.prepare('INSERT INTO orbit_agent_orders(owner_id,id,connection_id,request_json,state_json,created_at) VALUES(?,?,?,?,?,?)').bind('owner',id,'connection','{}',JSON.stringify(state),new Date().toISOString()).run();const hash=await outputHash(state.output);await saveOrderReview(db,'owner',{orderId:id,verdict:'accepted',criteria:'document',evidence:'opened artifact',outputHash:hash});assert.equal((await readOrderReview(db,'owner',id)).review.verdict,'accepted');state.output='artifact two';await db.prepare('UPDATE orbit_agent_orders SET state_json=? WHERE owner_id=? AND id=?').bind(JSON.stringify(state),'owner',id).run();assert.equal((await readOrderReview(db,'owner',id)).review.stale,true);await assert.rejects(()=>saveOrderReview(db,'owner',{orderId:id,verdict:'accepted',criteria:'document',evidence:'old output',outputHash:hash}));await assert.rejects(()=>readOrderReview(db,'other',id));assert.equal((await readWorkspace(db,'owner')).data.tasks.length,0);}));
test('device drafts isolate accounts; failed cleanup cannot invalidate server acknowledgement',()=>{const storage=new Map();globalThis.window={};globalThis.localStorage={getItem:k=>storage.get(k)??null,setItem:(k,v)=>storage.set(k,v),removeItem:()=>{throw new Error('locked')}};try{saveDraft('a','chat','1','unsent');assert.equal(readDraft('a','chat','1'),'unsent');assert.equal(readDraft('b','chat','1'),null);assert.notEqual(draftKey('a','chat','1'),draftKey('b','chat','1'));assert.doesNotThrow(()=>clearDraft('a','chat','1'));}finally{delete globalThis.window;delete globalThis.localStorage;}});
