'use client';
import {useEffect,useRef,useState,type ReactNode} from 'react';
import {Paperclip,Upload,FileText,Film,Image as ImageIcon,Download,X,LoaderCircle,RotateCcw,FolderOpen} from 'lucide-react';
import {Attachment,AttachmentMedia,AttachmentContent,AttachmentTitle,AttachmentDescription,AttachmentActions,AttachmentAction} from '@/components/ui/attachment';
import {Progress} from '@/components/ui/progress';
import {Dialog,DialogContent,DialogHeader,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {useAttachments,FILE_ACCEPT} from './provider';
import {fileSize,fileUrl,type StoredAttachment} from '@/lib/orbit/attachments/types';
import {agentRequest} from '../agent/connections';
const iconFor=(mime:string)=>mime.startsWith('video/')?Film:mime.startsWith('image/')?ImageIcon:FileText;
export function FileDrop({children,onFiles,disabled=false,className=''}:{children:ReactNode;onFiles:(files:File[])=>void;disabled?:boolean;className?:string}){const [over,setOver]=useState(false);return <div className={'file-drop '+className+(over?' file-over':'')} onDragOver={e=>{if(!disabled&&e.dataTransfer.types.includes('Files')){e.preventDefault();e.dataTransfer.dropEffect='copy';setOver(true)}}} onDragLeave={e=>{if(!(e.relatedTarget instanceof Node)||!e.currentTarget.contains(e.relatedTarget))setOver(false)}} onDrop={e=>{setOver(false);if(e.dataTransfer.files.length){e.preventDefault();e.stopPropagation();if(!disabled)onFiles([...e.dataTransfer.files])}}}>{children}{over&&<div className="file-drop-overlay"><Upload size={26}/><strong>여기에 놓아 첨부하세요</strong></div>}</div>}
export function FileCards({files}:{files:StoredAttachment[]}){const [preview,setPreview]=useState<StoredAttachment|null>(null),[mediaError,setMediaError]=useState(false);return <><div className="saved-files">{files.map(file=>{const Icon=iconFor(file.mime);return <Attachment className="orbit-file" key={file.id}><AttachmentMedia>{file.preview?<img src={fileUrl(file.id,true)} alt="" loading="lazy" width={48} height={48}/>:<Icon size={22}/>}</AttachmentMedia><AttachmentContent><button type="button" className="file-open" onClick={()=>{setMediaError(false);setPreview(file)}}><AttachmentTitle>{file.name}</AttachmentTitle><AttachmentDescription>{fileSize(file.size)}</AttachmentDescription></button></AttachmentContent><AttachmentActions><a href={fileUrl(file.id)} target="_blank" rel="noreferrer" className="icon-button" aria-label={file.name+' 원본 열기'}><Download size={16}/></a></AttachmentActions></Attachment>})}</div>{preview&&<Dialog open onOpenChange={open=>{if(!open)setPreview(null)}}><DialogContent className="file-preview-dialog"><DialogHeader><DialogTitle>{preview.name}</DialogTitle><DialogDescription>{fileSize(preview.size)} · {preview.contextLabel}</DialogDescription></DialogHeader>{preview.mime.startsWith('video/')?<><video src={fileUrl(preview.id)} controls playsInline preload="metadata" onError={()=>setMediaError(true)}/>{mediaError&&<p className="form-hint">이 기기에서 재생하지 못했습니다. 원본 파일을 내려받아 열어 주세요.</p>}</>:preview.preview?<img className="file-preview-image" src={fileUrl(preview.id,true)} alt={preview.name}/>:<div className="file-no-preview"><FileText size={36}/><p>원본 파일을 내려받아 확인할 수 있습니다.</p></div>}<a className="primary-button" href={fileUrl(preview.id)} target="_blank" rel="noreferrer"><Download size={16}/> 원본 열기 / 다운로드</a></DialogContent></Dialog>}</>}
export function AttachmentInput({scope,disabled=false,compact=false}:{scope:string;disabled?:boolean;compact?:boolean}){
 const upload=useAttachments(scope),input=useRef<HTMLInputElement>(null),[recent,setRecent]=useState<StoredAttachment[]|null>(null),[loading,setLoading]=useState(false),[error,setError]=useState('');
 async function openRecent(){setLoading(true);setError('');try{const r=await agentRequest('/api/attachments');setRecent(r.items)}catch(e){setError(e instanceof Error?e.message:'파일을 불러오지 못했습니다.')}finally{setLoading(false)}}
 return <FileDrop onFiles={upload.add} disabled={disabled} className={'attachment-input '+(compact?'compact':'')}><div className="attachment-buttons"><input ref={input} type="file" multiple accept={FILE_ACCEPT} className="sr-only" onChange={e=>{upload.add([...(e.target.files??[])]);e.target.value=''}} disabled={disabled}/><button type="button" className="text-button" disabled={disabled} onClick={()=>input.current?.click()}><Paperclip size={17}/> 파일 첨부</button><button type="button" className="text-button file-recent" disabled={disabled||loading} onClick={()=>void openRecent()}>{loading?<LoaderCircle size={15} className="animate-spin"/>:<FolderOpen size={15}/>} 업로드한 파일</button>{!compact&&<span className="file-hint">끌어다 놓기 · 이미지/문서 25 MB · 영상 100 MB</span>}</div>{error&&<p className="agent-error" role="alert">{error}</p>}<div className="upload-files">{upload.items.map(item=>{const Icon=iconFor(item.mime);return <Attachment key={item.id} className="orbit-file upload-file" state={item.status==='error'?'error':item.status==='ready'?'done':'uploading'}><AttachmentMedia>{item.stored?.preview?<img src={fileUrl(item.id,true)} alt="" width={48} height={48}/>:<Icon size={22}/>}</AttachmentMedia><AttachmentContent><AttachmentTitle>{item.name}</AttachmentTitle><AttachmentDescription>{item.status==='error'?item.error:item.status==='ready'?fileSize(item.size)+' · 준비됨':item.status==='processing'?'미리보기를 준비하는 중':item.progress+'% · 업로드 중'}</AttachmentDescription>{!['ready','error'].includes(item.status)&&<Progress value={item.progress} aria-label={item.name+' 업로드'} className="file-progress"/>}</AttachmentContent><AttachmentActions>{item.status==='error'&&<AttachmentAction disabled={disabled} onClick={()=>upload.retry(item.id)} aria-label={item.name+' 다시 시도'}><RotateCcw size={15}/></AttachmentAction>}<AttachmentAction disabled={disabled} onClick={()=>upload.remove(item.id)} aria-label={item.name+' 첨부에서 빼기'}><X size={15}/></AttachmentAction></AttachmentActions></Attachment>})}</div>{recent&&<Dialog open onOpenChange={open=>{if(!open)setRecent(null)}}><DialogContent><DialogHeader><DialogTitle>업로드한 파일</DialogTitle><DialogDescription>아직 대화나 일정에 보관하지 않은 파일입니다. 선택하면 현재 첨부에 추가됩니다.</DialogDescription></DialogHeader><div className="recent-files">{recent.length?recent.map(f=><button type="button" key={f.id} className="link-card" disabled={disabled} onClick={()=>{if(upload.adopt([f]))setRecent(null)}}><FileText size={18}/><span>{f.name}<small>{fileSize(f.size)}</small></span></button>):<p>보관을 기다리는 파일이 없습니다.</p>}</div></DialogContent></Dialog>}</FileDrop>;
}
export function EventFiles({eventId,demo,onSave}:{eventId:string;demo:boolean;onSave:(ids:string[])=>Promise<boolean>}){
 const scope='event:'+eventId,upload=useAttachments(scope),[files,setFiles]=useState<StoredAttachment[]>([]),[editing,setEditing]=useState(false),[loading,setLoading]=useState(false),[saving,setSaving]=useState(false),[error,setError]=useState('');
 useEffect(()=>{let active=true;setFiles([]);setEditing(false);if(demo)return;setLoading(true);void agentRequest('/api/attachments?type=event&id='+encodeURIComponent(eventId)).then(r=>{if(active){setFiles(r.items);upload.adopt(r.items)}}).catch(e=>{if(active)setError(e.message)}).finally(()=>{if(active)setLoading(false)});return()=>{active=false}},[eventId,demo]);
 return <div className="event-files"><div className="section-title"><h3><Paperclip size={16}/> 첨부파일</h3><button className="text-button" disabled={demo||loading} onClick={()=>setEditing(v=>!v)}>{editing?'닫기':'파일 추가 / 정리'}</button></div>{loading?<p className="form-hint">첨부파일을 불러오는 중</p>:<FileCards files={files}/>} {!files.length&&!editing&&!loading&&<p className="form-hint">회의 자료나 사진을 이 일정에 보관하세요.</p>}{error&&<p role="alert" className="agent-error">{error}</p>}{editing&&<><AttachmentInput scope={scope} disabled={demo||saving}/><button className="primary-button" disabled={saving||upload.busy} onClick={async()=>{setSaving(true);if(await onSave(upload.ready.map(f=>f.id))){setFiles(upload.ready);setEditing(false)}setSaving(false)}}>{saving?'저장 중…':'일정에 보관'}</button></>}</div>
}
