'use client';
import {createContext,useContext,useEffect,useRef,useState,type ReactNode} from 'react';
import {toast} from 'sonner';
import {agentRequest} from '../agent/connections';
import {FILE_ACCEPT,MAX_FILES,MAX_FILE_BYTES,MAX_DOCUMENT_BYTES,fileTypes,type StoredAttachment} from '@/lib/orbit/attachments/types';
import {ShareHandoffs} from '@/lib/orbit/share-handoffs';
import {removeShare} from '@/lib/orbit/share-drafts';
import {prepareFile} from '@/lib/orbit/attachments/prepare-client';
export {FILE_ACCEPT};
export interface UploadItem {id:string;name:string;size:number;mime:string;file?:File;stored?:StoredAttachment;progress:number;status:'queued'|'uploading'|'processing'|'ready'|'error';error?:string}
interface UploadStore {items:Record<string,UploadItem[]>;add:(scope:string,files:File[],ids?:string[])=>void;adopt:(scope:string,files:StoredAttachment[])=>boolean;remove:(scope:string,id:string)=>void;clear:(scope:string,ids:string[])=>void;retry:(scope:string,id:string)=>void;transfer:(from:string,to:string)=>boolean;registerShare:(scope:string,id:string,fileIds:string[])=>void;completeShare:(scope:string,committedIds:string[])=>Promise<void>}
const Context=createContext<UploadStore|null>(null);
function put(url:string,file:Blob,progress:(n:number)=>void){return new Promise<StoredAttachment>((resolve,reject)=>{const xhr=new XMLHttpRequest();xhr.open('PUT',url);xhr.setRequestHeader('Content-Type',file.type||'application/octet-stream');xhr.timeout=240000;xhr.upload.onprogress=e=>{if(e.lengthComputable)progress(Math.round(e.loaded/e.total*88))};xhr.onload=()=>{try{const data=JSON.parse(xhr.responseText);if(xhr.status>=200&&xhr.status<300)resolve(data);else reject(new Error(data.error??'파일 업로드를 확인하지 못했습니다.'))}catch{reject(new Error('로그인과 연결 상태를 확인해 주세요.'))}};xhr.onerror=xhr.ontimeout=()=>reject(new Error('전송이 끊겼습니다. 다시 시도하면 이어서 확인합니다.'));xhr.send(file)})}
export function AttachmentProvider({children}:{children:ReactNode}){
 const [items,setItems]=useState<Record<string,UploadItem[]>>({}),ref=useRef(items),mounted=useRef(true),jobs=useRef<Array<()=>Promise<void>>>([]),running=useRef(0),destinations=useRef(new Map<string,string>()),shareIds=useRef(new ShareHandoffs());
 useEffect(()=>{mounted.current=true;return()=>{mounted.current=false}},[]);
 const publish=(next:Record<string,UploadItem[]>)=>{ref.current=next;if(mounted.current)setItems(next)};
 const update=(scope:string,id:string,patch:Partial<UploadItem>)=>{const target=destinations.current.get(id)??scope;publish({...ref.current,[target]:(ref.current[target]??[]).map(item=>item.id===id?{...item,...patch}:item)})};
 const drain=()=>{while(running.current<2&&jobs.current.length){running.current++;void jobs.current.shift()!().finally(()=>{running.current--;drain()})}};
 const enqueue=(scope:string,item:UploadItem)=>{jobs.current.push(async()=>{try{update(scope,item.id,{status:'uploading',error:undefined});let stored:StoredAttachment=await agentRequest('/api/attachments','POST',{id:item.id,name:item.name,size:item.size});if(stored.prepared){update(scope,item.id,{status:'ready',stored,progress:100});return}if(stored.state!=='ready')stored=await put('/api/attachments/content?id='+item.id,item.file!,n=>update(scope,item.id,{progress:n}));update(scope,item.id,{status:'processing',progress:90});const prepared=await prepareFile(item.file!);if(prepared.preview)stored=await put('/api/attachments/preview?id='+item.id,prepared.preview,()=>{});stored=await agentRequest('/api/attachments/context','POST',{id:item.id,text:prepared.text,label:prepared.label});update(scope,item.id,{status:'ready',stored,progress:100});}catch(e){update(scope,item.id,{status:'error',error:e instanceof Error?e.message:'업로드를 완료하지 못했습니다.'})}});drain()};
 const add=(scope:string,files:File[],ids?:string[])=>{const existing=ref.current[scope]??[];if(existing.length+files.filter((_,i)=>!ids?.[i]||!existing.some(f=>f.id===ids[i])).length>MAX_FILES){toast.error('한 번에 파일 8개까지 첨부할 수 있습니다.');return}const next:UploadItem[]=[];for(const [index,file] of files.entries()){if(ids?.[index]&&existing.some(f=>f.id===ids[index]))continue;const mime=fileTypes[file.name.split('.').pop()!.toLowerCase()];if(!mime||!file.size||file.size>(mime.startsWith('video/')?MAX_FILE_BYTES:MAX_DOCUMENT_BYTES)){const id=ids?.[index]??crypto.randomUUID();next.push({id,name:file.name,size:file.size,mime:mime??'application/octet-stream',file,status:'error',progress:0,error:'지원하는 파일과 크기를 확인해 주세요.'});continue}const id=ids?.[index]??crypto.randomUUID();if(existing.some(f=>f.id===id))continue;destinations.current.set(id,scope);next.push({id,name:file.name,size:file.size,mime,file,status:'queued',progress:0})}publish({...ref.current,[scope]:[...existing,...next]});next.filter(item=>item.status!=='error').forEach(item=>enqueue(scope,item))};
 const adopt=(scope:string,files:StoredAttachment[])=>{const old=ref.current[scope]??[],next=files.filter(f=>!old.some(o=>o.id===f.id));if(old.length+next.length>MAX_FILES){toast.error('파일 8개까지 선택해 주세요.');return false}next.forEach(f=>destinations.current.set(f.id,scope));publish({...ref.current,[scope]:[...old,...next.map(f=>({id:f.id,name:f.name,size:f.size,mime:f.mime,stored:f,progress:100,status:'ready' as const}))]});return true};
 const clear=(scope:string,ids:string[])=>{publish({...ref.current,[scope]:(ref.current[scope]??[]).filter(f=>!ids.includes(f.id))})};
 const registerShare=(scope:string,id:string,fileIds:string[])=>shareIds.current.register(scope,id,fileIds);
 const completeShare=(scope:string,committedIds:string[])=>shareIds.current.complete(scope,committedIds,removeShare);
 const transfer=(from:string,to:string)=>{if(from===to)return true;const old=ref.current[to]??[],values=(ref.current[from]??[]).filter(f=>!old.some(o=>o.id===f.id));if(old.length+values.length>MAX_FILES){toast.error('파일 8개까지 선택해 주세요.');return false}values.forEach(f=>destinations.current.set(f.id,to));publish({...ref.current,[from]:[],[to]:[...old,...values]});shareIds.current.transfer(from,to);return true};
 return <Context.Provider value={{items,add,adopt,clear,transfer,registerShare,completeShare,remove:(scope,id)=>clear(scope,[id]),retry:(scope,id)=>{const item=ref.current[scope]?.find(f=>f.id===id);if(item?.file&&item.status==='error'){update(scope,id,{status:'queued'});enqueue(scope,item)}}}}>{children}</Context.Provider>;
}
export function useAttachments(scope:string){const store=useContext(Context);if(!store)throw new Error('AttachmentProvider required');const items=store.items[scope]??[];return {...store,adoptAt:store.adopt,clearAt:store.clear,items,ready:items.filter(i=>i.status==='ready').map(i=>i.stored!),busy:items.some(i=>i.status!=='ready'),add:(files:File[],ids?:string[])=>store.add(scope,files,ids),adopt:(files:StoredAttachment[])=>store.adopt(scope,files),remove:(id:string)=>store.remove(scope,id),retry:(id:string)=>store.retry(scope,id),clear:(ids:string[])=>store.clear(scope,ids)};}
