'use client';
import type {WorkspaceAction} from '@/lib/orbit/validation';
import {DropdownMenu,DropdownMenuTrigger,DropdownMenuContent,DropdownMenuItem} from '@/components/ui/dropdown-menu';
import {NoteLibrary} from '../note-library';
import {useEffect,useLayoutEffect,useMemo,useRef,useState} from 'react';
import {BookOpen,Network,RefreshCw,Link2,LoaderCircle,Search,ArrowUpRight} from 'lucide-react';
import {Connections,agentRequest} from '../agent/connections';
import type {Connection} from '@/lib/orbit/agent/types';
import type {Note,WorkspaceData} from '@/lib/orbit/model';
import {wikiGraph,wikiConnections,wikiLinks} from '@/lib/orbit/wiki/relations';
import {layoutGraph} from '@/lib/orbit/graph';
import {normalize} from '@/lib/orbit/classify';
export function WikiLibrary({onAsk,data,revision,demo,busy,onRefresh,onOpen,perform,initialKind=''}:{initialKind?:string;onAsk:(text:string)=>void;data:WorkspaceData;revision:number;perform:(a:WorkspaceAction,message?:string)=>Promise<boolean>;demo:boolean;busy:boolean;onRefresh:()=>Promise<void>;onOpen:(kind:'note'|'task'|'event',id:string)=>void}){
 const [mode,setMode]=useState<'graph'|'list'|'search'>('search'),[selected,setSelected]=useState(''),[query,setQuery]=useState(''),[loading,setLoading]=useState(!demo),[syncing,setSyncing]=useState(false),[message,setMessage]=useState(''),[error,setError]=useState(''),[connecting,setConnecting]=useState(false),[connections,setConnections]=useState<Connection[]>([]),[zoom,setZoom]=useState(1);
 const [projectId,setProjectId]=useState(''),[tag,setTag]=useState(''),[documentKind,setDocumentKind]=useState(initialKind);
 const refresh=useRef(onRefresh),lock=useRef(false),busyRef=useRef(busy);
 useLayoutEffect(()=>{refresh.current=onRefresh;busyRef.current=busy},[onRefresh,busy]);
 async function sync(){if(demo||lock.current||busyRef.current)return;lock.current=true;setSyncing(true);setError('');try{const result=await agentRequest('/api/wiki','POST',{action:'sync'});setMessage(result.warnings?.length?result.warnings.join(' / '):result.mail?.connected?`메일 ${result.mail.count}개 추가 · ${result.mail.more?'최근 30일 기록을 계속 가져오는 중':'최근 수집 완료'}`:'일정 확인 완료 · Gmail을 연결하면 메일도 수집합니다.');await refresh.current()}catch(e){setError((e as Error).message)}finally{lock.current=false;setSyncing(false)}}
 useEffect(()=>{if(demo)return;let active=true;void (async()=>{try{const result=await agentRequest('/api/wiki','POST',{action:'bootstrap'});if(result.imported)await refresh.current();if(active){const status=await agentRequest('/api/integrations');setConnections(status.connections);await sync()}}catch(e){if(active)setError((e as Error).message)}finally{if(active)setLoading(false)}})();const timer=setInterval(()=>{if(document.visibilityState==='visible')void sync()},60000);return()=>{active=false;clearInterval(timer)}},[demo]);
 const wiki=data.notes.filter(n=>n.kind==='wiki'),active=wiki.find(n=>n.id===selected),q=normalize(query);
 const filtered=wiki.filter(n=>!q||normalize(`${n.title} ${n.summary} ${n.wiki?.aliases.join(' ')??''}`).includes(q));
 const graph=useMemo(()=>wikiGraph(data,selected||undefined),[data,selected]);
 const placed=useMemo(()=>layoutGraph(graph.nodes,graph.edges,180),[graph]);
 const points=new Map(placed.map(n=>[n.id,n]));
 const bounds=placed.length?{x:Math.min(...placed.map(n=>n.x))-100,y:Math.min(...placed.map(n=>n.y))-70,w:Math.max(...placed.map(n=>n.x))-Math.min(...placed.map(n=>n.x))+200,h:Math.max(...placed.map(n=>n.y))-Math.min(...placed.map(n=>n.y))+140}:{x:-200,y:-200,w:400,h:400};
 const related=useMemo(()=>wikiConnections(data),[data]);
 return <section className="wiki-surface">
  <div className="wiki-toolbar"><label className="search-box"><Search size={17}/><input aria-label="모든 기록 검색" value={query} maxLength={200} onChange={e=>{setQuery(e.target.value);setMode('search')}} placeholder="제목·본문·태그 검색"/></label><DropdownMenu><DropdownMenuTrigger asChild><button className="secondary-button">보기·관리</button></DropdownMenuTrigger><DropdownMenuContent align="end"><DropdownMenuItem onSelect={()=>setMode('search')}>전체 기록 목록</DropdownMenuItem><DropdownMenuItem onSelect={()=>setMode('graph')}>위키 관계 그래프</DropdownMenuItem><DropdownMenuItem onSelect={()=>setMode('list')}>위키 문서 모아보기</DropdownMenuItem><DropdownMenuItem disabled={syncing||loading||busy||demo} onSelect={()=>void sync()}>새 정보 확인</DropdownMenuItem><DropdownMenuItem disabled={demo} onSelect={()=>setConnecting(true)}>연결 관리</DropdownMenuItem></DropdownMenuContent></DropdownMenu></div>
  {query.trim()&&<button className="text-button" disabled={demo} onClick={()=>onAsk('개인 위키·회의록·참고 자료에서 다음 질문과 관련된 원문을 찾아 줘. 실제 읽은 문서의 제목·버전·근거를 보여 줘. 조회 조건: '+JSON.stringify({projectId:projectId||null,kind:documentKind||null,tag:tag||null})+' / 질문: '+query)}>Orbit에게 관련 내용 찾기</button>}
  {loading&&<p role="status"><LoaderCircle size={16} className="animate-spin"/>기록을 불러오는 중…</p>}
  {error&&<p className="brief-alert" role="alert">{error}<button className="text-button" onClick={()=>location.reload()}>다시 불러오기</button></p>}
  {message&&<p className="form-hint" role="status">{message}</p>}
  {mode==='search'?<div className="phase2-panel"><details className="record-filters"><summary>필터{(projectId||tag||documentKind)?' · 적용 중':''}</summary><div className="phase2-toolbar"><label>프로젝트<select className="form-field" value={projectId} onChange={e=>setProjectId(e.target.value)}><option value="">전체</option>{data.projects.map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select></label><label>분류<select className="form-field" value={documentKind} onChange={e=>setDocumentKind(e.target.value)}><option value="">모든 기록</option><option value="wiki">개인 위키</option><option value="meeting">회의록</option><option value="knowledge">참고 자료</option></select></label><label>태그<select className="form-field" value={tag} onChange={e=>setTag(e.target.value)}><option value="">전체</option>{[...new Set(data.notes.flatMap(n=>n.tags))].sort().map(t=><option key={t}>{t}</option>)}</select></label></div></details><div id="orbit-meeting-slot" className="meeting-slot"/><NoteLibrary notes={data.notes} kind="all" query={query} revision={revision} demo={demo} projectId={projectId} tag={tag} documentKind={documentKind} onSelect={id=>onOpen('note',id)} onRefresh={onRefresh}/></div>:<div className="wiki-layout"><aside className="wiki-directory"><button className="text-button" onClick={()=>{setSelected('');setZoom(1)}}>전체 연결 보기</button>{filtered.map(n=><button key={n.id} className={selected===n.id?'is-selected':''} onClick={()=>{setSelected(n.id);setZoom(1)}}><small>{n.wiki?.order??'문서'}</small><span>{n.title}</span>{(n.wiki?.private||n.wiki?.confidential)&&<small>{n.wiki.private?'개인':'기밀'}</small>}</button>)}{!filtered.length&&<p>일치하는 위키가 없습니다.</p>}</aside>
   <div className="wiki-main">{mode==='graph'?<><div className="wiki-graph-controls"><span>{active?active.title+' 주변 연결':'개인 위키 연결 지도'}</span><button className="text-button" onClick={()=>setZoom(z=>Math.min(3,z+.25))} aria-label="위키 그래프 확대">＋</button><button className="text-button" onClick={()=>setZoom(z=>Math.max(.5,z-.25))} aria-label="위키 그래프 축소">－</button><button className="text-button" onClick={()=>{setSelected('');setZoom(1)}}>전체</button></div><div className="wiki-graph-scroll"><svg className="wiki-canvas" viewBox={`${bounds.x} ${bounds.y} ${bounds.w} ${bounds.h}`} style={{width:`${zoom*100}%`,minHeight:440*zoom}} aria-label="개인 위키 문서 연결 그래프" role="group">{graph.edges.map((e,i)=>{const a=points.get(e.a)!,b=points.get(e.b)!;return <line key={i} x1={a.x} y1={a.y} x2={b.x} y2={b.y} stroke={e.kind==='member'?'#9e91da':'#dde0ef'} strokeWidth={e.kind==='member'?1.8:.7}/>})}{placed.map(n=><g key={n.id} role="button" tabIndex={0} aria-label={n.label} transform={`translate(${n.x} ${n.y})`} style={{cursor:'pointer',opacity:q&&!normalize(n.label).includes(q)?.18:1}} onClick={()=>{if(n.recordKind)onOpen(n.recordKind,n.refId);else{setSelected(n.refId);setZoom(1)}}} onKeyDown={e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();if(n.recordKind)onOpen(n.recordKind,n.refId);else setSelected(n.refId)}}}><title>{n.label}</title><circle r={n.r} fill={n.color}/><text y={n.r+16} textAnchor="middle" fontSize={14} fill="#414a65">{n.label.length>14?n.label.slice(0,14)+'…':n.label}</text></g>)}</svg></div><p className="form-hint">굵은 선: 상위·하위 문서 · 가는 선: 위키링크 · 초록 노드: 새로 연결된 기록 · 문서를 누르면 주변 연결과 관련 기록을 확인합니다.</p></>:<div className="wiki-cards">{filtered.map(n=><button key={n.id} className="link-card" onClick={()=>onOpen('note',n.id)}><BookOpen size={18}/><span><strong>{n.title}</strong><p>{n.summary}</p></span></button>)}</div>}
    {active?<><div className="wiki-selected"><div><h2>{active.title}</h2><p>{active.summary}</p><small>별칭: {active.wiki?.aliases.join(' · ')||'없음'} · 원문 출처 {active.wiki?.sources.join(' · ')||'직접 작성'}</small></div><button className="primary-button" onClick={()=>onOpen('note',active.id)}>문서 열기 <ArrowUpRight size={16}/></button></div><WikiRelated data={data} note={active} onOpen={onOpen}/></>:<p className="form-hint">문서를 선택하면 관련 회의록·일정·메일·할 일을 함께 볼 수 있습니다. 연결된 기록 {related.length}건. 새 기록은 자동 연결하며, 본문 종합은 Hermes 대화에서 요청해 승인합니다.</p>}
   </div>
  </div>
  }
  {connecting&&<Connections connections={connections} onClose={()=>setConnecting(false)} onChange={async()=>{setConnections((await agentRequest('/api/integrations')).connections)}}/>}
 </section>;
}
export function WikiRelated({data,note,onOpen}:{data:WorkspaceData;note:Note;onOpen:(kind:'note'|'task'|'event',id:string)=>void}){
 const related=wikiConnections(data).filter(c=>c.wikiId===note.id),out=wikiLinks(note,data.notes),back=data.notes.filter(n=>n.id!==note.id&&(wikiLinks(n,data.notes).includes(note.id)||n.wiki?.parentId===note.id));
 return <section className="wiki-related"><h3>연결된 위키</h3><div className="wiki-link-chips">{[...new Set([...out,...back.map(n=>n.id),...(note.wiki?.parentId?[note.wiki.parentId]:[])])].map(id=>{const n=data.notes.find(n=>n.id===id);return n?<button key={id} className="secondary-button" onClick={()=>onOpen('note',id)}>{n.title}</button>:null})}</div><h3>새 정보와 연결된 기록 · {related.length}</h3><p className="form-hint">이름·별칭이 일치하는 출처입니다. 일정의 존재나 키워드 일치가 결정·완료 사실을 뜻하지는 않습니다.</p>{related.map(c=><button className="link-card" key={c.kind+c.id} onClick={()=>onOpen(c.kind,c.id)}><span><strong>{c.title}</strong><small>{c.source} · {c.date}{c.revision?` · v${c.revision}`:''} · {c.reason}</small></span><ArrowUpRight size={16}/></button>)}{!related.length&&<p className="muted">회의록·메일·일정이 들어오면 이 문서의 이름과 별칭으로 연결합니다.</p>}</section>;
}
