'use client';
import {useEffect,useMemo,useRef,useState} from 'react';
import {BookOpen,Network,RefreshCw,Link2,LoaderCircle,Search,ArrowUpRight} from 'lucide-react';
import {Connections,agentRequest} from '../agent/connections';
import type {Connection} from '@/lib/orbit/agent/types';
import type {Note,WorkspaceData} from '@/lib/orbit/model';
import {wikiGraph,wikiConnections,wikiLinks} from '@/lib/orbit/wiki/relations';
import {layoutGraph} from '@/lib/orbit/graph';
import {normalize} from '@/lib/orbit/classify';
export function WikiLibrary({data,demo,busy,onRefresh,onOpen}:{data:WorkspaceData;demo:boolean;busy:boolean;onRefresh:()=>Promise<void>;onOpen:(kind:'note'|'task'|'event',id:string)=>void}){
 const [mode,setMode]=useState<'graph'|'list'>('graph'),[selected,setSelected]=useState(''),[query,setQuery]=useState(''),[loading,setLoading]=useState(!demo),[syncing,setSyncing]=useState(false),[message,setMessage]=useState(''),[error,setError]=useState(''),[connecting,setConnecting]=useState(false),[connections,setConnections]=useState<Connection[]>([]),[zoom,setZoom]=useState(1);
 const refresh=useRef(onRefresh);refresh.current=onRefresh;const lock=useRef(false),busyRef=useRef(busy);busyRef.current=busy;
 async function sync(){if(demo||lock.current||busyRef.current)return;lock.current=true;setSyncing(true);setError('');try{const result=await agentRequest('/api/wiki','POST',{action:'sync'});setMessage(result.warnings?.length?result.warnings.join(' / '):result.mail?.connected?`메일 ${result.mail.count}개 추가 · ${result.mail.more?'최근 30일 기록을 계속 가져오는 중':'최근 수집 완료'}`:'일정 확인 완료 · Gmail을 연결하면 메일도 수집합니다.');await refresh.current()}catch(e){setError((e as Error).message)}finally{lock.current=false;setSyncing(false)}}
 useEffect(()=>{if(demo)return;let active=true;void (async()=>{try{const result=await agentRequest('/api/wiki','POST',{action:'bootstrap'});if(result.imported)await refresh.current();if(active){const status=await agentRequest('/api/integrations');setConnections(status.connections);await sync()}}catch(e){if(active)setError((e as Error).message)}finally{if(active)setLoading(false)}})();const timer=setInterval(()=>{if(document.visibilityState==='visible')void sync()},60000);return()=>{active=false;clearInterval(timer)}},[demo]);
 const wiki=data.notes.filter(n=>n.kind==='wiki'),active=wiki.find(n=>n.id===selected),q=normalize(query);
 const filtered=wiki.filter(n=>!q||normalize(`${n.title} ${n.summary} ${n.wiki?.aliases.join(' ')??''}`).includes(q));
 const graph=useMemo(()=>wikiGraph(data,selected||undefined),[data,selected]);
 const placed=useMemo(()=>layoutGraph(graph.nodes,graph.edges,180),[graph]);
 const points=new Map(placed.map(n=>[n.id,n]));
 const bounds=placed.length?{x:Math.min(...placed.map(n=>n.x))-100,y:Math.min(...placed.map(n=>n.y))-70,w:Math.max(...placed.map(n=>n.x))-Math.min(...placed.map(n=>n.x))+200,h:Math.max(...placed.map(n=>n.y))-Math.min(...placed.map(n=>n.y))+140}:{x:-200,y:-200,w:400,h:400};
 const related=useMemo(()=>wikiConnections(data),[data]);
 return <section className="wiki-surface">
  <div className="wiki-toolbar"><div className="mode-toggle" role="group" aria-label="개인 위키 보기"><button className={mode==='graph'?'is-active':''} onClick={()=>setMode('graph')}><Network size={16}/>그래프</button><button className={mode==='list'?'is-active':''} onClick={()=>setMode('list')}><BookOpen size={16}/>문서 {wiki.length}</button></div><label className="search-box"><Search size={16}/><input aria-label="위키 이름과 별칭 검색" value={query} onChange={e=>setQuery(e.target.value)} placeholder="이름·별칭·내용 검색"/></label><button className="secondary-button" disabled={syncing||loading||busy||demo} onClick={()=>void sync()}><RefreshCw size={16}/>{syncing?'수집 중':'새 정보 확인'}</button><button className="secondary-button" disabled={demo} onClick={()=>setConnecting(true)}><Link2 size={16}/>연결</button></div>
  {loading&&<p role="status"><LoaderCircle size={16} className="animate-spin"/>첨부한 위키트리를 내 기록으로 가져오고 있습니다.</p>}
  {error&&<p className="brief-alert" role="alert">{error}<button className="text-button" onClick={()=>location.reload()}>다시 불러오기</button></p>}
  {message&&<p className="form-hint" role="status">{message}</p>}
  <div className="wiki-layout"><aside className="wiki-directory"><button className="text-button" onClick={()=>{setSelected('');setZoom(1)}}>전체 연결 보기</button>{filtered.map(n=><button key={n.id} className={selected===n.id?'is-selected':''} onClick={()=>{setSelected(n.id);setZoom(1)}}><small>{n.wiki?.order??'문서'}</small><span>{n.title}</span>{(n.wiki?.private||n.wiki?.confidential)&&<small>{n.wiki.private?'개인':'기밀'}</small>}</button>)}{!filtered.length&&<p>일치하는 위키가 없습니다.</p>}</aside>
   <div className="wiki-main">{mode==='graph'?<><div className="wiki-graph-controls"><span>{active?active.title+' 주변 연결':'개인 위키 연결 지도'}</span><button className="text-button" onClick={()=>setZoom(z=>Math.min(3,z+.25))} aria-label="위키 그래프 확대">＋</button><button className="text-button" onClick={()=>setZoom(z=>Math.max(.5,z-.25))} aria-label="위키 그래프 축소">－</button><button className="text-button" onClick={()=>{setSelected('');setZoom(1)}}>전체</button></div><div className="wiki-graph-scroll"><svg className="wiki-canvas" viewBox={`${bounds.x} ${bounds.y} ${bounds.w} ${bounds.h}`} style={{width:`${zoom*100}%`,minHeight:440*zoom}} aria-label="개인 위키 문서 연결 그래프" role="group">{graph.edges.map((e,i)=>{const a=points.get(e.a)!,b=points.get(e.b)!;return <line key={i} x1={a.x} y1={a.y} x2={b.x} y2={b.y} stroke={e.kind==='member'?'#9e91da':'#dde0ef'} strokeWidth={e.kind==='member'?1.8:.7}/>})}{placed.map(n=><g key={n.id} role="button" tabIndex={0} aria-label={n.label} transform={`translate(${n.x} ${n.y})`} style={{cursor:'pointer',opacity:q&&!normalize(n.label).includes(q)?.18:1}} onClick={()=>{if(n.recordKind)onOpen(n.recordKind,n.refId);else{setSelected(n.refId);setZoom(1)}}} onKeyDown={e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();if(n.recordKind)onOpen(n.recordKind,n.refId);else setSelected(n.refId)}}}><title>{n.label}</title><circle r={n.r} fill={n.color}/><text y={n.r+16} textAnchor="middle" fontSize={14} fill="#414a65">{n.label.length>14?n.label.slice(0,14)+'…':n.label}</text></g>)}</svg></div><p className="form-hint">굵은 선: 상위·하위 문서 · 가는 선: 위키링크 · 초록 노드: 새로 연결된 기록 · 문서를 누르면 주변 연결과 관련 기록을 확인합니다.</p></>:<div className="wiki-cards">{filtered.map(n=><button key={n.id} className="link-card" onClick={()=>onOpen('note',n.id)}><BookOpen size={18}/><span><strong>{n.title}</strong><p>{n.summary}</p></span></button>)}</div>}
    {active?<><div className="wiki-selected"><div><h2>{active.title}</h2><p>{active.summary}</p><small>별칭: {active.wiki?.aliases.join(' · ')||'없음'} · 원문 출처 {active.wiki?.sources.join(' · ')||'직접 작성'}</small></div><button className="primary-button" onClick={()=>onOpen('note',active.id)}>문서 열기 <ArrowUpRight size={16}/></button></div><WikiRelated data={data} note={active} onOpen={onOpen}/></>:<p className="form-hint">문서를 선택하면 관련 회의록·일정·메일·할 일을 함께 볼 수 있습니다. 연결된 기록 {related.length}건. 새 기록은 자동 연결하며, 본문 종합은 Hermes 대화에서 요청해 승인합니다.</p>}
   </div>
  </div>
  {connecting&&<Connections connections={connections} onClose={()=>setConnecting(false)} onChange={async()=>{setConnections((await agentRequest('/api/integrations')).connections)}}/>}
 </section>;
}
export function WikiRelated({data,note,onOpen}:{data:WorkspaceData;note:Note;onOpen:(kind:'note'|'task'|'event',id:string)=>void}){
 const related=wikiConnections(data).filter(c=>c.wikiId===note.id),out=wikiLinks(note,data.notes),back=data.notes.filter(n=>n.id!==note.id&&(wikiLinks(n,data.notes).includes(note.id)||n.wiki?.parentId===note.id));
 return <section className="wiki-related"><h3>연결된 위키</h3><div className="wiki-link-chips">{[...new Set([...out,...back.map(n=>n.id),...(note.wiki?.parentId?[note.wiki.parentId]:[])])].map(id=>{const n=data.notes.find(n=>n.id===id);return n?<button key={id} className="secondary-button" onClick={()=>onOpen('note',id)}>{n.title}</button>:null})}</div><h3>새 정보와 연결된 기록 · {related.length}</h3><p className="form-hint">이름·별칭이 일치하는 출처입니다. 일정의 존재나 키워드 일치가 결정·완료 사실을 뜻하지는 않습니다.</p>{related.map(c=><button className="link-card" key={c.kind+c.id} onClick={()=>onOpen(c.kind,c.id)}><span><strong>{c.title}</strong><small>{c.source} · {c.date}{c.revision?` · v${c.revision}`:''} · {c.reason}</small></span><ArrowUpRight size={16}/></button>)}{!related.length&&<p className="muted">회의록·메일·일정이 들어오면 이 문서의 이름과 별칭으로 연결합니다.</p>}</section>;
}
