import {MAX_PREVIEW_BYTES} from './types';
export interface PreparedFile {preview?:Blob;text:string;label:string}
async function jpeg(canvas:HTMLCanvasElement){let quality=.86;let blob:Blob|null=null;for(let i=0;i<5;i++){blob=await new Promise(r=>canvas.toBlob(r,'image/jpeg',quality));if(blob&&blob.size<=MAX_PREVIEW_BYTES)return blob;quality-=.14;}return undefined}
function canvasFor(width:number,height:number){const scale=Math.min(1,1600/Math.max(width,height));const canvas=document.createElement('canvas');canvas.width=Math.max(1,Math.round(width*scale));canvas.height=Math.max(1,Math.round(height*scale));return canvas}
async function image(file:File):Promise<PreparedFile>{const bitmap=await createImageBitmap(file);try{const canvas=canvasFor(bitmap.width,bitmap.height);canvas.getContext('2d')!.drawImage(bitmap,0,0,canvas.width,canvas.height);const preview=await jpeg(canvas);return {preview,text:'',label:preview?'이미지 미리보기 · 원본 별도 보관':'원본 저장 · 이미지 미리보기를 만들지 못했습니다'}}finally{bitmap.close()}}
async function video(file:File):Promise<PreparedFile>{const element=document.createElement('video'),url=URL.createObjectURL(file);element.preload='auto';element.muted=true;element.playsInline=true;try{await new Promise<void>((resolve,reject)=>{const timer=setTimeout(()=>reject(new Error('video timeout')),12000);element.onerror=()=>{clearTimeout(timer);reject(new Error('video format'))};element.onloadeddata=()=>{clearTimeout(timer);resolve()};element.src=url;});const canvas=canvasFor(element.videoWidth,element.videoHeight);canvas.getContext('2d')!.drawImage(element,0,0,canvas.width,canvas.height);const preview=await jpeg(canvas);return {preview,text:'',label:preview?'영상 첫 프레임만 AI에 전달 · 음성·전체 영상 분석 제외':'원본 저장 · 영상 미리보기를 만들지 못했습니다'}}finally{element.removeAttribute('src');element.load();URL.revokeObjectURL(url)}}
async function pdf(file:File):Promise<PreparedFile>{const lib=await import('pdfjs-dist'),worker=await import('pdfjs-dist/build/pdf.worker.min.mjs?url');lib.GlobalWorkerOptions.workerSrc=worker.default;const loading=lib.getDocument({data:new Uint8Array(await file.arrayBuffer()),useSystemFonts:true});const timeout=setTimeout(()=>void loading.destroy(),25000);try{const doc=await loading.promise;let text='',pages=0;for(let n=1;n<=Math.min(doc.numPages,30)&&text.length<12000;n++){const page=await doc.getPage(n),content=await page.getTextContent();text+=`\n[${n}쪽]\n`+content.items.map(i=>'str' in i?i.str:'').join(' ');pages++;page.cleanup();}const first=await doc.getPage(1),viewport=first.getViewport({scale:1}),canvas=canvasFor(viewport.width*2,viewport.height*2),renderViewport=first.getViewport({scale:canvas.width/viewport.width});await first.render({canvas,viewport:renderViewport}).promise;const preview=await jpeg(canvas);return {preview,text:text.slice(0,12000),label:`PDF ${pages}/${doc.numPages}쪽 텍스트 · 첫 페이지 이미지${text.length>=12000?' · 텍스트 일부':''}`}}finally{clearTimeout(timeout);await loading.destroy()}}
function xml(bytes:Uint8Array){return new DOMParser().parseFromString(new TextDecoder().decode(bytes),'application/xml')}
function textNodes(doc:Document,name:string){return Array.from(doc.getElementsByTagName(name)).map(n=>n.textContent??'')}
async function office(file:File,ext:string):Promise<PreparedFile>{const {unzip}=await import('fflate');let expanded=0;const entries=await new Promise<Record<string,Uint8Array>>((resolve,reject)=>{void file.arrayBuffer().then(buffer=>unzip(new Uint8Array(buffer),{filter:item=>{if(!/^(word\/document\.xml|ppt\/slides\/slide\d+\.xml|xl\/(sharedStrings\.xml|worksheets\/sheet\d+\.xml))$/.test(item.name))return false;expanded+=item.originalSize;return item.originalSize<2000000&&expanded<6000000}},(error,result)=>error?reject(error):resolve(result))).catch(reject)});let text='';for(const name of Object.keys(entries).sort((a,b)=>a.localeCompare(b,undefined,{numeric:true}))){const doc=xml(entries[name]);if(name==='xl/sharedStrings.xml')continue;if(ext==='xlsx'){const strings=entries['xl/sharedStrings.xml']?textNodes(xml(entries['xl/sharedStrings.xml']),'si'):[];text+='\n['+name+']\n'+Array.from(doc.getElementsByTagName('row')).map(row=>Array.from(row.getElementsByTagName('c')).map(cell=>{const value=cell.getElementsByTagName('v')[0]?.textContent??cell.getElementsByTagName('t')[0]?.textContent??'';return cell.getAttribute('t')==='s'?(strings[Number(value)]??''):value}).join('\t')).join('\n')}else text+='\n['+name+']\n'+textNodes(doc,ext==='docx'?'w:p':'a:t').join('\n');if(text.length>12000)break;}return {text:text.slice(0,12000),label:text.trim()?`문서 텍스트${text.length>12000?' 일부 (12,000자)':''} · 표·배치·수식은 원본 확인`:'원본 저장 · 텍스트를 추출하지 못했습니다'}}
export async function prepareFile(file:File):Promise<PreparedFile>{const ext=file.name.split('.').pop()!.toLowerCase();try{if(['jpg','jpeg','png','webp','gif','heic','heif'].includes(ext))return await image(file);if(['mp4','mov','webm','mkv'].includes(ext))return await video(file);if(ext==='pdf')return await pdf(file);if(['docx','xlsx','pptx'].includes(ext))return await office(file,ext);if(['txt','md','csv'].includes(ext)){const text=await file.slice(0,100000).text();return {text:text.slice(0,12000),label:text.length>12000||file.size>100000?'텍스트 일부 (최대 12,000자)':'텍스트 내용'}}}catch{}return {text:'',label:'원본 저장 · 이 형식의 AI 내용 분석은 지원하지 않습니다'}}
