import {z} from 'zod';
import type {Database} from '../../../db/repository.ts';
import {AgentError} from '../agent/errors.ts';
import {fileTypes,MAX_FILES,MAX_FILE_BYTES,MAX_DOCUMENT_BYTES,MAX_PREVIEW_BYTES,type StoredAttachment} from './types.ts';
export interface BucketObject {size:number;body:ReadableStream<Uint8Array>;arrayBuffer():Promise<ArrayBuffer>}
export interface Bucket {put(key:string,value:ReadableStream<Uint8Array>|ArrayBuffer|Uint8Array,options?:{httpMetadata?:{contentType:string}}):Promise<{size:number}|null>;get(key:string,options?:{range?:{offset:number;length:number}}):Promise<BucketObject|null>;delete(key:string):Promise<void>}
export const fileIds=z.array(z.string().uuid()).max(MAX_FILES).refine(ids=>new Set(ids).size===ids.length);
export const uploadSchema=z.object({id:z.string().uuid(),name:z.string().trim().min(1).max(200),size:z.number().int().min(1).max(MAX_FILE_BYTES)}).strict();
interface Row {prepared:number;owner_id:string;id:string;name:string;mime:string;size:number;state:StoredAttachment['state'];object_key:string|null;lease:string|null;lease_until:number;preview_key:string|null;context_text:string;context_label:string;target_type:StoredAttachment['targetType'];target_id:string|null;created_at:string;updated_at:string}
export const publicFile=(r:Row):StoredAttachment=>({id:r.id,name:r.name,mime:r.mime,size:r.size,prepared:!!r.prepared,state:r.state,preview:!!r.preview_key,contextLabel:r.context_label,targetType:r.target_type,targetId:r.target_id,createdAt:r.created_at});
export async function findFile(db:Database,owner:string,id:string){const row=await db.prepare('SELECT * FROM orbit_attachments WHERE owner_id=? AND id=?').bind(owner,id).first<Row>();if(!row)throw new AgentError('파일을 찾을 수 없습니다.','NOT_FOUND',404);return row}
export async function prepareUpload(db:Database,owner:string,input:z.infer<typeof uploadSchema>){
 const ext=input.name.split('.').pop()!.toLowerCase(),mime=fileTypes[ext];if(!mime||/[\u0000-\u001f\u007f/\\]/.test(input.name))throw new AgentError('이미지·영상·PDF·Office·텍스트 파일을 선택해 주세요.','FILE_TYPE',415);
 if(!mime.startsWith('video/')&&input.size>MAX_DOCUMENT_BYTES)throw new AgentError('이미지와 문서는 파일당 25 MB까지 첨부할 수 있습니다.','FILE_SIZE',413);
 const now=new Date().toISOString();await db.prepare("INSERT INTO orbit_attachments(owner_id,id,name,mime,size,state,created_at,updated_at) VALUES(?,?,?,?,?,'pending',?,?) ON CONFLICT(owner_id,id) DO NOTHING").bind(owner,input.id,input.name,mime,input.size,now,now).run();const row=await findFile(db,owner,input.id);if(row.name!==input.name||row.size!==input.size)throw new AgentError('다른 파일에 사용한 업로드 번호입니다.','CONFLICT',409);return publicFile(row);
}
export async function uploadContent(db:Database,bucket:Bucket,owner:string,id:string,request:Request){
 const row=await findFile(db,owner,id);if(row.state==='ready')return publicFile(row);if(!request.body)throw new AgentError('파일 내용이 없습니다.');
 const length=request.headers.get('content-length');if(!length||Number(length)!==row.size)throw new AgentError('파일 크기가 맞지 않습니다. 파일을 다시 선택해 주세요.','FILE_SIZE',413);
 const lease=crypto.randomUUID(),now=Date.now();const claim=await db.prepare("UPDATE orbit_attachments SET state='uploading',lease=?,lease_until=? WHERE owner_id=? AND id=? AND state<>'ready' AND lease_until<? AND target_id IS NULL").bind(lease,now+300000,owner,id,now).run();if(claim.meta?.changes!==1)throw new AgentError('이 파일을 업로드 중입니다. 잠시 후 다시 시도해 주세요.','BUSY',409);
 const key='uploads/'+id+'/'+lease;
 try{const result=await bucket.put(key,request.body,{httpMetadata:{contentType:row.mime}});if(!result||result.size!==row.size)throw new AgentError('파일 전송이 끝나지 않았습니다. 다시 시도해 주세요.','UPLOAD',422);const saved=await db.prepare("UPDATE orbit_attachments SET state='ready',object_key=?,lease=NULL,lease_until=0,updated_at=? WHERE owner_id=? AND id=? AND lease=?").bind(key,new Date().toISOString(),owner,id,lease).run();if(saved.meta?.changes!==1){await bucket.delete(key);throw new AgentError('업로드 상태가 변경됐습니다. 다시 확인해 주세요.','CONFLICT',409)}return publicFile(await findFile(db,owner,id)); }catch(e){
  // A failed acknowledgement can follow a committed ready pointer. Never
  // delete bytes until D1 positively confirms that they are unreferenced.
  const current=await findFile(db,owner,id).catch(()=>null);
  if(current?.state==='ready'&&current.object_key===key)return publicFile(current);
  if(current){if(current.lease===lease){const reset=await db.prepare("UPDATE orbit_attachments SET state='pending',lease=NULL,lease_until=0 WHERE owner_id=? AND id=? AND lease=? AND object_key IS NULL").bind(owner,id,lease).run();if(reset.meta?.changes===1)await bucket.delete(key).catch(()=>{});}else if(current.object_key!==key)await bucket.delete(key).catch(()=>{});}
  throw e;
 }
}
export async function listFiles(db:Database,owner:string,target?:{type:'turn'|'event';id:string}){const {results}=await db.prepare(`SELECT * FROM orbit_attachments WHERE owner_id=? AND state='ready' AND prepared=1 AND ${target?'target_type=? AND target_id=?':'target_id IS NULL'} ORDER BY created_at DESC,id DESC LIMIT 100`).bind(owner,...(target?[target.type,target.id]:[])).all<Row>();return results.map(publicFile)}
export async function filesByIds(db:Database,owner:string,ids:string[]){if(!ids.length)return [];const {results}=await db.prepare(`SELECT * FROM orbit_attachments WHERE owner_id=? AND state='ready' AND prepared=1 AND id IN (${ids.map(()=>'?').join(',')})`).bind(owner,...ids).all<Row>();if(results.length!==ids.length)throw new AgentError('업로드가 끝난 내 파일을 선택해 주세요.','ATTACHMENTS',409);return ids.map(id=>results.find(r=>r.id===id)!)}
// Attachment ownership and an unbound/same-target state are checked inside the
// same winning transaction as the turn/event, never as a client-side promise.
export function attachmentGate(ids:string[]){return ids.length?`(SELECT COUNT(*) FROM orbit_attachments WHERE owner_id=? AND id IN (${ids.map(()=>'?').join(',')}) AND state='ready' AND prepared=1 AND (target_id IS NULL OR (target_type=? AND target_id=?)))=?`:'1'}
export function attachmentGateValues(owner:string,ids:string[],type:string,id:string){return ids.length?[owner,...ids,type,id,ids.length]:[]}
export function bindFiles(db:Database,owner:string,ids:string[],type:'turn'|'event',id:string,gate:string,values:(string|number|null)[]){return ids.map(fileId=>db.prepare(`UPDATE orbit_attachments SET target_type=?,target_id=?,updated_at=? WHERE owner_id=? AND id=? AND ${gate}`).bind(type,id,new Date().toISOString(),owner,fileId,...values))}
export async function putPreview(db:Database,bucket:Bucket,owner:string,id:string,request:Request){const row=await findFile(db,owner,id);if(row.preview_key)return publicFile(row);if(row.state!=='ready'||row.target_id||row.prepared)throw new AgentError('첨부 전의 업로드 파일만 준비할 수 있습니다.','CONFLICT',409);const declared=Number(request.headers.get('content-length'));if(!declared||declared>MAX_PREVIEW_BYTES)throw new AgentError('미리보기가 너무 큽니다.','FILE_SIZE',413);const bytes=await boundedBytes(request,MAX_PREVIEW_BYTES);if(bytes.length!==declared||bytes[0]!==255||bytes[1]!==216||bytes[2]!==255)throw new AgentError('JPEG 미리보기가 필요합니다.','FILE_TYPE',415);const key='previews/'+id+'/'+crypto.randomUUID();await bucket.put(key,bytes,{httpMetadata:{contentType:'image/jpeg'}});const r=await db.prepare('UPDATE orbit_attachments SET preview_key=? WHERE owner_id=? AND id=? AND preview_key IS NULL AND target_id IS NULL AND prepared=0').bind(key,owner,id).run();if(r.meta?.changes!==1)await bucket.delete(key);return publicFile(await findFile(db,owner,id))}
export async function saveContext(db:Database,owner:string,id:string,text:string,label:string){const row=await findFile(db,owner,id);if(row.prepared){if(row.context_text===text&&row.context_label===label)return publicFile(row);throw new AgentError('이미 준비한 첨부파일은 변경하지 않습니다.','CONFLICT',409)}const result=await db.prepare("UPDATE orbit_attachments SET context_text=?,context_label=?,prepared=1 WHERE owner_id=? AND id=? AND target_id IS NULL AND state='ready' AND prepared=0").bind(text,label,owner,id).run();if(result.meta?.changes!==1)throw new AgentError('파일 준비 상태가 변경됐습니다. 다시 확인해 주세요.','CONFLICT',409);return publicFile(await findFile(db,owner,id))}
export async function removeFile(db:Database,bucket:Bucket,owner:string,id:string){const row=await findFile(db,owner,id);if(row.target_id)throw new AgentError('대화나 일정에 보관한 파일은 여기서 지울 수 없습니다.','CONFLICT',409);const result=await db.prepare('DELETE FROM orbit_attachments WHERE owner_id=? AND id=? AND target_id IS NULL AND lease_until<?').bind(owner,id,Date.now()).run();if(result.meta?.changes!==1)throw new AgentError('파일 전송이 끝난 뒤 다시 시도해 주세요.','BUSY',409);if(row.object_key)await bucket.delete(row.object_key);if(row.preview_key)await bucket.delete(row.preview_key)}
export async function contentResponse(db:Database,bucket:Bucket,owner:string,id:string,request:Request,preview=false){
 const row=await findFile(db,owner,id),key=preview?row.preview_key:row.object_key;if(row.state!=='ready'||!key)throw new AgentError('아직 파일이 준비되지 않았습니다.','NOT_FOUND',404);
 let range:{offset:number;length:number}|undefined;if(!preview&&request.headers.has('range')){const match=/^bytes=(\d*)-(\d*)$/.exec(request.headers.get('range')!);if(!match||(!match[1]&&!match[2]))return new Response(null,{status:416,headers:{'Content-Range':'bytes */'+row.size,'Cache-Control':'private, no-store'}});const start=match[1]?Number(match[1]):Math.max(0,row.size-Number(match[2])),end=match[1]?(match[2]?Math.min(Number(match[2]),row.size-1):row.size-1):row.size-1;if(start>end||start>=row.size)return new Response(null,{status:416,headers:{'Content-Range':'bytes */'+row.size,'Cache-Control':'private, no-store'}});range={offset:start,length:end-start+1};}
 const object=await bucket.get(key,range?{range}:undefined);if(!object)throw new AgentError('파일을 불러오지 못했습니다. 다시 시도해 주세요.','STORAGE',503);
 const mime=preview?'image/jpeg':row.mime,inline=preview||mime.startsWith('image/')||mime.startsWith('video/');const headers=new Headers({'Content-Type':mime,'Content-Length':String(range?.length??object.size),'Cache-Control':'private, no-store','Vary':'Cookie','X-Content-Type-Options':'nosniff','Content-Security-Policy':"default-src 'none'; sandbox",'Content-Disposition':(inline?'inline':'attachment')+"; filename*=UTF-8''"+encodeURIComponent(row.name).replace(/'/g,'%27'),'Accept-Ranges':'bytes'});if(range)headers.set('Content-Range',`bytes ${range.offset}-${range.offset+range.length-1}/${row.size}`);return new Response(object.body,{status:range?206:200,headers});
}

export async function filesForTurns(db:Database,owner:string,ids:string[]){if(!ids.length)return [];const {results}=await db.prepare(`SELECT * FROM orbit_attachments WHERE owner_id=? AND target_type='turn' AND target_id IN (${ids.map(()=>'?').join(',')}) ORDER BY created_at,id`).bind(owner,...ids).all<Row>();return results.map(publicFile)}

async function boundedBytes(request:Request,max:number){const reader=request.body?.getReader();if(!reader)throw new AgentError('파일 내용이 없습니다.');const chunks:Uint8Array[]=[];let size=0;try{while(true){const {done,value}=await reader.read();if(done)break;size+=value.length;if(size>max){await reader.cancel();throw new AgentError('미리보기가 너무 큽니다.','FILE_SIZE',413)}chunks.push(value)}}finally{reader.releaseLock()}const bytes=new Uint8Array(size);let offset=0;for(const chunk of chunks){bytes.set(chunk,offset);offset+=chunk.length}return bytes}
