'use client';
import {HistoryRestore} from '../phase4/history-restore';
import {useRef,useState} from 'react';
import {unzipSync,strFromU8} from 'fflate';
import type {WorkspaceSnapshot} from '@/lib/orbit/model';
import {categories,categoryLabels,type Category} from '@/lib/orbit/backup';
import {agentRequest} from '../agent/connections';
export function BackupPanel({snapshot,demo,busy,onRefresh}:{snapshot:WorkspaceSnapshot;demo:boolean;busy:boolean;onRefresh:()=>Promise<void>}){
 const [file,setFile]=useState<any>(null),[selected,setSelected]=useState<{category:Category;id:string}[]>([]),[preview,setPreview]=useState<any>(null),[working,setWorking]=useState(false),[message,setMessage]=useState(''),[error,setError]=useState('');const operation=useRef(crypto.randomUUID()),locked=useRef(false);
 const reset=()=>{setPreview(null);operation.current=crypto.randomUUID()};
 async function download(){const a=document.createElement('a');a.href='/api/backup';a.download='orbit-backup-'+new Date().toISOString().slice(0,10)+'.zip';a.click();setMessage('브라우저에서 백업 다운로드를 시작했습니다. 완료 여부를 다운로드 목록에서 확인하세요.');}
 async function load(f:File){setError('');setMessage('');setFile(null);setSelected([]);reset();try{if(f.size>300*1024*1024)throw Error('300MB보다 큰 ZIP은 압축을 풀고 workspace.json만 선택하세요.');let text:string;if(f.name.toLowerCase().endsWith('.zip')){const files=unzipSync(new Uint8Array(await f.arrayBuffer()),{filter:f=>f.name==='workspace.json'&&f.originalSize<=25000000});if(!files['workspace.json'])throw Error('25MB 이내의 workspace.json이 필요합니다.');text=strFromU8(files['workspace.json']);}else{if(f.size>25000000)throw Error('복원 자료는 25MB 이내여야 합니다.');text=await f.text();}const parsed=JSON.parse(text);if(parsed.payload?.format!=='orbit-backup/v2'||typeof parsed.checksum!=='string')throw Error('이 화면에서 만든 v2 백업을 선택하세요.');setFile(parsed);}catch(e){setError((e as Error).message)}}
 async function request(action:'preview'|'restore'){if(locked.current)return;locked.current=true;setWorking(true);setError('');try{const result=await agentRequest('/api/backup','POST',{action,payload:file.payload,checksum:file.checksum,selection:selected,expectedRevision:action==='preview'?snapshot.revision:preview.revision,operationId:operation.current});if(action==='preview'){setPreview(result);setMessage('서버에서 백업 형식과 연결 관계를 검사했습니다. 아래 목록을 확인하세요.');}else{setMessage(result.replayed?'이 복구 요청은 이미 반영되었습니다.':`${result.inserted}건 복원 · 기존 ${result.kept}건 유지 · 저장된 기록과 원문 재확인 완료`);await onRefresh();setPreview(null);setSelected([]);}}catch(e){setError((e as Error).message)}finally{locked.current=false;setWorking(false)}}
 return <section className="phase2-panel"><article className="phase2-record"><h2>전체 기록 백업</h2><p>현재 기록·문서 변경 이력·회고·대화·실행 이력과 첨부 원본을 ZIP으로 보관합니다. 인증 토큰과 기기 임시 초안은 포함하지 않습니다.</p><button className="primary-button" disabled={demo||busy||working} onClick={()=>void download()}>{working?'처리 중…':'전체 백업 다운로드'}</button></article><article className="phase2-record"><h2>필요한 기록만 복원</h2><p>백업 ZIP 또는 그 안의 workspace.json을 선택하세요. 없는 기록만 추가하며 같은 번호의 기존 기록은 유지합니다. 필요한 프로젝트·목표·원문은 함께 복원합니다.</p><p className="form-hint">대화·실행 결과와 첨부 원본은 아래 별도 복원 영역에서 복구합니다. 먼저 업무 기록을 복원하면 연결을 유지할 수 있습니다.</p><label className="form-label">백업 파일<input type="file" accept=".zip,.json" disabled={demo||busy||working} onChange={e=>{if(e.target.files?.[0])void load(e.target.files[0])}}/></label>{file&&<><p>백업 시각 {new Date(file.payload.capturedAt).toLocaleString('ko-KR')}</p><div className="backup-choices">{categories.map(category=>{const records=Array.isArray(file.payload.data?.[category])?file.payload.data[category]:[];return <details key={category}><summary>{categoryLabels[category]} · {records.length}건</summary><button className="text-button" disabled={working} onClick={()=>{setSelected(s=>[...s.filter(i=>i.category!==category),...records.filter((r:any)=>!String(r.id).startsWith('google:')).map((r:any)=>({category,id:r.id}))]);reset()}}>모두 선택</button><button className="text-button" disabled={working} onClick={()=>{setSelected(s=>s.filter(i=>i.category!==category));reset()}}>선택 해제</button>{records.map((r:any)=><label className="backup-choice" key={r.id}><input type="checkbox" disabled={working||String(r.id).startsWith('google:')} checked={selected.some(s=>s.category===category&&s.id===r.id)} onChange={e=>{setSelected(s=>e.target.checked?[...s,{category,id:r.id}]:s.filter(v=>v.category!==category||v.id!==r.id));reset()}}/>{r.title??r.name??r.sentence??r.rule??r.date??r.id}{(snapshot.data[category]??[]).some(v=>v.id===r.id)&&<small>기존 기록 유지</small>}</label>)}</details>})}</div><button className="secondary-button" disabled={!selected.length||working||busy} onClick={()=>void request('preview')}>선택한 {selected.length}건 복원 미리보기</button></>}{preview&&<div className="phase2-record"><h3>복원 전 확인</h3><p>추가 {preview.inserted.length}건 · 기존 기록 유지 {preview.kept}건 · 필요한 연결 기록 {preview.dependencies}건 포함</p><ul>{preview.inserted.map((i:any)=><li key={i.category+i.id}>{categoryLabels[i.category as Category]} · {file.payload.data[i.category]?.find((r:any)=>r.id===i.id)?.title??file.payload.data[i.category]?.find((r:any)=>r.id===i.id)?.name??i.id}</li>)}</ul><button className="primary-button" disabled={working||busy||!preview.inserted.length} onClick={()=>void request('restore')}>확인한 기록 복원</button></div>}</article><HistoryRestore disabled={demo||busy||working} onRefresh={onRefresh}/>{message&&<p role="status">{message}</p>}{error&&<p role="alert" className="brief-alert">{error}</p>}</section>;
}
