'use client';
import {useState} from 'react';
import type {WorkspaceData,DecisionRecord,DelegationRecord} from '@/lib/orbit/model';
import type {WorkspaceAction} from '@/lib/orbit/validation';
const decisionStatus={active:'유효한 결정',revised:'재검토 중',closed:'검토 완료'};
const delegationStatus={requested:'요청 기록',accepted:'수락 확인',working:'진행 중',blocked:'막힘',delivered:'결과 수신',verified:'검토 완료',cancelled:'취소'};
export function FollowupPanel({data,today,busy,perform,onOpen}:{data:WorkspaceData;today:string;busy:boolean;perform:(a:WorkspaceAction,message?:string)=>Promise<boolean>;onOpen:(kind:'note'|'task',id:string)=>void}){
 const [tab,setTab]=useState<'decisions'|'delegations'>('decisions'),[filter,setFilter]=useState('open'),[project,setProject]=useState(''),[draft,setDraft]=useState<any>(null);
 const list=(tab==='decisions'?data.decisions??[]:data.delegations??[]).filter(r=>(!project||r.projectId===project)&&(filter==='all'||(tab==='decisions'?r.status!=='closed':!['verified','cancelled'].includes(r.status)))&&(filter!=='due'||('reviewDate'in r?r.reviewDate:r.checkDate)<=today)).sort((a,b)=>('reviewDate'in a?a.reviewDate:a.checkDate).localeCompare('reviewDate'in b?b.reviewDate:b.checkDate));
 const create=()=>setDraft(tab==='decisions'?{id:crypto.randomUUID(),title:'',projectId:project||data.projects[0]?.id||'',choice:'',rationale:'',alternatives:'',reviewDate:today,status:'active',outcome:''}:{id:crypto.randomUUID(),title:'',projectId:project||data.projects[0]?.id||'',assignee:'',deliverable:'',due:today,checkDate:today,status:'requested',update:'',evidence:''});
 const field=(key:string,label:string,multiline=false,type='text')=><label className="form-label" key={key}>{label}{multiline?<textarea className="form-field" maxLength={2000} value={draft[key]??''} onChange={e=>setDraft({...draft,[key]:e.target.value})}/>:<input className="form-field" type={type} maxLength={key==='title'?160:100} value={draft[key]??''} onChange={e=>setDraft({...draft,[key]:e.target.value})}/>}</label>;
 return <section className="phase2-panel"><div className="phase2-toolbar"><div className="mode-toggle"><button className={tab==='decisions'?'is-active':''} onClick={()=>{setTab('decisions');setDraft(null)}}>의사결정 장부</button><button className={tab==='delegations'?'is-active':''} onClick={()=>{setTab('delegations');setDraft(null)}}>위임 추적</button></div><button className="primary-button" disabled={busy||!data.projects.length} onClick={create}>새 기록</button></div><p className="form-hint">{tab==='decisions'?'무엇을 왜 결정했는지 남기고, 정한 날짜에 결과를 다시 확인합니다.':'실제로 요청한 업무와 받은 답변을 기록합니다. 여기에서 메시지를 발송하지 않습니다. 연결한 할 일은 대기로 전환합니다. 결과 수신·검토와 할 일 완료는 각각 확인합니다.'}</p>
 <div className="phase2-toolbar"><label>프로젝트 <select className="form-field" value={project} onChange={e=>setProject(e.target.value)}><option value="">전체</option>{data.projects.map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select></label><label>보기 <select className="form-field" value={filter} onChange={e=>setFilter(e.target.value)}><option value="open">진행 중</option><option value="due">오늘 확인할 기록</option><option value="all">완료 포함 전체</option></select></label></div>
 {!data.projects.length&&<p>프로젝트를 먼저 등록하면 결정과 위임을 연결할 수 있습니다.</p>}
 {draft&&<form className="phase2-editor" onSubmit={async e=>{e.preventDefault();const {history,createdAt,updatedAt,...record}=draft;if(await perform({type:tab==='decisions'?'decision.upsert':'delegation.upsert',record,expectedUpdatedAt:updatedAt} as WorkspaceAction,'기록과 변경 이력을 저장했습니다.'))setDraft(null)}}><h2>{tab==='decisions'?'결정 기록':'위임 기록'}</h2>{field('title','제목')}<label className="form-label">프로젝트<select className="form-field" value={draft.projectId} onChange={e=>setDraft({...draft,projectId:e.target.value,taskId:undefined})}>{data.projects.map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select></label>
 {tab==='decisions'?<>{field('choice','결정한 내용',true)}{field('rationale','판단 근거',true)}{field('alternatives','검토한 대안',true)}{field('reviewDate','재검토 날짜',false,'date')}{field('outcome','확인한 결과와 배운 점',true)}</>:<>{field('assignee','담당자')}{field('deliverable','요청한 결과물·완료 기준',true)}<div className="field-grid">{field('due','기한',false,'date')}{field('checkDate','다음 확인 날짜',false,'date')}</div>{field('update','최근 답변·막힌 이유',true)}{field('evidence','받은 결과물·검토 근거',true)}</>}
 <label className="form-label">상태<select className="form-field" value={draft.status} onChange={e=>setDraft({...draft,status:e.target.value})}>{Object.entries(tab==='decisions'?decisionStatus:delegationStatus).map(([k,v])=><option key={k} value={k}>{v}</option>)}</select></label><label className="form-label">연결할 할 일<select className="form-field" value={draft.taskId??''} onChange={e=>setDraft({...draft,taskId:e.target.value||undefined})}><option value="">연결 없음</option>{data.tasks.filter(t=>t.projectId===draft.projectId).map(t=><option key={t.id} value={t.id}>{t.title}</option>)}</select></label><label className="form-label">원문 기록<select className="form-field" value={draft.noteId??''} onChange={e=>setDraft({...draft,noteId:e.target.value||undefined,noteRevision:e.target.value?(data.notes.find(n=>n.id===e.target.value)?.revision??1):undefined})}><option value="">직접 작성</option>{data.notes.map(n=><option key={n.id} value={n.id}>{n.title} · v{n.revision??1}</option>)}</select></label><div className="phase2-toolbar"><button className="primary-button" disabled={busy}>저장</button><button type="button" className="secondary-button" onClick={()=>setDraft(null)}>닫기</button></div></form>}
 <div className="phase2-records">{list.map(record=>{const r=record as Omit<DecisionRecord,'status'|'history'>&Omit<DelegationRecord,'status'|'history'>&{status:string;history:(DecisionRecord['history'][number]|DelegationRecord['history'][number])[]},date=tab==='decisions'?r.reviewDate:r.checkDate,stale=r.noteId&&data.notes.find(n=>n.id===r.noteId)?.revision!==r.noteRevision;return <article className="phase2-record" key={r.id}><div className="phase2-toolbar"><strong>{r.title}</strong><span>{({...decisionStatus,...delegationStatus} as Record<string,string>)[r.status]} · {date<=today?'확인 필요':'다음 확인'} {date}</span></div><p className="muted">{data.projects.find(p=>p.id===r.projectId)?.name}{tab==='delegations'?` · ${r.assignee} · 기한 ${r.due}`:''}</p><p>{tab==='decisions'?r.choice:r.deliverable}</p><p>{tab==='decisions'?r.rationale:r.update}</p>{(r.outcome||r.evidence)&&<p>{r.outcome||r.evidence}</p>}{stale&&<p className="brief-alert">연결한 원문이 변경되었습니다. 판단 근거를 다시 확인하세요.</p>}<div className="phase2-toolbar"><button className="secondary-button" disabled={busy} onClick={()=>setDraft(record)}>검토·수정</button>{r.noteId&&<button className="text-button" onClick={()=>onOpen('note',r.noteId!)}>원문 보기 · 기록 당시 v{r.noteRevision}</button>}{r.taskId&&<button className="text-button" onClick={()=>onOpen('task',r.taskId!)}>연결된 할 일</button>}</div><details><summary>변경 이력 {r.history.length}건</summary>{[...r.history].reverse().map((h,i)=><div className="phase2-history" key={i}><small>{new Date(h.at).toLocaleString('ko-KR')}</small><p>{({...decisionStatus,...delegationStatus} as Record<string,string>)[h.status]}</p>{'choice'in h?<><p>{h.choice}</p><p>근거: {h.rationale}</p><p>대안: {h.alternatives||'기록 없음'}</p><p>결과: {h.outcome||'검토 전'}</p></>:<><p>{h.assignee} · 기한 {h.due} · 확인 {h.checkDate}</p><p>{h.update||'추가 답변 없음'}</p><p>{h.evidence||'결과 수신 전'}</p></>}</div>)}</details></article>})}</div>{!list.length&&<p className="empty-state">이 조건에 해당하는 기록이 없습니다.</p>}</section>;
}
