'use client';
import {useState} from 'react';
import type {WorkspaceData} from '@/lib/orbit/model';
import type {WorkspaceAction} from '@/lib/orbit/validation';
import {calibrationEvidence,calibrate} from '@/lib/orbit/planner';
import {executionSamples} from '@/lib/orbit/phase4';
import {addDays} from '@/lib/orbit/dates';
export function LearningPanel({data,today,busy,perform,onOpen}:{data:WorkspaceData;today:string;busy:boolean;perform:(a:WorkspaceAction,message?:string)=>Promise<boolean>;onOpen:(id:string)=>void}){
 const [selected,setSelected]=useState('');const target=data.tasks.find(t=>t.id===selected)??data.tasks.find(t=>t.status!=='done')??data.tasks[0],e=target?calibrationEvidence(data.tasks,target,today,data.executionHistory):null;
 const since=addDays(today,-30),plans=data.proposals.filter(p=>p.date>=since&&p.date<=today),samples=executionSamples(data,since,today),approved=plans.flatMap(p=>p.items.filter(i=>i.state==='approved').map(i=>({date:p.date,task:data.tasks.find(t=>t.id===i.taskId)}))),measured=approved.map(p=>samples.rows.find(r=>r.taskId===p.task?.id&&r.date===p.date)).filter(Boolean),done=measured.filter(p=>p?.outcome==='done').length;
 const friction=samples.rows.filter(t=>t.reason==='time'&&t.outcome!=='done');const groups=[...new Set(samples.rows.map(r=>r.buffer).filter((x):x is number=>x!==null))].sort().map(buffer=>{const rows=samples.rows.filter(r=>r.buffer===buffer);return {buffer,count:rows.length,done:rows.filter(r=>r.outcome==='done').length,time:rows.filter(r=>r.reason==='time').length}});
 const recommended=Math.min(.5,Math.round((data.preferences.bufferFraction+.1)*10)/10);
 return <section className="phase2-panel"><div className="phase2-metrics"><article><span>최근 30일 승인한 계획</span><strong>{approved.length}건</strong></article><article><span>해당 날짜에 결과를 기록</span><strong>{measured.length}건</strong></article><article><span>기록된 계획의 완료율</span><strong>{measured.length?Math.round(done/measured.length*100)+'%':'측정 전'}</strong></article></div><p className="form-hint">{since}–{today} · 결과를 기록하지 않은 {approved.length-measured.length}건은 성공·실패로 계산하지 않습니다. 같은 업무도 날짜별 결과를 구분하고 같은 날의 정정은 마지막 결과만 계산합니다. 이전 버전의 최신 결과 {samples.legacy.length}건을 보충했으며 당시 설정은 추정하지 않습니다.</p><article className="phase2-record"><h2>내일 제안에 쓰이는 시간 보정</h2><label className="form-label">확인할 업무<select className="form-field" value={target?.id??''} onChange={ev=>setSelected(ev.target.value)}>{data.tasks.map(t=><option key={t.id} value={t.id}>{t.title}</option>)}</select></label>{target&&e?<><p><strong>{target.duration}분 → {calibrate(target.duration,e.factor)}분</strong> · {e.factor}배 · {e.tier}</p><p>{e.samples.length}개 표본 · 최근 30일 완료 업무에서 실제÷예상 시간의 중앙값을 적용합니다. 최소 5개가 있어야 보정하며 범위는 0.5–2배입니다.</p><details><summary>계산에 사용한 기록 보기</summary>{e.samples.map(s=><button className="link-card" key={s.id} onClick={()=>onOpen(s.id)}>{s.title} · {s.date} · 예상 {s.estimate} / 실제 {s.actual}분</button>)}</details></>:<p>할 일을 등록하고 실제 소요시간을 기록하면 계산할 수 있습니다.</p>}</article><article className="phase2-record"><h2>다음 계획에서 바꿔볼 것</h2>{friction.length>=3&&recommended>data.preferences.bufferFraction?<><p>최근 시간 부족 기록이 {friction.length}건입니다. 비워둘 시간을 {Math.round(data.preferences.bufferFraction*100)}%에서 {Math.round(recommended*100)}%로 늘리는 실험을 제안합니다.</p><button className="primary-button" disabled={busy} onClick={()=>void perform({type:'preferences.update',preferences:{...data.preferences,bufferFraction:recommended}},'여유 시간 비율을 변경했습니다. 다음에 생성하는 제안부터 적용됩니다.')}>다음 계획에 적용</button><details><summary>근거 업무</summary>{friction.map(t=><button className="link-card" key={t.id} onClick={()=>onOpen(t.taskId)}>{t.title} · {t.date}</button>)}</details></>:<p>현재 기록만으로 설정을 바꿀 충분한 근거가 없습니다. 실제 소요시간과 미완료 이유를 꾸준히 기록하세요.</p>}</article><article className="phase2-record"><h2>여유 시간 설정별 관측 결과</h2><p className="form-hint">결과 기록 당시 설정을 기준으로 비교합니다. 업무 난이도·표본 차이가 있으므로 설정 변경의 효과를 입증하는 수치는 아닙니다. 이전 기록의 설정은 알 수 없어 제외합니다.</p>{groups.length?<table><thead><tr><th>여유 시간</th><th>표본</th><th>완료율</th><th>시간 부족</th></tr></thead><tbody>{groups.map(g=><tr key={g.buffer}><td>{Math.round(g.buffer*100)}%</td><td>{g.count}건</td><td>{Math.round(g.done/g.count*100)}%</td><td>{g.time}건</td></tr>)}</tbody></table>:<p>새 실행 결과가 쌓이면 설정별 차이를 확인할 수 있습니다.</p>}</article></section>;
}
