import {z} from 'zod';
import {readNote,readWorkspace,writeCommand,type Database} from '../../../db/repository.ts';
import {dateSchema} from '../validation.ts';

const id=z.string().min(1).max(160);
const sourceSchema=z.object({platform:z.literal('slack'),workspaceId:id,requesterId:id,channelId:id,messageTs:z.string().regex(/^\d{10}\.\d{6}$/),threadId:z.string().regex(/^\d{10}\.\d{6}$/).optional(),eventId:id.optional(),clientMsgId:id.optional()}).strict().refine(s=>s.eventId||s.clientMsgId);
const bindingSchema=z.object({contract:z.literal('orbit-slack-v2'),authorized:z.literal(true),ownerId:id,workspaceId:id,requesterId:id,projectId:id}).strict();
const inputSchema=z.object({operationKey:z.string().min(1).max(200),source:sourceSchema,providerStatus:z.enum(['succeeded','failed']),providerError:z.enum(['','provider_failed']),change:z.object({kind:z.literal('note'),title:z.string().min(1).max(160),text:z.string().min(1).max(4000),date:dateSchema}).strict(),project:z.object({id:id.optional(),name:id.optional()}).strict().optional(),binding:bindingSchema.optional()}).strict();
type Input=z.infer<typeof inputSchema>;
type Principal={token_hash:string;owner_id:string;workspace_id:string;requester_id:string};
type Row={id:string;payload_json:string;payload_hash:string;status:string;target_id:string|null;candidates_json:string};
class Failure extends Error {status:number;constructor(status:number,message:string){super(message);this.status=status}}
export async function digest(value:string){return [...new Uint8Array(await crypto.subtle.digest('SHA-256',new TextEncoder().encode(value)))].map(v=>v.toString(16).padStart(2,'0')).join('')}
function canonical(value:unknown):string {if(Array.isArray(value))return '['+value.map(canonical).join(',')+']';if(value!==null&&typeof value==='object')return '{'+Object.keys(value).sort().map(k=>JSON.stringify(k)+':'+canonical((value as Record<string,unknown>)[k])).join(',')+'}';return JSON.stringify(value)}
const authGate="EXISTS(SELECT 1 FROM orbit_slack_credentials WHERE token_hash=? AND owner_id=? AND workspace_id=? AND requester_id=? AND scope='directives:write' AND revoked=0 AND expires_at>?)";
const authValues=(p:Principal)=>[p.token_hash,p.owner_id,p.workspace_id,p.requester_id,Date.now()];
async function authenticate(db:Database,request:Request){const match=/^Bearer ([A-Za-z0-9_-]{32,256})$/.exec(request.headers.get('authorization')??'');if(!match)throw new Failure(401,'unauthorized');const hash=await digest(match[1]);const principal=await db.prepare("SELECT token_hash,owner_id,workspace_id,requester_id FROM orbit_slack_credentials WHERE token_hash=? AND scope='directives:write' AND revoked=0 AND expires_at>?").bind(hash,Date.now()).first<Principal>();if(!principal)throw new Failure(401,'unauthorized');return principal}
const binding=(p:Principal,projectId:string)=>({contract:'orbit-slack-v2' as const,authorized:true as const,ownerId:p.owner_id,workspaceId:p.workspace_id,requesterId:p.requester_id,projectId});
async function lookup(db:Database,p:Principal,field:'id'|'operation_key',value:string){return db.prepare(`SELECT * FROM orbit_slack_directives WHERE owner_id=? AND workspace_id=? AND requester_id=? AND ${field}=?`).bind(p.owner_id,p.workspace_id,p.requester_id,value).first<Row>()}
async function readback(db:Database,p:Principal,row:Row){const wire:Input=JSON.parse(row.payload_json);let target=null,status=row.status;if(row.target_id){try{const note=await readNote(db,p.owner_id,row.target_id);target={type:'note',id:note.id,note:{...note,ownerId:p.owner_id,date:note.updated}};if(note.kind!=='knowledge'||note.projectId!==wire.project?.id||note.title!==wire.change.title||note.body!==wire.change.text||note.updated!==wire.change.date)status='target_changed'}catch{status='target_missing'}}return {...wire,id:row.id,status,candidates:JSON.parse(row.candidates_json),target}}
async function post(db:Database,p:Principal,raw:unknown){const parsed=inputSchema.safeParse(raw);if(!parsed.success)throw new Failure(422,'unsupported_or_invalid_directive');const wire=parsed.data;if(wire.source.workspaceId!==p.workspace_id||wire.source.requesterId!==p.requester_id)throw new Failure(403,'source_scope_mismatch');if(wire.binding&&canonical(wire.binding)!==canonical(binding(p,wire.project?.id??'')))throw new Failure(403,'binding_mismatch');
 const hash=await digest(canonical(wire));const prior=await lookup(db,p,'operation_key',wire.operationKey);if(prior){if(prior.payload_hash!==hash)throw new Failure(409,'payload_conflict');return readback(db,p,prior)}
 const snapshot=await readWorkspace(db,p.owner_id);const project=snapshot.data.projects.find(project=>project.id===wire.project?.id);
 if(wire.project?.id&&!project)throw new Failure(403,'project_not_authorized');
 const status=wire.providerStatus==='failed'?'provider_failed':!project?'needs_confirmation':'completed';
 if(status==='completed'&&!wire.binding)throw new Failure(403,'binding_required');
 const receiptId=crypto.randomUUID(),targetId=status==='completed'?'slack:'+receiptId:null;
 const candidates=!project?snapshot.data.projects.filter(p=>p.status==='active').slice(0,8).map(p=>p.id):[];
 const receipt=(gate:string,values:(string|number|null)[])=>db.prepare(`INSERT INTO orbit_slack_directives(owner_id,workspace_id,requester_id,operation_key,id,payload_hash,payload_json,status,target_id,candidates_json,created_at) SELECT ?,?,?,?,?,?,?,?,?,?,? WHERE ${gate}`).bind(p.owner_id,p.workspace_id,p.requester_id,wire.operationKey,receiptId,hash,JSON.stringify(wire),status,targetId,JSON.stringify(candidates),new Date().toISOString(),...values);
 try{if(targetId&&project){await writeCommand(db,p.owner_id,{operationId:'slack-directive:'+receiptId,expectedRevision:snapshot.revision,action:{type:'note.upsert',note:{id:targetId,kind:'knowledge',title:wire.change.title,body:wire.change.text,projectId:project.id,summary:'',tags:[],updated:wire.change.date}}},new Date(),{gate:authGate,values:authValues(p),statements:(gate,values)=>[receipt(gate,values)]})}else{await db.batch([receipt(authGate,authValues(p))])}}catch(error){const winner=await lookup(db,p,'operation_key',wire.operationKey);if(winner){if(winner.payload_hash!==hash)throw new Failure(409,'payload_conflict');return readback(db,p,winner)}throw error}
 const saved=await lookup(db,p,'operation_key',wire.operationKey);if(!saved)throw new Failure(409,'authorization_or_revision_changed');return readback(db,p,saved);
}
// Integration credentials represent an explicitly provisioned single owner / Slack
// workspace / requester. Posted owner IDs and browser cookies never grant access.
// No provider I/O, task calendar outbox, or filesystem KB writes are performed here.
export async function handleDirective(db:Database,request:Request):Promise<Response>{const respond=(value:unknown,status=200)=>Response.json(value,{status,headers:{'Cache-Control':'private, no-store','Vary':'Authorization'}});try{const p=await authenticate(db,request);const url=new URL(request.url);
 if(request.method==='GET'){if(url.searchParams.has('prepareNote')){
  if(url.searchParams.get('workspaceId')!==p.workspace_id||url.searchParams.get('requesterId')!==p.requester_id)throw new Failure(403,'source_scope_mismatch');
  const projectId=url.searchParams.get('projectId');
  const projects=(await readWorkspace(db,p.owner_id)).data.projects;
  if(projectId&&!projects.some(v=>v.id===projectId))throw new Failure(403,'project_not_authorized');
  const candidates=projects.filter(v=>projectId?v.id===projectId:v.status==='active').slice(0,8).map(v=>({id:v.id,name:v.name}));
  return respond({contract:'orbit-slack-note-prepare-v1',workspaceId:p.workspace_id,requesterId:p.requester_id,candidates,providerWritesAllowed:false});
 }if(url.searchParams.has('resolveProjectId')){const projectId=url.searchParams.get('resolveProjectId')??'';if(url.searchParams.get('workspaceId')!==p.workspace_id||url.searchParams.get('requesterId')!==p.requester_id)throw new Failure(403,'source_scope_mismatch');if(!(await readWorkspace(db,p.owner_id)).data.projects.some(v=>v.id===projectId))throw new Failure(403,'project_not_authorized');return respond(binding(p,projectId))}const field=url.searchParams.has('id')?'id':'operation_key';const value=url.searchParams.get(field==='id'?'id':'operationKey');if(!value||value.length>200)throw new Failure(422,'lookup_required');const row=await lookup(db,p,field,value);if(!row)throw new Failure(404,'not_found');return respond(await readback(db,p,row))}
 if(request.method!=='POST')throw new Failure(405,'method_not_allowed');if(!request.headers.get('content-type')?.startsWith('application/json'))throw new Failure(415,'json_required');const reader=request.body?.getReader();if(!reader)throw new Failure(422,'body_required');let size=0;const chunks:Uint8Array[]=[];while(true){const {done,value}=await reader.read();if(done)break;size+=value.byteLength;if(size>12000){await reader.cancel();throw new Failure(413,'body_too_large')}chunks.push(value)}const bytes=new Uint8Array(size);let offset=0;for(const chunk of chunks){bytes.set(chunk,offset);offset+=chunk.byteLength}let raw:unknown;try{raw=JSON.parse(new TextDecoder().decode(bytes))}catch{throw new Failure(422,'invalid_json')}return respond(await post(db,p,raw));
 }catch(error){return respond({error:error instanceof Failure?error.message:'reconcile_before_retry',providerWritesAllowed:false},error instanceof Failure?error.status:503)}}
