import type {Database} from '@/db/repository';
import {AgentError} from './errors.ts';
import type {Provider} from './types.ts';
const encoder=new TextEncoder();
const encode=(bytes:Uint8Array)=>btoa(String.fromCharCode(...bytes));
const decode=(text:string)=>Uint8Array.from(atob(text),c=>c.charCodeAt(0));
export async function encrypt(value:unknown,secret:string,context:string){if(!secret)throw new AgentError('연결 보관 설정을 먼저 완료해 주세요.','CONFIG',503);const raw=decode(secret);if(raw.length!==32)throw new AgentError('연결 보관 키를 확인해 주세요.','CONFIG',503);const key=await crypto.subtle.importKey('raw',raw,'AES-GCM',false,['encrypt']);const iv=crypto.getRandomValues(new Uint8Array(12));const encrypted=await crypto.subtle.encrypt({name:'AES-GCM',iv,additionalData:encoder.encode(context)},key,encoder.encode(JSON.stringify(value)));return JSON.stringify({v:1,iv:encode(iv),data:encode(new Uint8Array(encrypted))})}
export async function decrypt<T>(payload:string,secret:string,context:string):Promise<T>{const box=JSON.parse(payload);const key=await crypto.subtle.importKey('raw',decode(secret),'AES-GCM',false,['decrypt']);return JSON.parse(new TextDecoder().decode(await crypto.subtle.decrypt({name:'AES-GCM',iv:decode(box.iv),additionalData:encoder.encode(context)},key,decode(box.data))))}
export async function readConnection<T>(db:Database,owner:string,provider:Provider,secret:string):Promise<T|null>{const row=await db.prepare('SELECT secret_json FROM orbit_integrations WHERE owner_id=? AND provider=?').bind(owner,provider).first<{secret_json:string}>();return row?decrypt<T>(row.secret_json,secret,`${owner}:${provider}`):null}
export async function saveConnection(db:Database,owner:string,provider:Provider,value:unknown,publicValue:unknown,secret:string){const encrypted=await encrypt(value,secret,`${owner}:${provider}`);await db.prepare('INSERT INTO orbit_integrations(owner_id,provider,secret_json,public_json,updated_at) VALUES(?,?,?,?,?) ON CONFLICT(owner_id,provider) DO UPDATE SET secret_json=excluded.secret_json,public_json=excluded.public_json,updated_at=excluded.updated_at').bind(owner,provider,encrypted,JSON.stringify(publicValue),new Date().toISOString()).run()}
