'use client';
import {useState} from 'react';
import {agentRequest} from '../agent/connections';
import type {WorkspaceData} from '@/lib/orbit/model';
interface Schedule {uncertain?:boolean;job:null|{enabled:boolean;nextRunAt?:string;lastRunAt?:string;lastStatus?:string;deliveryFailed?:boolean;deliveryUnverified?:boolean};settings:null|{hours:6|12|24;delivery:'local'|'telegram';research:string;includeCare:boolean;snapshotAt:string}}
export function BackgroundCoach({data}:{data:WorkspaceData}){
 const [state,setState]=useState<Schedule|null>(null),[busy,setBusy]=useState(false),[error,setError]=useState(''),[message,setMessage]=useState('');
 const time=(date?:string)=>date?new Date(date).toLocaleString('ko-KR',{timeZone:data.preferences.timeZone}):'아직 없음';
 async function request(action?:Record<string,unknown>){if(busy)return;setBusy(true);setError('');setMessage('');try{const result=await agentRequest('/api/agent/chief',action?'POST':'GET',action);setState(result);if(action)setMessage(action.action==='refresh'?'현재 목표·진척을 예약 실행에 전달했습니다.':'Hermes 예약 상태를 확인했습니다.')}catch(e){setError(e instanceof Error?e.message:'예약 상태를 확인하지 못했습니다.')}finally{setBusy(false)}}
 return <section className="chief-background"><h3>앱을 닫아도 챙기기</h3><p>Hermes가 켜져 있는 동안 예약 코칭과 최신 자료 조사를 실행합니다. Orbit에서 마지막으로 전달한 목표·진척을 기준으로 판단합니다.</p><p className="form-hint">닫힌 Orbit의 회의·메일·일정을 실시간으로 읽지는 않습니다. 앱을 열어 사용하는 동안 기록을 갱신하며, 아래에서도 직접 전달할 수 있습니다. Mac이 잠자기·종료 상태이면 실행되지 않습니다.</p>
 <button className="secondary-button" disabled={busy} onClick={()=>void request()}>Hermes 예약 상태 확인</button>
 {state?.uncertain&&<p role="alert" className="agent-error">이전 예약 변경의 성공 여부를 확인하지 못했습니다. 아래 기준 시점은 마지막으로 확인된 기록입니다. 설정을 확인하고 다시 갱신해 주세요.</p>}{state&&<><div className="chief-job-status"><strong>{state.job?(state.job.enabled?'예약 켜짐':'예약 일시 정지'):'예약 없음'}</strong>{state.settings&&<small>기록 기준: {time(state.settings.snapshotAt)}</small>}{state.job&&<><small>다음 실행: {time(state.job.nextRunAt)} · 마지막 실행: {time(state.job.lastRunAt)}</small><small>실행 상태: {state.job.lastStatus??'실행 전'}{state.job.deliveryFailed?' · 알림 전달 실패':state.job.deliveryUnverified?' · 전달 확인 안 됨':''}</small></>}</div>
 {state.job&&<div className="chief-actions"><button disabled={busy} className="secondary-button" onClick={()=>void request({action:'refresh'})}>현재 목표·진척 전달</button><button disabled={busy} className="text-button" onClick={()=>void request({action:state.job!.enabled?'pause':'resume'})}>{state.job.enabled?'예약 일시 정지':'예약 다시 켜기'}</button></div>}
 <form className="dialog-form" key={state.settings?.snapshotAt??'new'} onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);void request({action:'save',hours:Number(f.get('hours')),delivery:String(f.get('delivery')),research:String(f.get('research')??''),includeCare:f.get('care')==='on',acknowledged:f.get('ack')==='on'})}}><div className="chief-fields"><label>확인 간격<select name="hours" className="form-field" defaultValue={state.settings?.hours??12}><option value="6">6시간마다</option><option value="12">12시간마다</option><option value="24">24시간마다</option></select></label><label>받을 곳<select name="delivery" className="form-field" defaultValue={state.settings?.delivery??'local'}><option value="local">Hermes에 보고서 보관</option><option value="telegram">Hermes에 연결한 내 Telegram</option></select></label></div><p className="form-hint">‘보고서 보관’은 휴대폰 알림을 보내지 않습니다. Telegram은 Hermes에 본인 계정의 수신 채널이 이미 설정되어 있어야 합니다. 보고서 본문은 선택한 채널에서 확인합니다.</p><label>목표 달성에 필요한 최신 정보<input name="research" className="form-field" maxLength={300} defaultValue={state.settings?.research} placeholder="예: 목표 고객사의 최근 공개 소식과 영업 접점"/></label><label className="chief-inline"><input type="checkbox" name="care" defaultChecked={state.settings?.includeCare}/>건강·마음·학습 목표와 컨디션도 함께 전달</label><label className="chief-inline"><input type="checkbox" name="ack" required/>목표와 미완료 작업 요약을 내 Hermes에 전달하고, 선택한 내 채널로 반복 코칭을 받겠습니다.</label><button className="primary-button" disabled={busy}>이 내용으로 예약 {state.job?'갱신':'시작'}</button></form></>}
 {error&&<p role="alert" className="agent-error">{error}</p>}{message&&<p role="status" className="chief-notice">{message}</p>}
 </section>;
}
