'use client';
import { useEffect, useState } from 'react';
import { Orbit, ArrowUpRight, Play, Check, Clock3, Settings2, Heart, Target, Pause, X } from 'lucide-react';
import { Dialog, DialogContent, DialogHeader, DialogTitle, DialogDescription } from '@/components/ui/dialog';
import { chiefOfStaff, chiefDefaults, domainLabels } from '@/lib/orbit/chief';
import { formatTime, type WorkspaceData, type Goal } from '@/lib/orbit/model';
import type { WorkspaceAction } from '@/lib/orbit/validation';
import {agentRequest} from '../agent/connections';
import { BackgroundCoach } from './background-coach';
type Perform = (action: WorkspaceAction, message?: string) => Promise<boolean>;
const toneLabels = { gentle:'다정하게', balanced:'명확하고 따뜻하게', firm:'단호하게' };

export function GoalProgress({goal,today,perform,disabled}:{goal:Goal;today:string;perform:Perform;disabled:boolean}) {
  const [open,setOpen]=useState(false);
  if(!open) return <button type="button" className="text-button" onClick={()=>setOpen(true)}>진척·분야 수정</button>;
  return <form className="chief-goal-form" onSubmit={async e=>{e.preventDefault();const form=new FormData(e.currentTarget),tracking=form.get('track')==='on'; const next:Goal={...goal,domain:form.get('domain') as Goal['domain'],status:form.get('status') as Goal['status']}; if(tracking) next.progress={baseline:Number(form.get('baseline')),current:Number(form.get('current')),target:Number(form.get('target')),unit:String(form.get('unit')),startedOn:String(form.get('startedOn')),updatedOn:today};if(await perform({type:'goal.upsert',goal:next},'목표의 실제 진척을 저장했습니다.'))setOpen(false)}}>
    <div className="chief-fields"><label>분야<select className="form-field" name="domain" defaultValue={goal.domain??'work'}>{Object.entries(domainLabels).map(([id,label])=><option key={id} value={id}>{label}</option>)}</select></label><label>상태<select className="form-field" name="status" defaultValue={goal.status??'active'}><option value="active">진행 중</option><option value="paused">잠시 보류</option><option value="achieved">결과 확인 · 달성</option></select></label></div>
    <label className="chief-inline"><input name="track" type="checkbox" defaultChecked={!!goal.progress}/> 실제 수치로 진척 기록</label>
    <div className="chief-fields"><label>시작값<input name="baseline" type="number" step="any" className="form-field" defaultValue={goal.progress?.baseline??0}/></label><label>현재값<input name="current" type="number" step="any" className="form-field" defaultValue={goal.progress?.current??0}/></label><label>목표값<input name="target" type="number" step="any" className="form-field" defaultValue={goal.progress?.target??1}/></label><label>단위<input name="unit" maxLength={30} className="form-field" defaultValue={goal.progress?.unit??'회'}/></label><label>시작일<input name="startedOn" type="date" max={today} className="form-field" defaultValue={goal.progress?.startedOn??today}/></label></div>
    <p className="form-hint">마감일까지의 선형 기준선과 비교합니다. 목표 달성은 결과를 직접 확인한 뒤 표시하세요.</p>
    <div className="chief-actions"><button disabled={disabled} className="primary-button">진척 저장</button><button type="button" className="text-button" onClick={()=>setOpen(false)}>취소</button></div>
  </form>;
}

export function ChiefPanel({data,perform,busy,demo,onAsk,onGoals}:{data:WorkspaceData;perform:Perform;busy:boolean;demo:boolean;onAsk:(text:string)=>void;onGoals:()=>void}) {
  const [now,setNow]=useState(()=>new Date()),[settingsOpen,setSettingsOpen]=useState(false),[checkOpen,setCheckOpen]=useState(false),[blocked,setBlocked]=useState(false),[reason,setReason]=useState(''),[pending,setPending]=useState(false),[notice,setNotice]=useState(''),[syncError,setSyncError]=useState('');
  useEffect(()=>{const open=()=>{setSettingsOpen(true);setCheckOpen(true)};window.addEventListener('orbit:coach-settings',open);return()=>window.removeEventListener('orbit:coach-settings',open)},[]);
  useEffect(()=>{const tick=()=>setNow(new Date()),timer=setInterval(tick,60000);document.addEventListener('visibilitychange',tick);return()=>{clearInterval(timer);document.removeEventListener('visibilitychange',tick)}},[]);
  useEffect(()=>{if(demo)return;let cancelled=false;const timer=setTimeout(()=>{void agentRequest('/api/agent/chief','POST',{action:'sync'}).then(()=>{if(!cancelled)setSyncError('')}).catch(()=>{if(!cancelled)setSyncError('앱 밖 예약에 최신 설정·기록을 전달하지 못했습니다. 비서실장 설정에서 예약 상태를 확인해 주세요.')})},1500);return()=>{cancelled=true;clearTimeout(timer)}},[data,demo]);
  const state=chiefOfStaff(data,now),signal=state.primary,disabled=busy||demo||pending,settings={...chiefDefaults,...data.chief?.settings};
  async function act(action:WorkspaceAction,message:string){if(disabled)return false;setPending(true);setNotice('');try{const ok=await perform(action,message);if(ok){setNow(new Date());setNotice(message)}return ok}finally{setPending(false)}}
  const respond=(kind:'snooze'|'blocked'|'recovered',minutes:number,note='')=>act({type:'chief.respond',key:signal.key,kind,minutes,reason:note},kind==='recovered'?'휴식을 기록했습니다. 다음 행동을 확인합니다.':`${minutes}분 뒤 다시 확인합니다.`);
  return <section className={`chief-panel ${signal.kind==='recovery'?'chief-recovery':''}`} aria-label="목표를 챙기는 비서실장">
    <div className="chief-top"><span><Orbit size={17}/> 나의 궤도</span><div><button className="text-button" onClick={()=>setCheckOpen(v=>!v)}>{state.checkin?'컨디션 수정':'30초 체크인'}</button><button className="icon-button" aria-label="비서실장 설정" onClick={()=>setSettingsOpen(true)}><Settings2 size={16}/></button></div></div>
    {(state.paused||state.quiet||state.meeting)&&<p className="chief-pause">{state.paused?'잠시 쉬는 중입니다.':state.meeting?`‘${state.meeting}’ 시간입니다.`:'방해하지 않는 시간입니다.'} 먼저 알리지 않고, 필요할 때 확인할 수 있게 준비합니다.</p>}
    <h2>{signal.title}</h2><p className="chief-reason">{signal.reason}</p><p className="chief-next">{signal.next}</p>
    <div className="chief-actions">
      {signal.kind==='task'&&<button className="primary-button" disabled={disabled} onClick={()=>void act({type:'task.start',id:signal.taskId!},'집중을 시작했습니다. 작은 단계부터 진행하세요.')}><Play size={15}/>{signal.minutes}분부터 시작</button>}
      {signal.kind==='focus'&&<><button className="primary-button" disabled={disabled} onClick={()=>void act({type:'task.record',id:signal.taskId!,outcome:'done'},'완료를 기록했습니다.')}><Check size={15}/>완료 기록</button><button className="secondary-button" disabled={disabled} onClick={()=>void act({type:'task.stop',id:signal.taskId!},'집중을 멈추고 사용한 시간을 기록했습니다.')}><Pause size={15}/>잠시 멈춤</button></>}
      {signal.kind==='care'&&<button className="primary-button" disabled={disabled} onClick={()=>void act({type:'care.check',id:signal.routineId!,checked:true},'오늘의 돌봄·학습을 완료로 기록했습니다.')}><Check size={15}/>실천 완료</button>}
      {signal.kind==='recovery'&&<button className="primary-button" disabled={disabled} onClick={()=>void respond('snooze',5,'5분 회복을 선택함')}><Heart size={15}/>5분 쉬기</button>}
      {signal.kind==='rest'&&<button className="primary-button" disabled={disabled} onClick={()=>void respond('recovered',120,'휴식을 마쳤다고 확인함')}>휴식 마침 · 다음 행동</button>}
      {signal.kind==='goal'&&<button className="primary-button" onClick={onGoals}><Target size={15}/>목표 진척 확인</button>}
      {signal.kind==='checkin'&&<button className="primary-button" onClick={()=>setCheckOpen(true)}>컨디션 알려주기</button>}
      <button className="secondary-button" disabled={demo||busy} onClick={()=>onAsk(signal.ask)}>함께 풀기 <ArrowUpRight size={15}/></button>
      {!['focus','clear','rest'].includes(signal.kind)&&<><button className="text-button" disabled={disabled} onClick={()=>void respond('snooze',30)}><Clock3 size={14}/>30분 뒤</button><button className="text-button" disabled={disabled} onClick={()=>setBlocked(true)}>막혔어요</button></>}
    </div>
    {(checkOpen||(!state.checkin&&signal.kind==='checkin'))&&<form className="chief-checkin" key={state.today} onSubmit={async e=>{e.preventDefault();const form=new FormData(e.currentTarget);if(await act({type:'chief.checkin',energy:form.get('energy') as 'low'|'normal'|'high',strain:form.get('strain') as 'light'|'normal'|'heavy',note:String(form.get('note')??'')},'오늘 컨디션에 맞춰 우선순위를 다시 판단했습니다.'))setCheckOpen(false)}}><div className="chief-fields"><label>에너지<select required name="energy" className="form-field" defaultValue={state.checkin?.energy??''}><option value="" disabled>지금 상태</option><option value="low">낮아요</option><option value="normal">괜찮아요</option><option value="high">충분해요</option></select></label><label>부담<select required name="strain" className="form-field" defaultValue={state.checkin?.strain??''}><option value="" disabled>느끼는 부담</option><option value="light">여유 있어요</option><option value="normal">감당할 만해요</option><option value="heavy">많이 버거워요</option></select></label></div><label>오늘 필요한 도움 <input name="note" className="form-field" maxLength={500} defaultValue={state.checkin?.note} placeholder="선택 · 막힌 일, 수면, 집중, 도움받고 싶은 것"/></label><button className="primary-button" disabled={disabled}>오늘의 페이스 맞추기</button></form>}
    {state.alternatives.length>0&&<details className="chief-more"><summary>다음에 챙길 것 {state.alternatives.length}개</summary>{state.alternatives.map(s=><button key={s.key} className="chief-alternative" disabled={demo||busy} onClick={()=>onAsk(s.ask)}><span>{s.title}<small>{s.reason}</small></span><ArrowUpRight size={15}/></button>)}</details>}
    <div className="chief-bottom"><span>{state.wins?`오늘의 실행 ${state.wins}개 · `:''}완료할 때까지 다음 확인을 이어갑니다</span><button className="text-button" onClick={onGoals}>목표 관리</button></div>
    {syncError&&<p role="alert" className="agent-error">{syncError}</p>}
    {notice&&<p className="chief-notice" role="status">{notice}</p>}
    {blocked&&<Dialog open onOpenChange={setBlocked}><DialogContent><DialogHeader><DialogTitle>무엇이 진행을 막고 있나요?</DialogTitle><DialogDescription>할 일은 이유와 함께 대기로 옮깁니다. 60분 뒤 다시 확인하고, 지금은 해결 방법을 함께 찾습니다.</DialogDescription></DialogHeader><form className="dialog-form" onSubmit={async e=>{e.preventDefault();if(await respond('blocked',60,reason)){setBlocked(false);onAsk(`${signal.ask}\n현재 막힌 이유: ${reason}. 60분 뒤 재확인하도록 기록했어. 지금 가능한 우회 방법부터 제안해 줘.`);setReason('')}}}><label>막힌 이유<textarea required maxLength={500} className="form-field" value={reason} onChange={e=>setReason(e.target.value)} placeholder="정보가 부족한지, 누군가의 답을 기다리는지, 일이 너무 큰지"/></label><button className="primary-button" disabled={disabled||!reason.trim()}>기억하고 해결 방법 찾기</button></form></DialogContent></Dialog>}
    {settingsOpen&&<Dialog open onOpenChange={setSettingsOpen}><DialogContent className="settings-dialog chief-settings"><DialogHeader><DialogTitle>나를 이끄는 방식</DialogTitle><DialogDescription>목표는 분명하게, 페이스는 오늘의 나에게 맞게.</DialogDescription></DialogHeader>
      <form className="dialog-form" onSubmit={async e=>{e.preventDefault();const f=new FormData(e.currentTarget),minutes=(key:string)=>String(f.get(key)).split(':').reduce((a,b)=>a*60+Number(b),0);await act({type:'chief.settings',settings:{tone:f.get('tone') as typeof settings.tone,quietStart:minutes('start'),quietEnd:minutes('end'),pausedUntil:settings.pausedUntil}},'개입 방식을 저장했습니다.')}}><label>나에게 말하는 방식<select className="form-field" name="tone" defaultValue={settings.tone}>{Object.entries(toneLabels).map(([id,label])=><option key={id} value={id}>{label}</option>)}</select></label><p className="form-hint">단호한 모드도 비난하거나 수면·회복을 희생시키지 않습니다. 실제 지연의 근거와 다음 행동을 분명히 말합니다.</p><div className="chief-fields"><label>조용한 시간 시작<input type="time" name="start" required className="form-field" defaultValue={formatTime(settings.quietStart)}/></label><label>조용한 시간 종료<input type="time" name="end" required className="form-field" defaultValue={formatTime(settings.quietEnd)}/></label></div><div className="chief-actions"><button className="primary-button" disabled={disabled}>설정 저장</button><button type="button" className="secondary-button" disabled={disabled} onClick={()=>void act({type:'chief.settings',settings:{...settings,pausedUntil:state.paused?undefined:new Date(Date.now()+86400000).toISOString()}},state.paused?'비서실장의 개입을 다시 켰습니다.':'24시간 먼저 알리지 않습니다.')}>{state.paused?'개입 다시 켜기':'24시간 쉬기'}</button></div></form>
      <CareSettings data={data} perform={act} disabled={disabled} today={state.today}/>
      {!demo&&<BackgroundCoach data={data}/>}
    </DialogContent></Dialog>}
  </section>;
}

function CareSettings({data,perform,disabled,today}:{data:WorkspaceData;perform:(action:WorkspaceAction,message:string)=>Promise<boolean>;disabled:boolean;today:string}) {
  return <section className="chief-care-settings"><h3>목표를 지탱하는 돌봄·학습</h3><p className="form-hint">등록한 시간은 실행 제안에서 보호합니다. Google 일정에 자동 등록하지 않습니다.</p>{(data.careRoutines??[]).map(r=><div className="chief-routine" key={r.id}><span><strong>{r.title}</strong><small>{domainLabels[r.domain]} · {formatTime(r.start)} · {r.minutes}분 · {r.days.length===7?'매일':r.days.map(d=>'일월화수목금토'[d]).join('·')}</small></span><button className="text-button" disabled={disabled} onClick={()=>void perform({type:'care.check',id:r.id,checked:!r.log.includes(today)},r.log.includes(today)?'완료를 취소했습니다.':'오늘의 실천을 기록했습니다.')}>{r.log.includes(today)?'완료 취소':'실천 완료'}</button><button className="icon-button" disabled={disabled} aria-label={`${r.title} 삭제`} onClick={()=>void perform({type:'care.delete',id:r.id},'루틴을 삭제했습니다.')}><X size={14}/></button></div>)}
    <form className="dialog-form" onSubmit={async e=>{e.preventDefault();const form=e.currentTarget,f=new FormData(form),[h,m]=String(f.get('time')).split(':').map(Number);if(await perform({type:'care.upsert',routine:{id:crypto.randomUUID(),title:String(f.get('title')),domain:f.get('domain') as 'health'|'mind'|'learning',minutes:Number(f.get('minutes')),start:h*60+m,days:f.getAll('day').map(Number),active:true,...(f.get('goal')?{goalId:String(f.get('goal'))}:{})}},'돌봄·학습 시간을 등록했습니다.'))form.reset()}}><label>작고 구체적인 행동<input required maxLength={160} name="title" className="form-field" placeholder="예: 점심 뒤 10분 걷기 / 3분 명상 / 영어 10분"/></label><div className="chief-fields"><label>분야<select name="domain" className="form-field"><option value="health">건강</option><option value="mind">마음·회복</option><option value="learning">학습</option></select></label><label>시작<input type="time" name="time" defaultValue="12:30" required className="form-field"/></label><label>분<input type="number" name="minutes" min={2} max={120} defaultValue={10} required className="form-field"/></label></div><fieldset className="chief-days"><legend>실천 요일</legend>{[0,1,2,3,4,5,6].map(d=><label key={d}><input type="checkbox" name="day" value={d} defaultChecked/>{'일월화수목금토'[d]}</label>)}</fieldset><label>연결할 목표<select name="goal" className="form-field"><option value="">일상 유지</option>{(data.goals??[]).filter(g=>(g.status??'active')==='active').map(g=><option key={g.id} value={g.id}>{g.sentence}</option>)}</select></label><button className="secondary-button" disabled={disabled||(data.careRoutines?.length??0)>=12}>돌봄·학습 시간 추가</button></form>
  </section>;
}
