'use client';
import {useId,useMemo,useState} from 'react';
import {Target,Plus,ArrowUpRight,Play,Check,Link2,Network,List,Flag,LockKeyhole} from 'lucide-react';
import {Dialog,DialogContent,DialogHeader,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {Tabs,TabsList,TabsTrigger} from '@/components/ui/tabs';
import {Progress} from '@/components/ui/progress';
import {goalDashboard,questMap,questReadiness,type QuestState} from '@/lib/orbit/pacemaker';
import {domainLabels} from '@/lib/orbit/chief';
import {GoalProgress} from './chief-panel';
import type {WorkspaceData,Goal,Task} from '@/lib/orbit/model';
import type {WorkspaceAction} from '@/lib/orbit/validation';
type Perform=(action:WorkspaceAction,message?:string)=>Promise<boolean>;
type Open=(target:{kind:'task'|'project'|'note';id:string})=>void;
const stateLabels:Record<QuestState,string>={ready:'시작 가능',doing:'진행 중',blocked:'선행 대기',waiting:'응답 대기',held:'보류',paused:'목표 보류',done:'완료'};
const colors:Record<QuestState,string>={ready:'#6554dc',doing:'#6554dc',blocked:'#b57b2b',waiting:'#b57b2b',held:'#858ca2',paused:'#858ca2',done:'#258266'};
function metric(goal:Goal){const p=goal.progress;return p&&p.target!==p.baseline?Math.max(0,Math.min(1,(p.current-p.baseline)/(p.target-p.baseline))):null;}
export function GoalDashboard({data,today,busy,demo,perform,onManage,onOpen,onAsk}:{data:WorkspaceData;today:string;busy:boolean;demo:boolean;perform:Perform;onManage:()=>void;onOpen:Open;onAsk:(text:string)=>void}){
 const [selected,setSelected]=useState(''),[mode,setMode]=useState('map'),[adding,setAdding]=useState(false),[filter,setFilter]=useState('all');
 const goals=useMemo(()=>goalDashboard(data,today),[data,today]),entry=goals.find(g=>g.goal.id===selected)??goals.find(g=>(g.goal.status??'active')==='active')??goals[0];
 const disabled=busy||demo;
 const ask=()=>onAsk(entry?`목표 '${entry.goal.sentence}'(goalId=${entry.goal.id})를 달성하는 퀘스트를 설계해 줘. 현재 프로젝트와 기존 퀘스트를 먼저 읽고 중복을 피하면서, 필요한 최소 단계 2~6개와 선후 관계, 각 완료 조건을 정해 줘. 기존 일이면 수정/활용하고 새 일은 quest.plan 승인 카드 한 장으로 제안해 줘. 아직 실제 저장하거나 일정에 넣지는 마. 날짜·시간을 가정하면 명시하고, 건강·회복·학습 시간도 지켜줘.`:'내가 달성하고 싶은 목표를 구체화하도록 도와줘. 원하는 변화와 완료 기준부터 짧게 물어봐 줘.');
 return <div className="orbit-goals"><div className="goal-dashboard-toolbar"><p>원하는 변화와 오늘의 실행을 연결합니다.</p><div><button className="secondary-button" onClick={onManage}><Target size={16}/>목표 관리</button><button className="primary-button" disabled={demo} onClick={ask}>퀘스트 설계하기 <ArrowUpRight size={16}/></button></div></div>
  {!goals.length?<section className="goal-onboarding"><Target size={30}/><h2>어떤 변화를 이루고 싶으신가요?</h2><p>일·건강·마음·학습 중 원하는 목표를 하나 정하면, 필요한 퀘스트와 다음 행동을 연결합니다.</p><div className="chief-actions"><button className="primary-button" onClick={onManage}>첫 목표 만들기</button><button className="secondary-button" disabled={demo} onClick={ask}>Orbit과 함께 정하기</button></div></section>:<>
  <div className="goal-overview" role="group" aria-label="나의 목표 선택">{goals.map(g=>{const progress=metric(g.goal);return <button key={g.goal.id} className={`goal-overview-card ${entry.goal.id===g.goal.id?'selected':''}`} onClick={()=>setSelected(g.goal.id)} aria-pressed={entry.goal.id===g.goal.id}><div className="goal-card-meta"><span>{domainLabels[g.goal.domain??'work']}</span><span>{g.goal.status==='achieved'?'달성':g.goal.status==='paused'?'보류':g.pace.status==='behind'?'경로 점검':'진행 중'}</span></div><strong>{g.goal.sentence}</strong><div className="goal-card-progress"><span>{progress===null?'성과 수치 미등록':`${g.goal.progress!.current} / ${g.goal.progress!.target} ${g.goal.progress!.unit}`}</span><span>{g.done}/{g.total} 퀘스트</span></div><Progress value={g.ratio*100} aria-label={`${g.goal.sentence} 퀘스트 완료율`}/></button>})}</div>
  <section className="goal-command"><div className="goal-command-main"><span className="goal-kicker">내가 만들 변화</span><h2>{entry.goal.sentence}</h2><p>{entry.goal.deadline?`${entry.goal.deadline}까지`:'목표 기한을 정해 주세요.'}{entry.goal.progress&&` · 성과 확인 ${entry.goal.progress.updatedOn}`}</p><div className="goal-project-path"><Flag size={15}/><span>목표</span><span>→</span>{entry.projects.length?entry.projects.map(p=><button key={p.id} onClick={()=>onOpen({kind:'project',id:p.id})}>{p.name}</button>):<span>첫 퀘스트를 등록하면 실행 프로젝트를 연결합니다.</span>}</div><GoalProgress key={entry.goal.id} goal={entry.goal} today={today} perform={perform} disabled={disabled}/></div><div className="goal-metric"><svg width="114" height="114" viewBox="0 0 114 114" role="img" aria-label={metric(entry.goal)===null?'성과 미확인':`실제 수치 진척 ${Math.round(metric(entry.goal)!*100)}퍼센트`}><circle cx="57" cy="57" r="47" fill="none" stroke="#e9e8f4" strokeWidth="8"/><circle cx="57" cy="57" r="47" fill="none" stroke="#6554dc" strokeWidth="8" strokeLinecap="round" strokeDasharray={`${(metric(entry.goal)??0)*295.31} 295.31`} transform="rotate(-90 57 57)"/><text x="57" y="61" textAnchor="middle" fontSize="23" fontWeight="700" fill="#3d4260">{metric(entry.goal)===null?'—':`${Math.round(metric(entry.goal)!*100)}%`}</text></svg><strong>실제 성과</strong><small>{entry.goal.status==='achieved'?'결과 확인 · 달성':entry.pace.status==='confirm'?'목표 수치 도달 · 결과 확인 필요':entry.pace.status==='unknown'?'현재 수치를 확인해 주세요.':'직접 기록한 수치 기준'}</small></div></section>
  <div className="quest-summary"><div><strong>{entry.total}</strong><span>전체 퀘스트</span></div><div><strong>{entry.ready.length}</strong><span>시작·재개 가능</span></div><div><strong>{entry.blocked.length}</strong><span>확인할 장애물</span></div><div><strong>{entry.done}</strong><span>완료한 퀘스트</span></div></div>
  <section className="quest-workbench"><div className="quest-toolbar"><Tabs value={mode} onValueChange={setMode}><TabsList aria-label="퀘스트 보기"><TabsTrigger value="map"><Network size={15}/>실행 경로</TabsTrigger><TabsTrigger value="list"><List size={15}/>퀘스트 목록</TabsTrigger></TabsList></Tabs><button className="secondary-button" disabled={disabled||['paused','achieved'].includes(entry.goal.status??'active')} onClick={()=>setAdding(true)}><Plus size={15}/>퀘스트 추가</button></div>
  {mode==='map'&&<QuestGraph data={data} tasks={entry.quests.map(q=>q.task)} today={today} onOpen={onOpen}/>}
  <div className="quest-list-head"><h3>다음 행동까지 이어지는 퀘스트</h3><select className="form-field" aria-label="퀘스트 상태 필터" value={filter} onChange={e=>setFilter(e.target.value)}><option value="all">전체</option><option value="ready">시작·재개 가능</option><option value="blocked">장애물 확인</option><option value="done">완료</option></select></div>
  {entry.quests.filter(q=>filter==='all'||filter==='ready'&&q.canStart||filter==='blocked'&&entry.blocked.includes(q)||filter==='done'&&q.state==='done').map(q=><div key={q.task.id} className={`quest-row quest-${q.state}`}><span className="quest-status" style={{color:colors[q.state]}}>{q.state==='done'?<Check size={17}/>:q.canStart?<Play size={17}/>:<LockKeyhole size={17}/>}</span><div className="quest-row-body"><button className="quest-title" onClick={()=>onOpen({kind:'task',id:q.task.id})}>{q.task.title}</button><p>{q.reason}</p><small>{q.task.due} 마감 · {q.task.duration}분 · {data.projects.find(p=>p.id===q.task.projectId)?.name}</small><div className="quest-definition">완료 조건 · {q.task.definition||'아직 정하지 않았습니다.'}</div>{q.task.noteId&&<button className="text-button" onClick={()=>onOpen({kind:'note',id:q.task.noteId!})}><Link2 size={13}/>연결 기록 확인</button>}</div><div className="quest-row-actions"><span style={{color:colors[q.state]}}>{stateLabels[q.state]}</span>{q.canStart&&!q.task.startedAt&&<button className="secondary-button" disabled={disabled} onClick={()=>void perform({type:'task.start',id:q.task.id},'퀘스트의 집중 세션을 시작했습니다.')}>시작</button>}<button className="text-button" onClick={()=>onOpen({kind:'task',id:q.task.id})}>{q.state==='done'?'결과 보기':'열기'}</button></div></div>)}
  {!entry.total&&<div className="quest-empty"><h3>목표까지의 첫 단계를 정해봅시다.</h3><p>Orbit이 현재 기록을 검토해 퀘스트를 제안하거나, 직접 첫 단계를 추가할 수 있습니다.</p><button className="primary-button" disabled={demo} onClick={ask}>기록을 바탕으로 퀘스트 설계</button></div>}
  <p className="quest-note">퀘스트 완료율과 실제 성과는 별도로 확인합니다. 연결된 하위 목표의 퀘스트도 함께 표시합니다.</p></section>
  {adding&&<AddQuest data={data} goal={entry.goal} today={today} disabled={disabled} perform={perform} onClose={()=>setAdding(false)}/>}
 </>}
 </div>;
}
function QuestGraph({data,tasks,today,onOpen}:{data:WorkspaceData;tasks:Task[];today:string;onOpen:Open}){
 const map=useMemo(()=>questMap(data,tasks),[data,tasks]),marker=useId().replace(/:/g,'');
 if(!tasks.length)return null;
 return <><div className="quest-map" tabIndex={0} role="region" aria-label="퀘스트 선후 관계, 좌우로 스크롤할 수 있습니다"><svg width={map.width} height={map.height} role="img" aria-label="화살표의 앞 퀘스트를 완료하면 다음 퀘스트를 시작할 수 있습니다"><defs><marker id={marker} markerWidth="8" markerHeight="8" refX="7" refY="4" orient="auto"><path d="M0 0 L8 4 L0 8" fill="#a8a4c2"/></marker></defs>{map.edges.map(e=>{const a=map.nodes.find(n=>n.id===e.from)!,b=map.nodes.find(n=>n.id===e.to)!;return <path key={e.from+e.to} d={`M${a.x+200},${a.y+34} C${a.x+225},${a.y+34} ${b.x-25},${b.y+34} ${b.x-8},${b.y+34}`} fill="none" stroke="#bbb6d7" strokeWidth="1.5" markerEnd={`url(#${marker})`}/>})}{map.nodes.map(n=>{const status=n.task?questReadiness(data,n.task,today).state:'blocked';return <g key={n.id} transform={`translate(${n.x} ${n.y})`} role={n.task?'button':undefined} tabIndex={n.task?0:undefined} aria-label={`${n.title}, ${n.external?'다른 경로의 선행 퀘스트, ':''}${stateLabels[status]}`} onClick={()=>n.task&&onOpen({kind:'task',id:n.id})} onKeyDown={e=>{if(n.task&&(e.key==='Enter'||e.key===' ')){e.preventDefault();onOpen({kind:'task',id:n.id})}}}><rect width="200" height="76" rx="12" fill={status==='done'?'#eff8f4':'white'} stroke={colors[status]} strokeWidth="1.2" strokeDasharray={n.external?'4 3':undefined}/><text x="14" y="25" fill="#3d4260" fontSize="14" fontWeight="600">{n.title.length>17?n.title.slice(0,17)+'…':n.title}</text><text x="14" y="52" fill={colors[status]} fontSize="13">{n.external?'외부 선행 · ':''}{stateLabels[status]}</text></g>})}</svg></div><p className="quest-note">화살표 방향으로 선행 퀘스트를 먼저 완료합니다. 점선은 다른 경로 또는 화면 밖의 선행 퀘스트입니다.{map.omittedPrerequisites>0&&` 외부 선행 ${map.omittedPrerequisites}개는 아래 퀘스트의 대기 이유에서 확인합니다.`}{map.omitted>0&&` 경로에는 ${tasks.length-map.omitted}개를 표시하며 전체 ${tasks.length}개는 아래 목록에서 확인합니다.`}</p></>;
}
function AddQuest({data,goal,today,disabled,perform,onClose}:{data:WorkspaceData;goal:Goal;today:string;disabled:boolean;perform:Perform;onClose:()=>void}){
 const projects=data.projects.filter(p=>p.goalId===goal.id),[pending,setPending]=useState(false);
 return <Dialog open onOpenChange={v=>{if(!v&&!pending)onClose()}}><DialogContent><DialogHeader><DialogTitle>목표에 한 걸음 더 가까이</DialogTitle><DialogDescription>{goal.sentence}</DialogDescription></DialogHeader><form className="dialog-form" onSubmit={async e=>{e.preventDefault();const f=new FormData(e.currentTarget),projectId=String(f.get('project')),id=crypto.randomUUID(),due=String(f.get('due'));const project=projectId==='new'?{id:crypto.randomUUID(),name:goal.sentence.slice(0,60),goal:goal.sentence,goalId:goal.id,color:'#6554dc',symbol:'O',due:goal.deadline??due,priority:3}:undefined;setPending(true);try{if(await perform({type:'quest.plan',goalId:goal.id,...(project?{project}:{}),tasks:[{id,title:String(f.get('title')),definition:String(f.get('definition')),duration:Number(f.get('duration')),due,impact:3,projectId:project?.id??projectId,dependsOn:f.getAll('depends').map(String)}]},'퀘스트와 목표 연결을 함께 저장했습니다.'))onClose()}finally{setPending(false)}}}><label>퀘스트<input required maxLength={160} name="title" className="form-field" placeholder="지금 실행할 수 있는 구체적인 한 단계"/></label><label>어떻게 되면 완료인가요?<textarea required maxLength={4000} name="definition" className="form-field" placeholder="결과물 또는 스스로 확인할 수 있는 실천 기준"/></label><div className="chief-fields"><label>마감<input required type="date" name="due" defaultValue={goal.deadline??today} className="form-field"/></label><label>예상 시간(분)<input required type="number" min={5} max={480} step={5} name="duration" defaultValue={25} className="form-field"/></label></div><label>실행 프로젝트<select name="project" className="form-field" defaultValue={projects[0]?.id??'new'}>{projects.map(p=><option key={p.id} value={p.id}>{p.name}</option>)}<option value="new">이 목표의 실행 프로젝트 만들기</option></select></label><fieldset className="quest-prerequisites"><legend>먼저 완료해야 할 퀘스트 · 선택</legend>{data.tasks.filter(t=>t.status!=='done').slice(0,60).map(t=><label key={t.id}><input name="depends" type="checkbox" value={t.id}/>{t.title}</label>)}</fieldset><button className="primary-button" disabled={disabled||pending}>퀘스트 등록</button></form></DialogContent></Dialog>;
}
