'use client';
import {useEffect,useRef,useState} from 'react';
import {BookOpen,Brain,Check,Link2,MessageSquare,Plus,Search,Sparkles,Upload,ArrowUpRight,Trash2,Pencil} from 'lucide-react';
import {Dialog,DialogContent,DialogHeader,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {personalContext,memoryAvailable} from '@/lib/orbit/pacemaker';
import type {PersonalMemory,WorkspaceData,View} from '@/lib/orbit/model';
import type {WorkspaceAction} from '@/lib/orbit/validation';
type Perform=(action:WorkspaceAction,message?:string)=>Promise<boolean>;
type Open=(target:{kind:'task'|'note';id:string})=>void;
const kinds={preference:'나의 선호',constraint:'고려할 조건',strategy:'효과적인 방식',reflection:'자기 탐색'};
const frictionNames:Record<string,string>={time:'시간 부족',waiting:'외부 응답 대기',priority:'우선순위 변경',scope:'범위가 큼',energy:'에너지 부족',other:'기타'};
type Conversation={id:string;conversationId:string;title:string;date:string;user:string;assistant:string};
async function personalRequest(query?:string){const response=await fetch('/api/personal'+(query!==undefined?'?q='+encodeURIComponent(query):''),{cache:'no-store'});const body=await response.json();if(!response.ok)throw new Error(body.error??'대화 기록을 불러오지 못했습니다.');return body;}
export function Understanding({data,today,busy,demo,perform,onOpen,navigate,onAsk,onConnect}:{data:WorkspaceData;today:string;busy:boolean;demo:boolean;perform:Perform;onOpen:Open;navigate:(view:View)=>void;onAsk:(text:string)=>void;onConnect:()=>void}){
 const context=personalContext(data,today),[editing,setEditing]=useState<Partial<PersonalMemory>|null>(null),[importing,setImporting]=useState(false),[stats,setStats]=useState<{turns:number;conversations:number}|null>(null),[error,setError]=useState(''),[query,setQuery]=useState(''),[searching,setSearching]=useState(false),[results,setResults]=useState<Conversation[]|null>(null),[deleting,setDeleting]=useState<PersonalMemory|null>(null);
 const searchToken=useRef(0),disabled=demo||busy;
 useEffect(()=>{let active=true;if(!demo)void personalRequest().then(r=>{if(active)setStats(r)}).catch(e=>{if(active)setError(e.message)});return()=>{active=false;searchToken.current++}},[demo]);
 const search=async()=>{const token=++searchToken.current;setSearching(true);setError('');try{const r=await personalRequest(query);if(token===searchToken.current)setResults(r.items)}catch(e){if(token===searchToken.current)setError(e instanceof Error?e.message:'검색 실패')}finally{if(token===searchToken.current)setSearching(false)}};
 const meeting=data.notes.filter(n=>n.kind==='meeting').length,mail=data.notes.filter(n=>n.source?.provider==='gmail').length;
 return <div className="orbit-understanding">
  <div className="understanding-intro"><div><Brain size={23}/><h2>나를 이해하는 기록</h2><p>내가 확인한 기억과 실행 결과를 다음 대화와 하루 제안에 함께 사용합니다.</p></div><button className="primary-button" disabled={disabled} onClick={()=>setEditing({})}><Plus size={16}/> 기억 추가</button></div>
  <section className="understanding-sources" aria-label="연결된 기록"><button onClick={()=>navigate('wiki')}><BookOpen size={18}/><strong>{data.notes.length}</strong><span>위키·지식 기록</span></button><button onClick={()=>navigate('wiki')}><MessageSquare size={18}/><strong>{meeting} / {mail}</strong><span>회의록 / 가져온 메일</span></button><button onClick={()=>navigate('calendar')}><Link2 size={18}/><strong>{data.events.length}</strong><span>저장된 일정</span></button><button onClick={()=>{document.getElementById('personal-conversation-search')?.focus()}}><Brain size={18}/><strong>{stats?stats.conversations:demo?'—':'…'}</strong><span>Orbit 대화방{stats?` · ${stats.turns}개 응답`:''}</span></button></section>
  <div className="understanding-source-actions"><span>연결한 계정에서 가져온 기록과 직접 남긴 자료를 사용합니다.</span><button className="text-button" disabled={demo} onClick={onConnect}>계정 연결 관리 <Link2 size={14}/></button><button className="secondary-button" disabled={disabled} onClick={()=>setImporting(true)}><Upload size={15}/> 자기 탐색·AI 대화 가져오기</button></div>
  <section className="understanding-memory"><div className="understanding-section-head"><div><h3>내가 확인한 기억 <small>{data.memories?.length??0}/60</small></h3><p>맞지 않는 기억은 바로 수정하거나 지울 수 있습니다. AI의 새로운 기억 제안은 승인 후 저장됩니다.</p></div><button className="text-button" disabled={demo} onClick={()=>onAsk('내가 연결한 기록과 대화에서, 다음 목표 실행에 도움이 될 만한 나의 선호나 효과적인 방식을 찾아줘. 근거를 읽고 확실한 것만 기억 제안 카드로 보여줘. 기존 기억과 중복하지 말고 자기 탐색 해석과 실제 실행 기록을 구분해 줘.')}><Sparkles size={15}/> 기록에서 기억 제안받기</button></div>
   {!data.memories?.length?<div className="understanding-empty"><Brain size={26}/><p>“중요한 일은 오전에 25분씩 시작하는 편이 좋아요.”<br/>나에게 맞는 방식을 하나부터 알려주세요.</p><button className="text-button" disabled={disabled} onClick={()=>setEditing({})}>첫 기억 남기기 <ArrowUpRight size={14}/></button></div>:<div className="memory-grid">{data.memories.map(memory=>{const available=memoryAvailable(data,memory);return <article className={'memory-card '+(!available?'needs-review':'')} key={memory.id}><div className="memory-card-top"><span>{kinds[memory.kind]}{memory.origin==='saju'?' · 사주 해석':''}</span><div><button className="icon-button" aria-label={memory.statement+' 수정'} disabled={disabled} onClick={()=>setEditing(memory)}><Pencil size={14}/></button><button className="icon-button" aria-label={memory.statement+' 삭제'} disabled={disabled} onClick={()=>setDeleting(memory)}><Trash2 size={14}/></button></div></div><p>{memory.statement}</p><small>{available?memory.kind==='reflection'?'자기 탐색에 참고 · 성과·건강 판단에 사용하지 않음':'확인한 기억 · 다음 대화와 제안에 반영':'연결 기록이 변경되거나 삭제되어 활용 중지 · 다시 확인해 주세요'}</small><div className="memory-source-list">{memory.sources.map((source,i)=><button key={i} className="text-button" onClick={()=>source.kind==='review'?navigate('review'):onOpen({kind:source.kind,id:source.id})}><Link2 size={12}/>{source.kind==='note'?data.notes.find(n=>n.id===source.id)?.title??'삭제된 기록':source.kind==='task'?data.tasks.find(t=>t.id===source.id)?.title??'삭제된 퀘스트':source.id+' 회고'}{source.revision?' · v'+source.revision:''}</button>)}</div><time>확인 {memory.updatedOn}</time></article>})}</div>}
  </section>
  <section className="understanding-learning"><div className="understanding-section-head"><div><h3>실행하며 알아가는 나</h3><p>{context.learning.since}–{today} · 실제 기록으로 확인한 변화입니다.</p></div></div><div className="learning-grid"><article><span className="goal-kicker">예상과 실제 소요 시간</span><h4>{context.learning.factor?`예상 시간의 ${context.learning.median}배`:'아직 시간을 배우는 중'}</h4><p>{context.learning.factor?`실제 소요 시간을 남긴 완료 ${context.learning.samples}건의 중앙값입니다. 계획 보정은 0.5~2배 범위에서 적용합니다.`:`현재 ${context.learning.samples}건. 실제 시간을 남긴 완료 기록이 5건 이상 쌓이면 보정치를 보여드립니다.`}</p><details><summary>계산에 사용한 퀘스트</summary>{context.learning.taskIds.length?context.learning.taskIds.map(id=><button className="text-button" key={id} onClick={()=>onOpen({kind:'task',id})}>{data.tasks.find(t=>t.id===id)?.title}</button>):<p>집중 세션을 마치며 실제 시간과 결과를 남겨주세요.</p>}{context.learning.samples>30&&<small>최근 30건을 표시했습니다. 계산에는 조건에 맞는 전체 기록을 사용합니다.</small>}</details></article><article><span className="goal-kicker">자주 남긴 미완료 이유</span><h4>{context.learning.topFriction?`${frictionNames[context.learning.topFriction.reason]} · ${context.learning.topFriction.count}건`:'막힌 이유를 함께 찾아갑니다'}</h4><p>사용자가 기록한 미완료 이유입니다. 성격을 단정하지 않고 다음 실행 방법을 조정하는 단서로 사용합니다.</p>{context.learning.topFriction&&<button className="text-button" disabled={demo} onClick={()=>onAsk(`최근 미완료 이유 '${frictionNames[context.learning.topFriction!.reason]}'가 ${context.learning.topFriction!.count}건 있었어. 관련 퀘스트 ${context.learning.topFriction!.taskIds.join(', ')}와 지금 목표를 확인해 막힌 부분을 줄일 방법을 제안해 줘.`)}>다음에는 어떻게 해볼까요? <ArrowUpRight size={14}/></button>}</article></div>{context.rules.length>0&&<p className="quest-note">내가 정한 개선 규칙 {context.rules.length}개도 계속 참고합니다. <button className="text-button" onClick={()=>navigate('review')}>회고에서 관리</button></p>}</section>
  <section className="personal-conversations"><h3>이전 대화에서 이어가기</h3><p>다른 대화방에 남긴 내 말을 찾습니다. 가져온 외부 AI 대화는 개인 위키에서 검색할 수 있습니다.</p><form onSubmit={e=>{e.preventDefault();void search()}} className="personal-search"><Search size={17}/><input id="personal-conversation-search" value={query} maxLength={200} onChange={e=>setQuery(e.target.value)} placeholder="목표, 관심사, 자주 막힌 일 검색"/><button className="secondary-button" disabled={demo||searching}>{searching?'검색 중…':'검색'}</button></form>{error&&<p role="alert" className="agent-error">{error}</p>}{results!==null&&<div className="personal-search-results">{!results.length?<p>일치하는 대화가 없습니다.</p>:results.map(r=><article key={r.id}><div><strong>{r.title}</strong><time>{r.date.slice(0,10)}</time></div><p><b>나</b> {r.user}</p>{r.assistant&&<details><summary>당시 AI 답변 · 사실 확인은 별도</summary><p>{r.assistant}</p></details>}<button className="text-button" onClick={()=>{navigate('agent');window.dispatchEvent(new CustomEvent('orbit:open-chat',{detail:{id:r.conversationId}}))}}>대화 이어가기 <ArrowUpRight size={14}/></button></article>)}<small>검색 결과는 최근 12건까지 표시합니다. 더 구체적인 검색어로 범위를 좁힐 수 있습니다.</small></div>}</section>
  {editing&&<MemoryEditor memory={editing} data={data} disabled={disabled} perform={perform} onClose={()=>setEditing(null)}/>}
  {importing&&<ImportRecord data={data} today={today} disabled={disabled} perform={perform} onClose={()=>setImporting(false)}/>}
  {deleting&&<Dialog open onOpenChange={open=>{if(!open&&!busy)setDeleting(null)}}><DialogContent><DialogHeader><DialogTitle>이 기억을 지울까요?</DialogTitle><DialogDescription>{deleting.statement}</DialogDescription></DialogHeader><p>이후 대화와 제안의 기억 목록에서 제외됩니다. 원래 기록은 그대로 보관합니다.</p><button className="primary-button" disabled={disabled} onClick={async()=>{if(await perform({type:'memory.delete',id:deleting.id},'기억을 지웠습니다.'))setDeleting(null)}}>기억 삭제</button></DialogContent></Dialog>}
 </div>;
}
function MemoryEditor({memory,data,disabled,perform,onClose}:{memory:Partial<PersonalMemory>;data:WorkspaceData;disabled:boolean;perform:Perform;onClose:()=>void}){
 const [error,setError]=useState(''),[pending,setPending]=useState(false),[kind,setKind]=useState<PersonalMemory['kind']>(memory.kind??'preference'),[origin,setOrigin]=useState<PersonalMemory['origin']>(memory.origin??'user');
 const refs=[...data.notes.map(n=>({key:'note:'+n.id,label:n.title,ref:{kind:'note' as const,id:n.id,revision:n.revision??1}})),...data.tasks.map(t=>({key:'task:'+t.id,label:t.title,ref:{kind:'task' as const,id:t.id}})),...data.reviews.slice(-14).map(r=>({key:'review:'+r.date,label:r.date+' 회고',ref:{kind:'review' as const,id:r.date}}))];
 return <Dialog open onOpenChange={open=>{if(!open&&!pending)onClose()}}><DialogContent><DialogHeader><DialogTitle>{memory.id?'기억을 다시 확인하기':'Orbit에 알려주고 싶은 나'}</DialogTitle><DialogDescription>확인한 기억을 다음 대화와 제안에 사용합니다. 연결 기록이 바뀌면 재확인을 요청합니다.</DialogDescription></DialogHeader><form className="dialog-form" onSubmit={async e=>{e.preventDefault();const f=new FormData(e.currentTarget),sources=f.getAll('source').map(String).map(key=>refs.find(r=>r.key===key)!.ref);if(sources.length>6||origin==='records'&&!sources.length){setError(sources.length>6?'연결 기록은 최대 6개까지 선택해 주세요.':'실행·기록에서 확인한 기억은 근거 기록을 선택해 주세요.');return}setError('');setPending(true);try{if(await perform({type:'memory.upsert',memory:{id:memory.id??crypto.randomUUID(),statement:String(f.get('statement')),kind:origin==='saju'?'reflection':kind,origin,sources}},'확인한 기억을 저장했습니다.'))onClose()}finally{setPending(false)}}}><label>기억할 내용<textarea className="form-field" name="statement" defaultValue={memory.statement} required maxLength={600} rows={3}/></label><div className="chief-fields"><label>종류<select className="form-field" value={origin==='saju'?'reflection':kind} disabled={origin==='saju'} onChange={e=>setKind(e.target.value as PersonalMemory['kind'])}>{Object.entries(kinds).map(([id,label])=><option key={id} value={id}>{label}</option>)}</select></label><label>어디에서 알게 되었나요?<select className="form-field" value={origin} onChange={e=>setOrigin(e.target.value as PersonalMemory['origin'])}><option value="user">내가 직접 알려주는 내용</option><option value="records">실행·기록에서 확인</option><option value="saju">사주·자기 탐색 해석</option></select></label></div><fieldset className="quest-prerequisites"><legend>연결 기록 · 최대 6개{origin==='records'?' (필수)':''}</legend>{refs.map(r=><label key={r.key}><input type="checkbox" name="source" value={r.key} defaultChecked={memory.sources?.some(s=>s.kind===r.ref.kind&&s.id===r.ref.id)}/>{r.label}</label>)}</fieldset><p className="quest-note">사주 해석은 자기 탐색을 위한 참고로만 보관하며, 건강이나 목표 성과를 예측하는 근거로 사용하지 않습니다.</p><p role={error?'alert':undefined} className="agent-error">{error}</p><button className="primary-button" disabled={disabled||pending}><Check size={15}/> 확인하고 기억하기</button></form></DialogContent></Dialog>;
}
function ImportRecord({data,today,disabled,perform,onClose}:{data:WorkspaceData;today:string;disabled:boolean;perform:Perform;onClose:()=>void}){
 const [body,setBody]=useState(''),[title,setTitle]=useState(''),[kind,setKind]=useState('personal'),[pending,setPending]=useState(false),[error,setError]=useState('');
 return <Dialog open onOpenChange={open=>{if(!open&&!pending)onClose()}}><DialogContent><DialogHeader><DialogTitle>흩어진 기록을 나의 위키로</DialogTitle><DialogDescription>텍스트를 붙여 넣거나 .txt / .md 파일을 선택하세요. 외부 AI 계정의 전체 대화가 자동 연결되는 기능은 아닙니다.</DialogDescription></DialogHeader><form className="dialog-form" onSubmit={async e=>{e.preventDefault();setError('');if(!body.trim()){setError('가져올 내용을 입력해 주세요.');return}const id=crypto.randomUUID(),project=data.projects.find(p=>p.name==='나를 이해하는 기록')??{id:crypto.randomUUID(),name:'나를 이해하는 기록',goal:'나의 맥락과 실천 방법을 이해하는 개인 기록',color:'#6554dc',symbol:'O',due:today,priority:3};const tags=kind==='saju'?['자기탐색','사주']:kind==='llm'?['AI대화','가져온기록']:['자기탐색'];setPending(true);try{if(await perform({type:'wiki.import',project,notes:[{id,title,kind:'wiki',projectId:project.id,summary:kind==='saju'?'사주·자기 탐색 해석 자료. 객관적 예측 자료가 아닙니다.':kind==='llm'?'사용자가 가져온 AI 대화. 사용자 발언과 AI의 해석을 구분해서 읽습니다.':body.slice(0,200),body,tags,updated:today,source:{provider:'manual',externalId:id,date:today},wiki:{aliases:[],links:[],sources:[],private:true,importedFrom:'personal-text'}}]},'개인 위키에 기록을 저장했습니다.'))onClose()}finally{setPending(false)}}}><label>자료 종류<select className="form-field" value={kind} onChange={e=>setKind(e.target.value)}><option value="personal">자기 탐색·개인 기록</option><option value="saju">사주 해석 자료</option><option value="llm">다른 AI와 나눈 대화</option></select></label><label>제목<input className="form-field" required maxLength={160} value={title} onChange={e=>setTitle(e.target.value)}/></label><label className="text-button">텍스트 파일 선택<input type="file" accept=".txt,.md,text/plain,text/markdown" onChange={async e=>{const file=e.target.files?.[0];if(!file)return;if(file.size>400000){setError('텍스트 파일은 400KB 이하로 선택해 주세요.');return}try{const text=await file.text();if(text.length>100000){setError('10만 자 이하의 자료를 선택해 주세요.');return}setBody(text);if(!title)setTitle(file.name.replace(/\.(txt|md)$/i,'').slice(0,160));setError('')}catch{setError('파일을 읽지 못했습니다. 내용을 붙여 넣어 주세요.')}}}/></label><label>내용<textarea className="form-field" value={body} onChange={e=>setBody(e.target.value)} maxLength={100000} rows={8} required/></label>{error&&<p role="alert" className="agent-error">{error}</p>}<button className="primary-button" disabled={disabled||pending||!body.trim()}><Upload size={15}/> 위키에 가져오기</button></form></DialogContent></Dialog>;
}
