'use client';
import {useMemo} from 'react';
import {ArrowUpRight,ArrowRight,Target,CalendarDays,Check,CheckCheck,Clock3,Flag,FolderKanban,Heart,Play,Sparkles,BookOpen,AlertCircle,Orbit,Plus} from 'lucide-react';
import {Progress} from '@/components/ui/progress';
import {workspaceDashboard} from '@/lib/orbit/dashboard';
import {questReadiness} from '@/lib/orbit/pacemaker';
import {domainLabels} from '@/lib/orbit/chief';
import {formatTime,durationText,type WorkspaceData,type View} from '@/lib/orbit/model';
import {koreanDate,addDays} from '@/lib/orbit/dates';
import type {WorkspaceAction} from '@/lib/orbit/validation';
type Open=(target:{kind:'task'|'project'|'note'|'event';id:string})=>void;
type Props={data:WorkspaceData;now:Date;busy:boolean;demo:boolean;perform:(action:WorkspaceAction,message?:string)=>Promise<boolean>;navigate:(view:View)=>void;onOpen:Open;onGoals:()=>void;onCreate:()=>void;onAsk:(text:string)=>void;onCalendar:(date:string)=>void;onProposal:(date:string)=>void;onCoachSettings:()=>void};
const energyLabels={low:'여유롭게',normal:'평소처럼',high:'집중해서',unknown:'컨디션 미확인'};
const metricStatus={'unknown':'수치 확인 필요','behind':'경로 점검','on-track':'기준 페이스 유지','confirm':'달성 확인 필요','achieved':'달성','paused':'보류'};
export function WorkspaceDashboard({data,now,busy,demo,perform,navigate,onOpen,onGoals,onCreate,onAsk,onCalendar,onProposal,onCoachSettings}:Props){
  const d=useMemo(()=>workspaceDashboard(data,now),[data,now]),disabled=busy||demo;
  const primary=d.chief.primary,next=d.active??(primary.taskId?data.tasks.find(t=>t.id===primary.taskId):undefined),canStart=next&&questReadiness(data,next,d.today).canStart;
  const max=Math.max(1,...d.week.map(day=>day.count)),weekTotal=d.week.reduce((sum,day)=>sum+day.count,0);
  const goalRows=[...d.goals].sort((a,b)=>Number(['paused','achieved'].includes(a.goal.status??'active'))-Number(['paused','achieved'].includes(b.goal.status??'active'))).slice(0,4);
  return <div className="workspace-dashboard">
    <div className="wd-toolbar"><div><CalendarDays size={16}/><span>{koreanDate(d.today)}</span><span className="wd-zone">{data.preferences.timeZone}</span></div><button className="secondary-button" onClick={onGoals}><Target size={16}/>목표 관리</button></div>
    <div className="wd-metrics">
      <button onClick={()=>navigate('goals')}><span><Target size={17}/>진행 중인 목표</span><strong>{d.activeGoals.length}<small>개</small></strong><p>일과 삶의 원하는 변화 <ArrowUpRight size={14}/></p></button>
      <button onClick={()=>navigate('today')}><span><Flag size={17}/>오늘의 집중 업무</span><strong>{d.focusTasks.filter(t=>t.status!=='done').length}<small>개 남음</small></strong><p>지정·승인된 {d.focusTasks.length}개 기준 <ArrowUpRight size={14}/></p></button>
      <button onClick={()=>navigate('today')}><span><CheckCheck size={17}/>오늘 완료</span><strong>{d.completed.length}<small>개</small></strong><p>완료일이 오늘인 업무 <ArrowUpRight size={14}/></p></button>
      <button onClick={()=>document.getElementById('dashboard-attention')?.scrollIntoView({behavior:'smooth',block:'start'})}><span><AlertCircle size={17}/>확인할 업무</span><strong>{d.attention.length}<small>개</small></strong><p>기한 경과·선행 대기·재확인 <ArrowRight size={14}/></p></button>
    </div>
    <div className="wd-grid">
      <section className={'wd-next wd-panel '+(['recovery','rest'].includes(primary.kind)?'is-recovery':'')} aria-labelledby="dashboard-next">
        <div className="wd-section-label"><Orbit size={18}/><span>지금, 궤도를 지키는 한 걸음</span></div>
        <h2 id="dashboard-next">{primary.title}</h2><p>{primary.reason}</p><div className="wd-next-step">{primary.next}</div>
        <div className="wd-actions">{next&&<button className="primary-button" disabled={disabled||(!d.active&&!canStart)} onClick={async()=>{if(d.active){onOpen({kind:'task',id:next.id});return}if(await perform({type:'task.start',id:next.id},'집중 세션을 시작했습니다.'))onOpen({kind:'task',id:next.id})}}><Play size={16}/>{d.active?'진행 중인 집중 기록':'집중 시작'}</button>}
          {primary.kind==='care'&&primary.routineId&&<button className="primary-button" disabled={disabled} onClick={()=>void perform({type:'care.check',id:primary.routineId!,checked:true},'오늘의 실천을 기록했습니다.')}><Check size={16}/>실천 완료</button>}
          <button className={next||primary.kind==='care'?'secondary-button':'primary-button'} disabled={demo} onClick={()=>onAsk(primary.ask)}><Sparkles size={16}/>Orbit과 정리하기</button>
        </div>
        <div className="wd-next-footer"><span>{energyLabels[d.chief.energy]}</span><button className="text-button" onClick={onCoachSettings}>컨디션·페이스 설정 <ArrowUpRight size={14}/></button></div>
      </section>
      <section className="wd-panel wd-time" aria-labelledby="dashboard-time"><div className="wd-panel-head"><h2 id="dashboard-time">오늘의 여유</h2><Clock3 size={18}/></div><strong className="wd-time-value">{durationText(d.chief.capacity)}</strong><p>지금부터 업무 종료까지<br/>일정·돌봄·여유분을 제외한 시간</p><div className="wd-time-demand"><span>아직 배치하지 않은 마감·집중 업무</span><strong>{durationText(d.chief.demand)}</strong></div>{d.chief.overloaded&&<div className="wd-load-notice">남은 시간에 맞춰 범위를 조정해 보세요.</div>}<button className="text-button" onClick={()=>onCalendar(d.today)}>시간 배치 확인 <ArrowUpRight size={14}/></button></section>
      <section className="wd-panel wd-goals" aria-labelledby="dashboard-goals"><div className="wd-panel-head"><h2 id="dashboard-goals">목표의 현재 위치</h2><button className="text-button" onClick={()=>navigate('goals')}>전체 목표 <ArrowUpRight size={14}/></button></div>
        {goalRows.length?goalRows.map(({goal,done,total,pace})=>{const p=goal.progress,dated=p&&p.updatedOn<=d.today,ratio=dated&&p.target!==p.baseline?Math.max(0,Math.min(100,100*(p.current-p.baseline)/(p.target-p.baseline))):0;return <button className="wd-goal-row" key={goal.id} onClick={()=>navigate('goals')}><div className="wd-goal-meta"><span>{domainLabels[goal.domain??'work']}</span><span className={'wd-pace '+pace.status}>{goal.status==='paused'?'보류':metricStatus[pace.status]}</span></div><h3>{goal.sentence}</h3><div className="wd-goal-numbers"><span>{dated?`${p.current} / ${p.target} ${p.unit}`:'성과 수치 미확인'}</span><span>퀘스트 {done}/{total}</span></div><Progress value={ratio} aria-label={goal.sentence+' 마지막 기록 수치 진척'}/><small>{dated?`${p.updatedOn} 마지막 기록`:'현재 위치를 직접 확인해 주세요.'}{goal.deadline?' · '+goal.deadline+' 목표':''}</small></button>}):<div className="wd-empty"><Target size={26}/><p>원하는 변화부터 하나 정해볼까요?</p><button className="secondary-button" onClick={onGoals}><Plus size={15}/>첫 목표 만들기</button></div>}
        <p className="wd-footnote">성과는 직접 기록한 수치입니다. 퀘스트 완료율과 구분해 확인합니다.</p>
      </section>
      <section className="wd-panel wd-agenda" aria-labelledby="dashboard-agenda"><div className="wd-panel-head"><h2 id="dashboard-agenda">오늘의 흐름</h2><button className="text-button" onClick={()=>onCalendar(d.today)}>일정 열기 <ArrowUpRight size={14}/></button></div><p className="wd-source-note">저장된 일정 기준 · 일정 화면에서 연결 캘린더를 갱신합니다.</p>
        {d.todayEvents.length?<ol className="wd-event-list">{d.todayEvents.slice(0,6).map(e=><li key={e.id} className={e.end<=d.chief.minute?'is-past':e.start<=d.chief.minute?'is-current':''}><time>{formatTime(e.start)}<small>{formatTime(e.end)}</small></time><button onClick={()=>onOpen({kind:'event',id:e.id})}><strong>{e.title}</strong><span>{e.kind==='focus'?'집중':e.kind==='break'?'휴식':'일정'}{e.projectId?' · '+(data.projects.find(p=>p.id===e.projectId)?.name??'프로젝트'):''}{e.start<=d.chief.minute&&e.end>d.chief.minute?' · 진행 중':''}</span></button></li>)}</ol>:<div className="wd-inline-empty">오늘 등록된 일정이 없습니다.</div>}{d.todayEvents.length>6&&<button className="text-button" onClick={()=>onCalendar(d.today)}>나머지 {d.todayEvents.length-6}개 일정 보기</button>}
        {d.upcoming.length>0&&<div className="wd-upcoming"><h3>다음 일정</h3>{d.upcoming.slice(0,2).map(e=><button key={e.id} onClick={()=>onCalendar(e.date)}><span>{e.date.slice(5).replace('-','/')} · {formatTime(e.start)}</span><strong>{e.title}</strong><ArrowUpRight size={14}/></button>)}</div>}
      </section>
      <section id="dashboard-attention" className="wd-panel wd-attention" aria-labelledby="dashboard-attention-title"><div className="wd-panel-head"><h2 id="dashboard-attention-title">막힌 곳을 풀어가는 시간</h2><button className="text-button" onClick={()=>navigate('tasks')}>할 일 전체 <ArrowUpRight size={14}/></button></div>
        {d.attention.length?d.attention.slice(0,4).map(t=><button className="wd-attention-row" key={t.id} onClick={()=>onOpen({kind:'task',id:t.id})}><AlertCircle size={17}/><div><strong>{t.title}</strong><p>{t.due<d.today?`${t.due} 기한 경과 · `:''}{t.checkDate&&t.checkDate<=d.today?`${t.checkDate} 재확인 · `:''}{questReadiness(data,t,d.today).reason}</p></div><ArrowUpRight size={15}/></button>):<div className="wd-inline-empty">기한이 지났거나 확인을 기다리는 업무가 없습니다.</div>}
        <div className="wd-ready"><h3>시작할 수 있는 다음 업무 <span>{d.ready.length}</span></h3>{d.ready.filter(t=>t.id!==d.active?.id).slice(0,3).map(t=><button key={t.id} onClick={()=>onOpen({kind:'task',id:t.id})}><span>{t.title}</span><small>{t.duration}분</small><ArrowUpRight size={14}/></button>)}{!d.ready.length&&<p>진행 중인 집중이나 선행 조건을 확인해 주세요.</p>}<button className="text-button" onClick={onCreate}><Plus size={15}/>새 할 일</button></div>
      </section>
      <section className="wd-panel wd-care" aria-labelledby="dashboard-care"><div className="wd-panel-head"><h2 id="dashboard-care">나를 위한 페이스</h2><Heart size={18}/></div><p className="wd-source-note">건강·마음·배움도 목표를 지탱하는 실행입니다.</p>{d.care.length?d.care.map(({routine:r})=>{const done=r.log.includes(d.today);return <div className="wd-care-row" key={r.id}><div><strong>{r.title}</strong><span>{domainLabels[r.domain]} · {formatTime(r.start)} · {r.minutes}분</span></div><button className={'secondary-button '+(done?'is-done':'')} aria-pressed={done} disabled={disabled} onClick={()=>void perform({type:'care.check',id:r.id,checked:!done},done?'실천 완료를 취소했습니다.':'오늘의 실천을 기록했습니다.')}><Check size={15}/>{done?'완료':'완료하기'}</button></div>}):<div className="wd-inline-empty">오늘 등록된 돌봄·학습 루틴이 없습니다.</div>}<button className="text-button" onClick={onCoachSettings}>돌봄·학습 루틴 관리 <ArrowUpRight size={14}/></button>
        <div className="wd-week"><div><h3>최근 7일의 실행</h3><strong>{weekTotal}<small>개 완료</small></strong></div><div className="wd-week-chart" role="img" aria-label={'날짜별 완료 업무: '+d.week.map(day=>day.date+' '+day.count+'개').join(', ')}>{d.week.map(day=><div key={day.date} title={day.date+' · '+day.count+'개'}><span>{day.count}</span><div className="wd-week-track"><i style={{height:`${day.count/max*100}%`}}/></div><time>{day.date.slice(8)}</time></div>)}</div><small>현재 완료 상태인 업무의 완료일 기준입니다.</small></div>
      </section>
      <section className="wd-panel wd-projects" aria-labelledby="dashboard-projects"><div className="wd-panel-head"><h2 id="dashboard-projects">프로젝트 현황</h2><button className="text-button" onClick={()=>navigate('projects')}>연결 그래프 <ArrowUpRight size={14}/></button></div><div className="wd-project-grid">{d.projects.slice(0,4).map(({project:p,total,done,blocked})=><button key={p.id} onClick={()=>onOpen({kind:'project',id:p.id})}><div><FolderKanban size={19} style={{color:p.color}}/><strong>{p.name}</strong><ArrowUpRight size={14}/></div><p>{p.goal||'최종 결과물을 정해 주세요.'}</p><Progress value={total?done/total*100:0} aria-label={p.name+' 등록 업무 완료율'}/><span>등록 업무 {done}/{total} 완료{blocked?` · 대기 ${blocked}`:''}</span></button>)}</div>{!d.projects.length&&<div className="wd-inline-empty">프로젝트를 등록하면 연결된 업무 진행을 보여드립니다.</div>}</section>
    </div>
    <div className="wd-bottom"><button onClick={()=>navigate('wiki')}><BookOpen size={20}/><div><strong>쌓인 기록에서 답을 찾습니다</strong><span>개인 위키·회의록·지식 {data.notes.length}개</span></div><ArrowUpRight size={17}/></button><button onClick={()=>onProposal(addDays(d.today,1))}><Sparkles size={20}/><div><strong>다음 한 걸음을 설계합니다</strong><span>내일의 원페이지 실행 제안</span></div><ArrowUpRight size={17}/></button></div>
  </div>;
}
