'use client';
import {useCallback,useEffect,useRef,useState} from 'react';
import {Bell,CheckCheck,CheckCircle2,AlertCircle,Clock3} from 'lucide-react';
import {toast} from 'sonner';
import {Dialog,DialogContent,DialogHeader,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import type {OrbitNotification} from '@/lib/orbit/notifications/store';
import {clientRequest} from '@/lib/orbit/agent/client-request';
type Inbox={items:OrbitNotification[];unread:number;publicKey:string;serverTime:string;hasMore:boolean;subscriptions:{id:string;error:string}[]};
const bytes=(s:string)=>Uint8Array.from(atob(s.replace(/-/g,'+').replace(/_/g,'/')+'='.repeat((4-s.length%4)%4)),c=>c.charCodeAt(0));
export function NotificationCenter({ownerId,demo}:{ownerId:string;demo:boolean}){
 const [open,setOpen]=useState(false),[data,setData]=useState<Inbox|null>(null),[error,setError]=useState(''),[busy,setBusy]=useState(false),[push,setPush]=useState(false),[supported,setSupported]=useState(false),[filter,setFilter]=useState('all');
 const seen=useRef<Set<string>|null>(null),scope=useRef(ownerId);scope.current=ownerId;
 const request=useCallback((method='GET',body?:unknown,suffix='')=>clientRequest('/api/notifications'+suffix,method,body),[ownerId]);
 const refresh=useCallback(async()=>{const current=ownerId;try{const next=await request() as Inbox;if(scope.current!==current)return;setData(next);setError('');if('serviceWorker'in navigator&&'PushManager'in window){const reg=await navigator.serviceWorker.getRegistration('/'),sub=await reg?.pushManager.getSubscription();if(sub){const hash=new Uint8Array(await crypto.subtle.digest('SHA-256',new TextEncoder().encode(sub.endpoint))),id=btoa(String.fromCharCode(...hash)).replace(/\+/g,'-').replace(/\//g,'_').replace(/=+$/,'');setPush(next.subscriptions.some(s=>s.id===id));}else setPush(false);}const fresh=next.items.filter(n=>!n.readAt&&!seen.current?.has(n.id));if(seen.current&&fresh.length){const n=fresh[0];toast(n.title,{description:fresh.length>1?`새 알림 ${fresh.length}건` : n.body.slice(0,100),action:{label:'확인',onClick:()=>setOpen(true)}});}seen.current=new Set([...(seen.current??[]),...next.items.map(n=>n.id)]);const nav=navigator as Navigator&{setAppBadge?:(n:number)=>Promise<void>;clearAppBadge?:()=>Promise<void>};if(next.unread)void nav.setAppBadge?.(next.unread).catch(()=>{});else void nav.clearAppBadge?.().catch(()=>{});}catch(e){if(scope.current===current)setError((e as Error).message)}},[ownerId,request]);
 useEffect(()=>{if(demo)return;seen.current=null;setData(null);void refresh();const poll=setInterval(()=>{if(document.visibilityState==='visible')void refresh()},12000);const onFocus=()=>void refresh();window.addEventListener('focus',onFocus);const support='serviceWorker'in navigator&&'PushManager'in window&&'Notification'in window;setSupported(support);if(support){navigator.serviceWorker.addEventListener('message',onFocus);}setOpen(new URLSearchParams(location.search).has('notifications'));return()=>{clearInterval(poll);window.removeEventListener('focus',onFocus);if(support)navigator.serviceWorker.removeEventListener('message',onFocus)}},[demo,refresh]);
 async function enable(){setBusy(true);setError('');try{const permission=await Notification.requestPermission();if(permission!=='granted')throw new Error('기기 설정에서 ORBIT 알림을 허용해 주세요. 앱 안의 알림함은 계속 사용할 수 있습니다.');const reg=await navigator.serviceWorker.register('/sw.js',{scope:'/'});await navigator.serviceWorker.ready;let sub=await reg.pushManager.getSubscription();if(sub){const expected=bytes(data!.publicKey),actual=new Uint8Array(sub.options.applicationServerKey??new ArrayBuffer(0));if(expected.length!==actual.length||expected.some((v,i)=>v!==actual[i])){await sub.unsubscribe();sub=null;}}if(!sub)sub=await reg.pushManager.subscribe({userVisibleOnly:true,applicationServerKey:bytes(data!.publicKey)});const value=sub.toJSON();await request('POST',{action:'subscribe',subscription:{endpoint:sub.endpoint,keys:value.keys}});setPush(true);await request('POST',{action:'test'});await refresh();}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
 async function disable(){setBusy(true);try{const reg=await navigator.serviceWorker.getRegistration('/'),sub=await reg?.pushManager.getSubscription();if(sub){await request('POST',{action:'unsubscribe',endpoint:sub.endpoint});await sub.unsubscribe();}setPush(false)}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
 async function visit(n:OrbitNotification){try{await request('POST',{action:'read',ids:[n.id]});location.assign(n.href)}catch(e){setError((e as Error).message)}}
 async function readAll(){if(!data)return;try{await request('POST',{action:'read',ids:[],through:data.serverTime});await refresh()}catch(e){setError((e as Error).message)}}
 if(demo)return null;
 return <><button className="icon-button notification-bell" aria-label={`알림함${data?.unread?' · 읽지 않은 알림 '+data.unread+'건':''}`} onClick={()=>{setOpen(true);void refresh()}}><Bell size={20}/>{!!data?.unread&&<span>{data.unread>99?'99+':data.unread}</span>}</button>
 <Dialog open={open} onOpenChange={setOpen}><DialogContent className="notification-dialog"><DialogHeader><DialogTitle>알림함 {data?.unread?`· ${data.unread}`:''}</DialogTitle><DialogDescription>회의 요약, 승인 요청, 업무 완료와 실패를 확인하세요.</DialogDescription></DialogHeader>
 <div className="notification-controls"><button className="text-button" onClick={()=>void readAll()} disabled={!data?.unread}><CheckCheck size={16}/>모두 읽음</button>{supported?<button className="secondary-button" disabled={busy||!data} onClick={()=>void(push?disable():enable())}>{push?'이 기기 알림 끄기':'기기 알림 켜기'}</button>:<p className="form-hint">기기 알림은 지원되는 브라우저에서 설정할 수 있습니다.</p>}{push&&<button className="text-button" disabled={busy} onClick={()=>void request('POST',{action:'test'}).then(refresh).catch(e=>setError(e.message))}>테스트 알림</button>}</div>
 {error&&<p role="alert" className="note-error">{error}</p>}{data?.subscriptions.some(s=>s.error)&&<p role="status" className="note-error">일부 기기에 알림을 보내지 못해 재시도 중입니다. 기기 알림 설정과 테스트 알림을 확인해 주세요.</p>}
 <div className="notification-filters" aria-label="알림 필터">{[['all','전체'],['approval','승인 요청'],['failed','실패'],['unread','읽지 않음']].map(([key,label])=><button key={key} aria-pressed={filter===key} className={filter===key?'active':''} onClick={()=>setFilter(key)}>{label}</button>)}</div>
 <div className="notification-list" aria-live="polite">{data?.items.filter(n=>filter==='all'||filter==='unread'&&!n.readAt||n.kind===filter).map(n=><button key={n.id} className={'notification-item '+(n.readAt?'read':'unread')} onClick={()=>void visit(n)}>{n.kind==='failed'?<AlertCircle size={20}/>:n.kind==='approval'?<Clock3 size={20}/>:n.kind==='completed'?<CheckCircle2 size={20}/>:<Bell size={20}/>}<span><strong>{n.title}</strong><p>{n.body}</p><small>{new Date(n.createdAt).toLocaleString('ko-KR')}</small></span>{!n.readAt&&<i aria-label="읽지 않음"/>}</button>)}{!data?<p>알림을 불러오는 중입니다.</p>:!data.items.length?<p className="empty-state">새 알림이 없습니다. 회의록이 등록되거나 업무 상태가 바뀌면 여기서 알려드립니다.</p>:null}</div>
 {data?.hasMore&&<button className="text-button" onClick={()=>void request('GET',undefined,'?before='+encodeURIComponent(data.items.at(-1)!.createdAt)).then((v:any)=>setData({...data,items:[...data.items,...v.items],hasMore:v.hasMore})).catch(e=>setError(e.message))}>이전 알림 더 보기</button>}
 </DialogContent></Dialog></>;
}
