'use client';
import {useEffect,useState} from 'react';
import {Mic,RefreshCw,ArrowUpRight} from 'lucide-react';
import {agentRequest} from './agent/connections';
import type {Project} from '@/lib/orbit/model';
type Status={connected:boolean;total:number;ready:number;state:{failed?:{id:string;error:string}[];enabled:boolean;queue:string[];page:number;backfillComplete:boolean;lastSync?:string;error?:string};records:{id:string;title:string;status:string;noteIds:string[];manualProject?:string;autoPrimary?:string;matches:{projectId:string;name:string;matched:string[]}[]}[]};
export function PlaudPanel({projects,onRefresh,onOpen,onAsk}:{projects:Project[];onRefresh:()=>Promise<void>;onOpen:(id:string)=>void;onAsk:(text:string)=>void}){
 const [data,setData]=useState<Status|null>(null),[error,setError]=useState(''),[busy,setBusy]=useState(false),[expanded,setExpanded]=useState(false),[editing,setEditing]=useState(''),[project,setProject]=useState(''),[keyword,setKeyword]=useState('');
 async function load(){try{setData(await agentRequest('/api/meetings'));setError('')}catch(e){setError((e as Error).message)}}
 useEffect(()=>{void load();const id=setInterval(()=>void load(),30000);return()=>clearInterval(id)},[]);
 async function run(value:unknown){setBusy(true);setError('');try{setData(await agentRequest('/api/meetings','POST',value));await onRefresh();setEditing('')}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
 async function connect(){setBusy(true);try{const r=await agentRequest('/api/integrations/connect','POST',{provider:'plaud'});const url=new URL(r.url);if(url.origin!=='https://mcp.plaud.ai')throw new Error('연결 주소를 확인하지 못했습니다.');location.assign(url.href)}catch(e){setError((e as Error).message);setBusy(false)}}
 return <section className="plaud-panel"><div className="plaud-panel-heading"><Mic size={22}/><div><strong>회의록에서 요약과 결재까지</strong><p>{data?`${data.total}개 회의 보관 · 원문·요약 준비 ${data.ready}개`:'회의 보관함 확인 중'}</p></div><button className="text-button" onClick={()=>setExpanded(v=>!v)}>{expanded?'접기':'회의 요약·결재 보기'}</button></div>
 {data&&!data.connected?<div className="plaud-panel-actions"><p>ORBIT에서 Plaud를 연결하면 원문을 가져와 핵심 요약과 승인할 업무를 자동으로 준비합니다.</p><button className="secondary-button" disabled={busy} onClick={()=>void connect()}>Plaud {data.total?'다시 ':''}연결 <ArrowUpRight size={15}/></button></div>:data&&<div className="plaud-panel-actions"><span>{!data.state.enabled?'자동 수집 일시 정지':data.state.queue.length?'회의록을 순서대로 가져오는 중':data.state.backfillComplete?'전체 목록 1회 확인 · 새 회의와 변경 내용 재확인':'기존 회의록 수집 대기'}{data.state.lastSync&&' · 최근 저장 '+new Date(data.state.lastSync).toLocaleString('ko-KR')}</span><button className="secondary-button" disabled={busy||!data.state.enabled} onClick={()=>void run({action:'sync'})}><RefreshCw size={15}/>{busy?'확인 중…':'지금 가져오기'}</button></div>}
 {error&&<p role="alert">{error}</p>}{data?.state.error&&<p role="alert">{data.state.error} 저장한 진행 위치부터 다시 시도합니다.</p>}
 {!!data?.state.failed?.length&&<p role="status">다시 확인할 회의 {data.state.failed.length}개 · 나머지 회의는 계속 수집합니다.</p>}
 {expanded&&data&&<div className="plaud-details"><p>한 회의가 여러 프로젝트와 관련되면 태그를 함께 붙입니다. 확실하지 않은 연결은 회의 보관함에 남깁니다. 원문·AI 요약·사용자 피드백을 구분하여 답변에 참고합니다.</p><button className="text-button" disabled={busy} onClick={()=>void run({action:'settings',enabled:!data.state.enabled})}>{data.state.enabled?'자동 수집 잠시 멈추기':'자동 수집 다시 시작'}</button>{data.records.map(r=><article key={r.id}><button className="text-button" disabled={!r.noteIds.length||r.status==='excluded'} onClick={()=>onOpen(r.noteIds[0])}>{r.title} <ArrowUpRight size={14}/></button><p>{r.manualProject?projects.find(p=>p.id===r.manualProject)?.name:r.matches.length?r.matches.map(m=>m.name).join(' · '):'프로젝트 확인 필요'} · {r.status==='ready'?'원문·요약 저장됨':r.status==='excluded'?'사용자가 삭제한 기록 · 재수집 제외':r.status==='partial'?'분할 원문 수집 중':'전사·요약 준비 중'}</p>{r.matches.length>0&&<small>연결 근거: {r.matches.flatMap(m=>m.matched).join(', ')}</small>}<div className="sheet-actions"><button className="secondary-button" disabled={!r.noteIds.length||r.status==='excluded'} onClick={()=>onOpen(r.noteIds[0])}>요약·결재 확인</button><button className="text-button" onClick={()=>{setEditing(r.id);setProject(r.manualProject??r.autoPrimary??'');setKeyword('')}}>프로젝트 수정</button><button className="text-button" onClick={()=>onAsk('회의록 “'+r.title+'”의 원문을 확인해서, 핵심 결정과 과거 관련 기록의 차이, 지금 할 행동 1가지를 근거와 함께 정리해 줘.')}>이 회의로 질문하기</button></div>{editing===r.id&&<form onSubmit={e=>{e.preventDefault();void run({action:'retag',id:r.id,projectId:project,keyword})}}><label>연결 프로젝트<select className="form-field" value={project} onChange={e=>setProject(e.target.value)} required><option value="">선택하세요</option>{projects.map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select></label><label>다음 회의에도 적용할 별칭 · 선택<input className="form-field" maxLength={40} value={keyword} onChange={e=>setKeyword(e.target.value)} placeholder="예: 매장명, 브랜드명"/></label><button className="secondary-button" disabled={busy||!project}>수정하고 기억하기</button></form>}</article>)}{data.records.length===20&&<p>최근 수집한 20개입니다. 전체 회의는 아래 기록 검색에서 Plaud로 찾을 수 있습니다.</p>}</div>}
 </section>;
}
