'use client';
import {categoryOf,calendarItemColor,categoryLabels} from '@/lib/orbit/calendar-categories';
import {projectTimeline,eventProjectReason} from '@/lib/orbit/project-context';
import {CityThemeButton} from './city-themes';
import {projectWorld} from '@/lib/orbit/project-world';
import {useEffect,useRef,useState,type ReactNode,type CSSProperties} from 'react';
import {Plus,Pencil,Trash2,Flag,Target,CalendarDays,FileText,CheckCheck,ChevronRight,MessageSquare,Settings2,MoreHorizontal,ChevronDown} from 'lucide-react';
import type {Project,ProjectMilestone,ProjectStatus,Task,WorkspaceData} from '@/lib/orbit/model';
import {formatTime,statusLabel} from '@/lib/orbit/model';
import type {WorkspaceAction} from '@/lib/orbit/validation';
import {projectSummary,projectStatus,projectDisplayStatus,projectStatusLabel,priorityLabel} from '@/lib/orbit/project-management';
import type {ProjectIntent} from './project-actions';
import {workEligibility} from '@/lib/orbit/work-policy';
import {Tabs,TabsList,TabsTrigger,TabsContent} from '@/components/ui/tabs';
import {Progress} from '@/components/ui/progress';
import {Checkbox} from '@/components/ui/checkbox';
import {Choice} from './choice';
import {AlertDialog,AlertDialogContent,AlertDialogHeader,AlertDialogTitle,AlertDialogDescription,AlertDialogFooter,AlertDialogCancel,AlertDialogAction} from '@/components/ui/alert-dialog';

type Props={intent?:ProjectIntent;onManage:()=>void;project:Project;data:WorkspaceData;today:string;busy:boolean;perform:(action:WorkspaceAction,message?:string)=>Promise<boolean>;onOpen:(kind:'task'|'note'|'event',id:string,revision?:number)=>void;onCreate:(kind:'task'|'event'|'meeting',projectId:string)=>void;onEdit:()=>void;onDelete:()=>void;onChat:()=>void;onEditing:(editing:boolean)=>void;followup:ReactNode};
export function ProjectDetailPanel({intent='overview',onManage,project:p,data,today,busy,perform,onOpen,onCreate,onEdit,onDelete,onChat,onEditing,followup}:Props){
  const s=projectSummary(data,p,today),state=projectDisplayStatus(p,data.tasks);
  const [tab,setTab]=useState(['settings','complete','resume'].includes(intent)?'overview':intent==='overview'&&state==='completed'?'overview':'tasks'),[settings,setSettings]=useState(intent==='settings'||intent==='complete'||intent==='resume'),[status,setStatus]=useState<ProjectStatus>(intent==='complete'?'completed':intent==='resume'?'active':state),[priority,setPriority]=useState(p.priority),[goalId,setGoalId]=useState(p.goalId??'none'),[result,setResult]=useState(p.result??''),[error,setError]=useState('');
  const [stage,setStage]=useState<ProjectMilestone|null>(null),[removeStage,setRemoveStage]=useState<ProjectMilestone|null>(null);
  const [taskFilter,setTaskFilter]=useState(state==='completed'?'all':'open');
  const [seenState,setSeenState]=useState(state);
  if(seenState!==state){setSeenState(state);if(state==='completed')setTaskFilter('all')}
  const [due,setDue]=useState(p.due),[stagesOpen,setStagesOpen]=useState(s.milestones.length>0);
  const settingsRef=useRef<HTMLFormElement>(null);
  useEffect(()=>{if(settings){const frame=requestAnimationFrame(()=>{const form=settingsRef.current,body=form?.closest<HTMLElement>('.sheet-body');if(form&&body)body.scrollTop+=form.getBoundingClientRect().top-body.getBoundingClientRect().top-66});return()=>cancelAnimationFrame(frame)}},[settings]);
  const editing=settings||!!stage,locked=busy||editing;
  useEffect(()=>{onEditing(settings||!!stage||!!removeStage);return()=>onEditing(false)},[settings,stage,removeStage,onEditing]);
  function openSettings(next?:ProjectStatus){setDue(p.due);setStatus(next??state);setPriority(p.priority);setGoalId(p.goalId??'none');setResult(p.result??'');setError('');setSettings(true);setTab('overview')}
  const addStage=()=>{setStagesOpen(true);setStage({id:crypto.randomUUID(),title:'',due:p.due,done:false,taskIds:[]});setError('')};
  const tasks=s.tasks.filter(t=>taskFilter==='all'||taskFilter==='done'?taskFilter==='all'||t.status==='done':taskFilter==='waiting'?t.status==='waiting'||!!t.blocker?.trim():t.status!=='done')
    .sort((a,b)=>Number(b.id===p.nextTaskId)-Number(a.id===p.nextTaskId)||Number(a.status==='done')-Number(b.status==='done')||a.due.localeCompare(b.due));
  const taskRow=(task:Task)=>{
    const readiness=workEligibility(data,task,today),milestone=(p.milestones??[]).find(m=>m.taskIds.includes(task.id));
    return <article className={`project-task-row ${task.status==='done'?'is-done':''}`} key={task.id} style={{'--task-category-color':calendarItemColor(task,data.preferences,'task')} as CSSProperties}>
      <div className="project-task-main"><Checkbox aria-label={`${task.title} 완료`} checked={task.status==='done'} disabled={locked} onCheckedChange={checked=>void perform({type:'task.status',id:task.id,status:checked?'done':'todo'},checked?'완료로 기록했습니다.':'다시 할 일로 옮겼습니다.')}/><button disabled={locked} onClick={()=>onOpen('task',task.id)}><strong>{task.title}</strong><span><span className={task.due<today&&task.status!=='done'?'overdue':''}>{task.due.slice(5).replace('-','/')}</span> · {task.duration}분 · {statusLabel[task.status]} · {categoryLabels[categoryOf(task)]}</span></button>{task.status!=='done'&&<button className={`project-pin ${p.nextTaskId===task.id?'is-pinned':''}`} aria-label={`${task.title} ${p.nextTaskId===task.id?'다음 행동 해제':'다음 행동으로 지정'}`} aria-pressed={p.nextTaskId===task.id} disabled={locked||!readiness.allowed&&p.nextTaskId!==task.id} title={!readiness.allowed?readiness.reason:undefined} onClick={()=>void perform({type:'project.next-task',id:p.id,taskId:p.nextTaskId===task.id?null:task.id},p.nextTaskId===task.id?'다음 행동 지정을 해제했습니다.':'다음 행동으로 지정했습니다.')}><Target size={18}/></button>}</div>
      {!readiness.allowed&&task.status!=='done'&&<p className="project-task-blocker">{readiness.reason}</p>}
      {!!s.milestones.length&&<label className="project-task-stage">단계<select value={milestone?.id??''} disabled={locked} aria-label={`${task.title} 단계 선택`} onChange={e=>void perform({type:'project.task-stage',id:p.id,taskId:task.id,milestoneId:e.target.value||null},'할 일의 단계를 변경했습니다.')}><option value="">미지정</option>{s.milestones.map(m=><option key={m.id} value={m.id}>{m.title}</option>)}</select></label>}
    </article>;
  };
  return <div className="project-detail-panel project-flow-detail" style={{'--illustration-accent':projectWorld(p.id,data.preferences).accent} as CSSProperties}>
    <div className="project-detail-art"><img src={projectWorld(p.id,data.preferences).image} width="960" height="720" alt=""/><CityThemeButton project={p}/></div>
    <div className="project-detail-surface">
    <div className="project-detail-heading"><span>ORBIT PROJECT · {projectStatusLabel[state]}</span><h2>{p.name}</h2><p>{p.goal||'완료 기준을 정해 보세요.'}</p><div><span>{s.done} / {s.tasks.length} 완료</span><strong>{s.progress??0}%</strong></div><Progress value={s.progress??0} aria-label="프로젝트 할 일 완료율"/></div>
    <div className="project-detail-quickbar"><button disabled={locked} className={`project-state-label state-${state}`} onClick={()=>openSettings()}>{projectStatusLabel[state]}<ChevronDown size={14}/></button><button disabled={locked} className={s.dueOver?'overdue':''} onClick={()=>openSettings()}><CalendarDays size={15}/>{p.due} 목표</button><button disabled={locked} className="icon-button" aria-label="프로젝트 관리 메뉴" aria-haspopup="dialog" onClick={onManage}><MoreHorizontal size={21}/></button></div>
    <Tabs value={tab} onValueChange={setTab} className="project-detail-tabs"><TabsList><TabsTrigger value="tasks" disabled={editing}>할 일 {s.tasks.length}</TabsTrigger><TabsTrigger value="resources" disabled={editing}>자료·기록</TabsTrigger><TabsTrigger value="overview">개요·관리</TabsTrigger></TabsList>
      <TabsContent value="overview">
        <section className="project-detail-section"><div className="project-section-heading"><h3>만들어야 할 결과</h3><button className="text-button" disabled={locked} onClick={onEdit}><Pencil size={14}/>수정</button></div><p className="project-result-text">{p.goal||'완료 기준을 입력해 주세요.'}</p>{p.goalId&&<p className="project-linked-goal"><Target size={14}/>{data.goals?.find(g=>g.id===p.goalId)?.sentence??'연결 목표 확인 필요'}</p>}
        <div className="project-detail-progress"><Progress value={s.progress??0} aria-label="할 일 완료율"/><span>{s.tasks.length?`${s.done}/${s.tasks.length} 완료 · ${s.progress}%`:'할 일이 아직 없어요'}</span></div></section>
        {state==='completed'?<section className="project-completed-outcome"><h3><CheckCheck size={18}/>완료 결과</h3><p>{p.result||'연결된 할 일을 모두 완료했습니다. 최종 결과를 남겨 보세요.'}</p>{!p.result&&<button className="secondary-button" disabled={locked} onClick={()=>openSettings('completed')}>최종 결과 기록</button>}{p.completedOn&&<small>{p.completedOn} 완료</small>}</section>:<section className="project-detail-next"><div className="project-section-heading"><h3>다음 행동</h3><button className="text-button" disabled={locked} onClick={()=>setTab('tasks')}>할 일 보기<ChevronRight size={14}/></button></div>{s.next?<button className="project-next-task-button" disabled={locked} onClick={()=>onOpen('task',s.next!.id)}><Target size={19}/><span><strong>{s.next.title}</strong><small>{s.next.due} · {s.next.duration}분{p.nextTaskId===s.next.id?' · 직접 지정':''}</small></span><ChevronRight size={18}/></button>:<><p>{state!=='active'?`${projectStatusLabel[state]} 프로젝트입니다.`:s.open.length?'대기·선행 작업 등 실행 조건을 확인해 주세요.':s.tasks.length?'할 일을 모두 마쳤어요. 최종 결과를 확인해 주세요.':'작게 시작할 첫 행동을 정해 보세요.'}</p><button className="secondary-button" disabled={locked} onClick={()=>state!=='active'?openSettings('active'):s.tasks.length&&!s.open.length?openSettings('completed'):s.tasks.length?setTab('tasks'):onCreate('task',p.id)}>{state!=='active'?'프로젝트 진행하기':s.tasks.length&&!s.open.length?'완료 결과 기록':s.tasks.length?'할 일 확인':'첫 할 일 추가'}</button></>}</section>}
        <section className="project-detail-section"><div className="project-section-heading"><button className="project-stage-toggle" disabled={editing} aria-expanded={stagesOpen||!!stage} onClick={()=>setStagesOpen(v=>!v)}>실행 단계 <span>{s.milestones.filter(m=>m.done).length}/{s.milestones.length}</span><ChevronDown size={16}/></button><button className="text-button" disabled={locked} onClick={addStage}><Plus size={15}/>단계 추가</button></div>
          {(stagesOpen||stage)&&<>
          {!s.milestones.length&&!stage&&<div className="project-stage-empty"><p>결과물을 중간 단계로 나누어 관리하세요.</p><small>예: 초안 완성 → 검토 → 최종 전달</small></div>}
          {s.milestones.map((m,index)=>{const completed=m.taskIds.filter(id=>data.tasks.find(t=>t.id===id)?.status==='done').length;return <div className={`project-milestone ${m.done?'is-done':''}`} key={m.id}><div className="project-milestone-line"><Checkbox checked={m.done} disabled={locked||!m.done&&completed<m.taskIds.length} aria-label={`${m.title} 단계 완료`} onCheckedChange={checked=>void perform({type:'project.milestone.upsert',id:p.id,milestone:{...m,done:checked===true}},checked?'단계를 완료했습니다.':'단계를 다시 진행합니다.')}/><div><strong><span>{String(index+1).padStart(2,'0')}</span>{m.title}</strong><small className={!m.done&&m.due<today?'overdue':''}>{m.due.slice(5).replace('-','/')} 목표 · {m.taskIds.length?`할 일 ${completed}/${m.taskIds.length}`:'연결된 할 일 없음'}{!m.done&&completed<m.taskIds.length?' · 할 일 완료 후 체크':''}</small></div><button className="icon-button" aria-label={`${m.title} 단계 수정`} disabled={locked} onClick={()=>{setStage({...m,taskIds:[...m.taskIds]});setError('')}}><Pencil size={15}/></button></div>{!!m.taskIds.length&&<div className="project-milestone-tasks">{m.taskIds.map(id=>{const t=data.tasks.find(t=>t.id===id);return t?<button key={id} disabled={locked} onClick={()=>onOpen('task',id)}><span>{t.status==='done'?'✓':'·'}</span>{t.title}</button>:null})}</div>}</div>})}
          {stage&&<form className="project-inline-form" onSubmit={async e=>{e.preventDefault();if(await perform({type:'project.milestone.upsert',id:p.id,milestone:{...(p.milestones?.find(m=>m.id===stage.id)??stage),title:stage.title.trim(),due:stage.due}},'실행 단계를 저장했습니다.'))setStage(null)}}><fieldset disabled={busy} className="project-inline-fields"><label>단계의 결과물<input required maxLength={160} value={stage.title} placeholder="예: 제안서 초안 완성" onChange={e=>setStage({...stage,title:e.target.value})}/></label><label>목표일<input required type="date" value={stage.due} onChange={e=>setStage({...stage,due:e.target.value})}/></label><p className="form-hint">할 일 탭에서 이 단계에 업무를 연결할 수 있습니다.</p><div className="project-form-actions"><button className="primary-button" disabled={busy}>단계 저장</button><button type="button" className="secondary-button" onClick={()=>setStage(null)} disabled={busy}>취소</button>{s.milestones.some(m=>m.id===stage.id)&&<button type="button" className="text-button danger-text" disabled={busy} onClick={()=>setRemoveStage(stage)}><Trash2 size={15}/>단계 삭제</button>}</div></fieldset></form>}
          </>}
        </section>

        <section className="project-detail-section"><div className="project-section-heading"><h3>프로젝트 관리</h3><button className="text-button" disabled={locked} onClick={()=>openSettings()}><Settings2 size={15}/>설정</button></div>
          {!settings&&<div className="project-management-actions"><button className="secondary-button" disabled={locked} onClick={()=>openSettings(state==='active'?'paused':'active')}>{state==='active'?'보류하기':'진행하기'}</button>{state!=='completed'&&<button className="secondary-button" disabled={locked} onClick={()=>openSettings('completed')}><CheckCheck size={15}/>완료 결과 기록</button>}</div>}
          {settings&&<form ref={settingsRef} className="project-inline-form" onSubmit={async e=>{e.preventDefault();if(status==='completed'&&!result.trim()){setError('완료한 결과를 한 줄 이상 기록해 주세요.');return;}if(await perform({type:'project.manage',id:p.id,status,due,priority,goalId:goalId==='none'?null:goalId,result},'프로젝트 관리 설정을 저장했습니다.'))setSettings(false)}}><fieldset disabled={busy} className="project-inline-fields">
            <label>상태<Choice value={status} onChange={v=>setStatus(v as ProjectStatus)} label="프로젝트 상태" items={Object.entries(projectStatusLabel).map(([value,label])=>({value,label}))}/></label>
            <label>목표일<input required type="date" value={due} onChange={e=>setDue(e.target.value)}/></label>
            <details className="project-settings-advanced"><summary>우선순위·목표 연결</summary><label>우선순위<Choice value={String(priority)} onChange={v=>setPriority(Number(v))} label="프로젝트 우선순위" items={[5,4,3,2,1].map(v=>({value:String(v),label:`${v} · ${priorityLabel(v)}`}))}/></label>
            <label>연결 목표<Choice value={goalId} onChange={setGoalId} label="프로젝트 연결 목표" items={[{value:'none',label:'연결 안 함'},...(data.goals??[]).map(g=>({value:g.id,label:g.sentence}))]}/></label></details>
            {(status==='completed'||result)&&<label>완료 결과<textarea required={status==='completed'} maxLength={4000} rows={3} placeholder="무엇을 완성했고, 어떤 결과를 얻었나요?" value={result} onChange={e=>setResult(e.target.value)}/></label>}
            {status!=='active'&&<p className="form-hint">새 자동 계획과 집중 시작에서 제외되며, 오늘 이후의 집중 지정은 해제됩니다. 이미 승인한 일정은 유지되며 일정 화면에서 조정할 수 있습니다.{s.tasks.some(t=>t.startedAt)?' 실행 중인 타이머는 종료하고 실제 시간을 기록합니다.':''}</p>}
            {status==='completed'&&s.open.length>0&&<p className="project-form-warning">미완료 할 일 {s.open.length}건은 기록에 남으며 자동 계획에서 제외됩니다.</p>}{error&&<p role="alert">{error}</p>}
            <div className="project-form-actions"><button className="primary-button" disabled={busy}>관리 설정 저장</button><button type="button" className="secondary-button" disabled={busy} onClick={()=>setSettings(false)}>취소</button></div>
          </fieldset></form>}
        </section>
      </TabsContent>
      <TabsContent value="tasks"><h3>{state==='completed'?'완료한 일':'지금 해야 할 일'}</h3><div className="project-task-filters" aria-label="프로젝트 할 일 필터">{[['open','미완료'],['waiting','대기'],['done','완료'],['all','전체']].map(([value,label])=><button key={value} aria-pressed={taskFilter===value} onClick={()=>setTaskFilter(value)}>{label}</button>)}</div><p className="project-task-guide">완료한 일은 체크하고, 다음 할 일을 선택하세요.</p>{tasks.map(taskRow)}{!tasks.length&&<div className="project-stage-empty"><p>표시할 할 일이 없습니다.</p><button className="text-button" disabled={locked} onClick={()=>onCreate('task',p.id)}><Plus size={15}/>할 일 추가</button></div>}</TabsContent>
      <TabsContent value="resources"><section className="project-detail-section"><h3>프로젝트 타임라인</h3><p className="muted">일정 → 회의록 → 후속 업무를 날짜순으로 확인하세요.</p>{projectTimeline(data,p.id).map(item=><button key={item.kind+item.id} className="project-resource-row" onClick={()=>onOpen(item.kind,item.id)}><CalendarDays size={17}/><span>{item.title}<small>{item.date} · {item.label} · {item.reason}</small></span><ChevronRight size={15}/></button>)}</section><div className="project-resource-actions"><button className="secondary-button" disabled={locked} onClick={()=>onCreate('event',p.id)}><CalendarDays size={16}/>일정 추가</button><button className="secondary-button" disabled={locked} onClick={()=>onCreate('meeting',p.id)}><FileText size={16}/>회의록 추가</button><button className="secondary-button" disabled={locked} onClick={onChat}><MessageSquare size={16}/>대화 열기</button></div><section className="project-detail-section"><h3>연결 일정 <span>{s.events.length}</span></h3>{s.events.slice().sort((a,b)=>Number(a.date<today)-Number(b.date<today)||a.date.localeCompare(b.date)||a.start-b.start).map(e=><button className="project-resource-row" key={e.id} onClick={()=>onOpen('event',e.id)}><CalendarDays size={17}/><span>{e.title}<small>{e.date} · {formatTime(e.start)}–{formatTime(e.end)} · {eventProjectReason(e)}</small></span><ChevronRight size={15}/></button>)}{!s.events.length&&<p className="muted">연결된 일정이 없습니다.</p>}</section><section className="project-detail-section"><h3>기록·자료 <span>{s.notes.length}</span></h3>{s.notes.slice().sort((a,b)=>b.updated.localeCompare(a.updated)).map(n=><button className="project-resource-row" key={n.id} onClick={()=>onOpen('note',n.id)}><FileText size={17}/><span>{n.title}<small>{n.updated} · {n.kind==='meeting'?'회의록':n.kind==='knowledge'?'참고 자료':'문서'}</small></span><ChevronRight size={15}/></button>)}{!s.notes.length&&<p className="muted">연결된 기록이 없습니다.</p>}</section>{(data.meetingRecords??[]).some(r=>r.projectId===p.id)&&<section className="project-detail-section"><h3>확정한 회의 결과</h3>{data.meetingRecords!.filter(r=>r.projectId===p.id).map(r=><button className="project-resource-row" key={r.id} onClick={()=>onOpen('note',r.noteId,r.noteRevision)}><CheckCheck size={17}/><span>{data.notes.find(n=>n.id===r.noteId)?.title??'회의 결과'}<small>확정 당시 기록</small></span></button>)}</section>}<details className="workspace-more"><summary>위임·회신·결정 확인</summary>{followup}</details><button className="text-button danger-text" disabled={locked} onClick={onDelete}><Trash2 size={15}/>프로젝트 삭제</button></TabsContent>
    </Tabs>
    {!editing&&<div className="project-detail-footer"><button className="primary-button" disabled={locked} onClick={()=>s.next?onOpen('task',s.next.id):state==='completed'&&!p.result?openSettings('completed'):projectStatus(p)==='completed'?openSettings('active'):onCreate('task',p.id)}>{s.next?'다음 할 일 열기':state==='completed'&&!p.result?'최종 결과 기록':projectStatus(p)==='completed'?'다시 진행하기':'할 일 추가'}<ChevronRight size={18}/></button><button className="secondary-button" disabled={locked} onClick={()=>onCreate('task',p.id)}><Plus size={17}/>할 일 추가</button></div>}
    </div>
    <AlertDialog open={!!removeStage} onOpenChange={open=>{if(!open)setRemoveStage(null)}}><AlertDialogContent><AlertDialogHeader><AlertDialogTitle>이 단계를 삭제할까요?</AlertDialogTitle><AlertDialogDescription>{removeStage?.title} 단계만 삭제합니다. 연결된 할 일은 프로젝트에 그대로 남습니다.</AlertDialogDescription></AlertDialogHeader><AlertDialogFooter><AlertDialogCancel disabled={busy}>취소</AlertDialogCancel><AlertDialogAction disabled={busy} onClick={async e=>{e.preventDefault();if(removeStage&&await perform({type:'project.milestone.delete',id:p.id,milestoneId:removeStage.id},'단계를 삭제했습니다. 할 일은 유지됩니다.')){setRemoveStage(null);setStage(null)}}}>단계 삭제</AlertDialogAction></AlertDialogFooter></AlertDialogContent></AlertDialog>
  </div>;
}
